### ISSUE TITLE
TV/EPG tab missing

### ISSUE THREAD

**Issue by bulcke** [xbmc/Kore#1004]
### Describe the bug
Here is a clear and concise description of what the problem is:

Kore Android app version 3.0.0 is missing the TV navigation tab. This is quite esential since it has the TV channels and EPG.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Show all tabs just like native Kodi does.

## Actual Behavior

TV tab missing.

## Possible Fix

According to https://github.com/xbmc/Kore/issues/23 it was in 2.0.0 

### To Reproduce

1. Open Kore app on Android smarthphone.
2. Notice tere is no TV tab the navigation menu.
3. Be disappointed.

### Debuglog

The debuglog can be found here:
Not applicable

### Screenshots 
Here are some links or screenshots to help explain the problem:

https://ibb.co/8Mw0jLw

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - Mobile device: Samsung Galaxy A32 5G
 - Android version: 13
 - Kodi version and platform: 20.3
 - Kore version: 3.0.0
 

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by SyncedSynapse** [comment]
PVR is TV, with EPG.

**Comment by bulcke** [comment]
I see.

Why would you name it different from Kodi? Other tab names are consistent with Kodi (Movies, TV Shows, Music).

**Comment by basilgello** [comment]
I recall it was 'PVR and TV' once, no?
