### ISSUE TITLE
[Feature Request]Option to sort albums by artist name an year rather than album title

### ISSUE THREAD

**Issue by DaveTBlake** [xbmc/Kore#101]
Would be useful to be able to control the sort criteria when listing albums. Currently albums are listed by title, but listing by artist name and year would be more natural - how I would put CDs on the shelf. Best as an option in case some people prefer the current approach.

**Comment by axelsimon** [comment]
Agreed, listing albums by year is what seems most obvious to me, but I can understand if some people prefer in alphabetical order. A way to chose this would be great.

**Comment by gvkt** [comment]
+1 for this suggestion

**Comment by TheYetiWakes** [comment]
+1 from me too.

**Comment by MartijnKaijser** [comment]
@SyncedSynapse @poisdeux this would be great option to have.
Sort by Artist/album  or sort by artist/album(year)    just like in Kodi itself

**Comment by poisdeux** [comment]
See #309. Note that I didn't implement @MartijnKaijser suggestion to sort by Artist/Album. Not sure if that is really useful as you can use the Artist screen to get the albums for a specific artist

**Comment by MartijnKaijser** [comment]
Problem is my library has about 6000 artists and only a handful has albums added.

**Comment by poisdeux** [comment]
So you'll only get the handful listed in the album list. Then sorting on artist should be enough right? Or do these artists have a kazillion albums?

**Comment by poisdeux** [comment]
Should be fixed in the next release. See #309
