### ISSUE TITLE
Missing skip buttons in notification

### ISSUE THREAD

**Issue by michucz** [xbmc/Kore#1014]
### Describe the bug
The skip forward/backwards buttons have disappeared from the notification

## Expected Behavior
There used to be a skip forward/backwards buttons in the notification

## Actual Behavior
The buttons are gone

## Possible Fix
Couldn't find anything in the settings

### Screenshots 
Here are some links or screenshots to help explain the problem:
![Screenshot_20240227-133350_Bromite_1](https://github.com/xbmc/Kore/assets/26311948/e66b88e6-97e0-4bf4-9139-88effa4dfea5)

### Your Environment
Used Operating system:

 - Mobile device: Samsung Galaxy S9
 - Android version: lineageos 20 (android 13)
 - Kodi version and platform: kodi 20.2 (osmc)
 - Kore version: 3.1.0
 

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by SyncedSynapse** [comment]
The notifications follow Android's guidelines for media notifications, and use the same framework. Android updated its guidelines to show fewer buttons on the notifications, hence the change.
