### ISSUE TITLE
Missing BACKWARD and FORWARD buttons in lock screen

### ISSUE THREAD

**Issue by jEsuSdA** [xbmc/Kore#1016]
### Describe the bug
Here is a clear and concise description of what the problem is:

I just updated Kore and I noticed there are some useful buttons that are gone in the latest version: the backward and forward buttons.

## Expected Behavior
Here you can see the previous version:

![Screenshot_2024-03-06-15-52-46-279_lockscreen](https://github.com/xbmc/Kore/assets/5833446/ef694ce4-e9ea-4d52-8299-d8b93137f04f)

Buttons:
- Previous
- Backward
- Play/Pause
- Forward
- Next

## Actual Behavior

Here you can see the actual behaviour:

![Screenshot_2024-03-06-15-53-25-779_lockscreen](https://github.com/xbmc/Kore/assets/5833446/297ae84e-9cba-4da5-b941-1b256b8916f9)

Buttons:
- Previous
- Play/Pause
- Next

## Possible Fix

Could you add the lost buttons in next release or tell me what configuration I must to change to get back again?

### Your Environment

 - Mobile device: Xiaomi Redmi Note 12 Pro
 - Android version: Android 13 + MIUI 14.0.1
 - Kodi version and platform: Kodi 20.5 on Debian GNU/Linux
 - Kore version: v3.1.0
 

Thank you so much!

**Comment by SyncedSynapse** [comment]
Please see #1014 for the explanation, as the reason is the same.
