### ISSUE TITLE
Launcher icon shortcuts for quick access to media centers

### ISSUE THREAD

**Issue by lameventanas** [xbmc/Kore#1023]
## Feature suggestion
**Detailed Description**

Let's say I have more than one media center added to Kore.
I would like to easily choose which one to use when starting Kore, by using Android's launcher shortcut.
Eg: long-press the launcher's icon, then I would get a menu with each media center, and on selecting them, Kore would run and connect to it.

I don't know the technical term for this function, but if you long-press the Chrome or Firefox icon, you will get a menu with "New Tab", "New Private Tab", etc.
Kore would show a menu with all the media centers you have added.

### Context

It would benefit people that have added different instances of Kodi to Kore.

### Additional context, screenshots or links
Here are some relevant links or screenshots:

![kore-shortcuts](https://github.com/user-attachments/assets/c7e7a443-3c08-442e-a6fe-cd6215f65ff2)

*Note: Team Kodi will consider this item however we will not make any promises if it will be included.*

**Comment by SyncedSynapse** [comment]
This is already implemented...
