### ISSUE TITLE
“Various Artists” albums don't show song artists

### ISSUE THREAD

**Issue by axelsimon** [xbmc/Kore#104]
Hi,

Right now, if an album is marked as Various Artists, Kore will show the following when showing the album: tracknumber, title and track length.

But not the artist.

It is often hard to know what song you're about to play without the artist's name ;)

I think putting the artist's name where the track length currently is and moving track length to the right of that should work nicely to solve the issue.

Thanks!

axel

**Comment by SyncedSynapse** [comment]
Done in #281
