### ISSUE TITLE
[feature request] SMS and call (and more) notifications to Kodi

### ISSUE THREAD

**Issue by shtrom** [xbmc/Kore#108]
The old XBMC remote had this cool feature that you could get notification of incoming text messages and phone calls, and it would even pause the playback when a call came in. It would be pretty neat to add this to Kore. Or even a more generic notification framework where you could select which app's notifications are forwarded to Kodi.

**Comment by SyncedSynapse** [comment]
Not a fan, as it requires pretty invasive permissions (access calls, sms, etc) on the device.

I might take a look when the new M version comes out, as the permission system is changed, but for previous (current) versions, this won't be done.
