### ISSUE TITLE
[feature request] Lock screen widget

### ISSUE THREAD

**Issue by shtrom** [xbmc/Kore#109]
At least on CM11, there is the option of adding widgets to the lock screen. It would be pretty cool to have the Kore remote control available there without having to unlock the device!

**Comment by SyncedSynapse** [comment]
Widgets on lockscreen were removed in recent Android versions.

In any case, go into settings and check the "Show notification". The notification should show up on the lockscreen and allow you to control Kodi, if your phone supports lockscreen notifications.
