### ISSUE TITLE
Send local file to Kodi

### ISSUE THREAD

**Issue by TheLastProject** [xbmc/Kore#110]
Currently, I use [DroidUPnP](https://trishika.github.io/DroidUPnP/) to send music on my phone straight to Kodi to play using UPnP.

However, it would be nice if Kore could do this by itself, because it is a lot nicer to only use a single app for all your Kodi-related needs instead of having to switch between several apps.

**Comment by SyncedSynapse** [comment]
I understand and see the merit of your suggestion, but turning Kore into a UPnP server isn't really in my plans right now. I just don't see this being done in the short/medium term, so i don't think this issue should be kept open.
