### ISSUE TITLE
Please make media center configuration available from a more obvious place

### ISSUE THREAD

**Issue by wp9015362** [xbmc/Kore#111]
@SyncedSynapse :

After having set up Kore, I was searching and searching and searching for the media center configuration.

I just couldn't find it.

Then I noticed that you can tap on the media center's name at the top of the menu that can be swiped in from the left side of the screen and that tapping on it leads to the media center configuration.

IMHO this is too hard to find.

Could you please move the media center configuration to a more obvious place?

My suggestion would be:

Just add a "Media center configuration" section to the normal settings (where you can also configure the theme and other options and where the About section is).

Regards

**Comment by petterreinholdtsen** [comment]
I agree.  In fact, I would like to more dynamically switch between several kodi instances on my local network without having to manually change IP address.  it would make kore work more like chrome with chromecast, where one can select which instance to select when sharing a video.  At home I have several kodi instances running, one for each screen available, and I would like to be able to select which screen to control quickly both from the remote control interface and from for example the youtube 'share' option.
