### ISSUE TITLE
Videos shared from YouTube app are played twice (or more)

### ISSUE THREAD

**Issue by mruwek** [xbmc/Kore#112]
After 1.5.0 update every video shared from YouTube app via "Play on Kodi" plays twice or even more (playlist grows each time Kodi goes to background and is afterwards "maximized" from "recent apps").

**Comment by mruwek** [comment]
I've looked into this today and it seems like Kore is sending YouTube URL also in such situation as:

1. Share YouTube video via Play on Kodi, Kore is launched automatically.
2. Screen of the phone turns off after 30 seconds (or other amount of time set in settings of screen)
3. Video ends
4. Turn the screen on and unlock the device - Kore is foreground of course.
5. After a second or less video is added again to queue and played.

**Comment by ainola** [comment]
Yep, it's always happens when I share a video, lock the screen, then wake my smartphone after watching the video.

I've seen the playlist grow to ~10 videos from it, too!
