### ISSUE TITLE
Kore should use switches instead of checkboxes in the settings to adhere to Google Material Design Guidelines

### ISSUE THREAD

**Issue by wp9015362** [xbmc/Kore#115]
@SyncedSynapse :

Currently Kore is using checkboxes in the settings.

But the Google Material Design Guidelines clearly say:

> https://www.google.com/design/spec/components/selection-controls.html
> 
> [...] If you have a single option, avoid using a checkbox and use an on/off switch instead. [...]

So, could you please replace them with switches?

Regards

**Comment by wp9015362** [comment]
@SyncedSynapse :

The discussion over there might be helpful (regarding compatibility with older Android versions), see:

https://github.com/connectbot/connectbot/pull/205

Regards

**Comment by SyncedSynapse** [comment]
In d271d0b17a24a81a27f4b8e2634b7e1fbe5d554b
