### ISSUE TITLE
[Feature Request] add native on-screen-keyboard for android version

### ISSUE THREAD

**Issue by yuvalif** [xbmc/Kore#121]
in android devices, currently searches are only available through sending text option.

**Comment by SyncedSynapse** [comment]
What exactly is the request? There's the option "send text to media center" in the overflow menu, which shows a on-screen keyboard.

**Comment by yuvalif** [comment]
in android you use the on screen keyboard to type in a text box in the app, and then the text to the host. while in iOS app, when you point into a text box on the host you can use the on screen keyboard to type directly into the host.

**Comment by SyncedSynapse** [comment]
I understand that you prefer one kind of keyboard over the other, but i see no compelling reason for changing this right now. It's just a personal preference, afaict, the functionality is there, and i won't create an option to do both versions, as i don't think it is justified. Sorry,

**Comment by yuvalif** [comment]
probably i wasn't so clear. this is not a amtter of keyboard preference. the request is, when itype in my smartphone kwyboard, instead of typing into the textbox in the app, and then send the text tothe keyboard on the tv screen; type directly into the text box of the keyborad on the tv screen.

Sent from Yahoo Mail on Android

**Comment by SyncedSynapse** [comment]
I got it. And what i meant was that both ways achieve the same thing, and the remote has one implemented, so i don't see the value of adding another way of doing the same thing.
