### ISSUE TITLE
[Feature request] Shutdown timer

### ISSUE THREAD

**Issue by tristanlins** [xbmc/Kore#132]
I miss the custom shutdown timer in the shutdown menu.

**Comment by SyncedSynapse** [comment]
I can't find support for it on Kodi's jsonrpc API, so you'll have to keep using the GUI for that.

**Comment by tristanlins** [comment]
Mh, but I use a keyboard-less Raspberry with openelec and cannot access the GUI ;-D

The inofficial xmbc remote has a button "Press S" which opens the GUI shutdown dialogue.
Perhaps you could add "shutdown dialogue" option?!

**Comment by SyncedSynapse** [comment]
Hadn't thought about that, it might make sense including that option and removing the suspend and reboot.

Anyway, you don't need a keyboard to navigate the GUI. I don't know which skin you're using, but navigate to the power icon (on the bottom in the default skin) with the remote d-pad, click on it and the shutdown menu appears. Or am i missing something?

**Comment by tristanlins** [comment]
Youre right. I didn't know that I can navigate to the power button with the d-pad ;-D

Thanks for this hint! :-)
