### ISSUE TITLE
Vibrate on button press toggle button has different animation as the other toggle buttons 

### ISSUE THREAD

**Issue by MartijnKaijser** [xbmc/Kore#159]

**Comment by SyncedSynapse** [comment]
That's a clinical eye :)

Anyway, this looks like an Android bug. That setting isn't different from the others, and i just did a quick test, where i exchanged the order of the settings, and the wrong animation is always applied to the "last" one on the list (doesn't matter which one is last). 

To check this, edit app/src/main/res/xml/preferences.xml and exchange the last `SwitchPreference` with one of the others.

I'm going to close this, as this can't be solved on Kore's end.
