### ISSUE TITLE
Provide global search for a track name

### ISSUE THREAD

**Issue by jondo** [xbmc/Kore#160]
I have got some songs that I often want to access directly. Currently I always have to (try to) remember which albums they are on in order to navigate to them and play them. I would prefer having an top level display of 'tracks' in the same way as for 'artists' and 'albums', where I can just type part of the song's title into the search field.

**Comment by poisdeux** [comment]
Not sure what your solution is. What I would suggest is use the search query at artists or albums overview to search through songnames as well. This means you also get artistnames or albumnames that contain a song that matches the query. Would that work for you?

**Comment by jondo** [comment]
I think your suggestion would give surprising results and would not be findable and understandable by users. Searching by artist, album or song should not be mixed.

**Comment by SyncedSynapse** [comment]
I also think this would cause some confusion to users. The obvious solution is to add a "songs" tab (which can also solve the issue of showing songs without albums), but i have doubts about its general usability. I just can't see myself browsing and searching through all the songs of my music collection, but then, maybe that's just me. It might also have performance issues.

**Comment by jondo** [comment]
The songs tab could be search-only: It could stay empty until three letters of a search word are entered.

**Comment by poisdeux** [comment]
Ok, I agree that mixing the search over artists/albums/songs will be confusion.
I guess we could give a songs tab a chance. Scrolling through a large list should not be a problem, searching however might give some noticeable delays. To make the user aware the app is still searching, we could show a progress indicator while the cursor is loading.
I would then also add the play button on the songs tab to be able to quickly play all songs matching the search query. I find it sometimes very amusing to play all tracks containing a specific word.

**Comment by poisdeux** [comment]
#240 implements this feature request. This can be closed.

**Comment by jondo** [comment]
Sorry, I can only use this feature (and close this issue) after Kore is updated on F-Droid or Play Store. Both are on the latest version 2.0.0, which is nearly half a year old. @SyncedSynapse ?

**Comment by SyncedSynapse** [comment]
@jondo Soon. I'm closing this one for now, if after you check it you have some additional comments, place them here.
