### ISSUE TITLE
 connection wizard can't auto find new kodi installs anymore 

### ISSUE THREAD

**Issue by MartijnKaijser** [xbmc/Kore#165]
The wizard can't find any Kodi installs anymore while manually adding them works instant

**Comment by SyncedSynapse** [comment]
Nothing changed on the wizard @MartijnKaijser. Specifically, the zeroconf code hasn't been touched in some time (IIRC). I've also just tested it (on Linux, with avahi) and it worked fine.

Are you sure nothing changed on the other end?

**Comment by MartijnKaijser** [comment]
tried my phone and tablet. Tried to connect to 4 different setups. Windows/2x Openelec/Android/

**Comment by SyncedSynapse** [comment]
Openelec worked for me.

Are you blocking port 5353 on your network?

**Comment by SyncedSynapse** [comment]
Hey @MartijnKaijser , this is still an issue for you? Are you sure you haven't changed anything on your network that might impact the discovery? This part of the code hasn't changed on a long time.

**Comment by MartijnKaijser** [comment]
I actually just added a new kodi instance and it worked on first try. No clue what changed
