### ISSUE TITLE
[Feature Request][PVR] channel group selection by click on header labels

### ISSUE THREAD

**Issue by xhaggi** [xbmc/Kore#167]
If you first go to the PVR section you are able to select a channel group, but you can't re-select another one except you switch to another section like Movies, Music etc. and then back to PVR. So I suggest to show the channel group selection if you click on the header labels "TV-Channels" or "Radio-Channels".

**Comment by SyncedSynapse** [comment]
You can change select another channel group, just use the back button.

Using a dropdown box on the header isn't viable because the list has tabs.

**Comment by xhaggi** [comment]
Mhhh not very user-friendly, why not back to the group selection if you click on the header label. I don't want a drop-down or something else.

**Comment by SyncedSynapse** [comment]
There's a bug that i hadn't noticed: The hamburger menu should change to a back arrow when you select a group channel, visually indicating that you can go back, and allowing you to tap it to go back.

I'll fix it soon.

**Comment by SyncedSynapse** [comment]
Done in eca7d2b2ad81da26b2c8c04dab2dd0d7ab1c0deb

I've started a build on Jenkins and when it ends it should be available here: http://mirrors.kodi.tv/tools/kore/test-builds/

I would appreciate if you could test it, as my PVR is somewhat limited (and kind of broken, as it doesn't store channel groups).

**Comment by xhaggi** [comment]
great will give it a try when it's on the mirror

**Comment by xhaggi** [comment]
works so far, but if you select a tv group and then switch to radio channels where I only have one group, the back-arrow will remain and has no effect if you click on it. After clicking on the arrow icon the menu icon is shown and if you now click on tv channels you end-up in the channel view with no arrow icon indicating that it's possible to go back to the group selection.

Another issue you can't access the side menu if you are in tv channels after selecting a group. You always need to go back and then you can open the side menu.

As suggested, why not show the group selection if you click on the tv or radio channel tab + the hardware back button which is already possible?

Thanks anyway!

**Comment by SyncedSynapse** [comment]
Hey @xhaggi 
Hopefully the hamburger menu/back arrow issues are fixed with the latest PR. That icon is mainly used to signal navigation from/to upper and lower level views. When in the upper level (hamburger menu showing up) it is used to open the side menu. The side menu can always be opened by swiping from the left.

**Comment by xhaggi** [comment]
Hey thanks for your work on this minor stuff, but I've to say it don't work. the arrow and the selected group name is visible if you jump over to radio or recordings. I would expect that it show me the group depending on the context you've selected (tv or radio) and no group + the hamburger menu if you enter recordings.
