### ISSUE TITLE
List of TV episodes/movies doesn't sync automatically

### ISSUE THREAD

**Issue by edmorley** [xbmc/Kore#169]
If I add new TV series/episodes or movies, and then reopen Kore v2.0.0 - I have to initiate a manual sync for them to appear in the list of content in Kore, rather than a sync being performed automatically.

**Comment by SyncedSynapse** [comment]
This is by design, and i plan to keep it that way.

You may have a big library, and it shouldn't be updated each time you go into the shows (or music, or movies) list, so i think it's best that it is kept as a manual option.

**Comment by edmorley** [comment]
Yeah makes sense, thank you for the follow-up :-)

**Comment by rmbleeker** [comment]
@SyncedSynapse can we at least get an option in the settings to enable automatic sync as soon as Kore connects to Kodi? Or perhaps when you enter a library for the first time during a session? I'm fine with it being disabled by default.

I always use Kore over my very stable and high bandwidth wifi so the size of the library is not an issue, but with new stuff being added on an almost daily basis, for example new TV show episodes, having to do a manual sync every time is quite tedious.

**Comment by SyncedSynapse** [comment]
@rmbleeker If you only add new TV show episodes, Kore already keeps them up to date: when you select a TV show, if silently refreshes that tv show, so any new episodes show up immediately (and the watched count gets corrected).
Nevertheless this doesn't apply to new Movies, Music or new TV Shows.
I'll reopen this. I'm not opposed to this being an option, disabled by default.

**Comment by rmbleeker** [comment]
You're right about existing TV Shows refreshing when selected. I never realized it but I tested it and it works.

Thanks for considering implementing something similar for the other categories.

**Comment by glenntanner3** [comment]
While on the subject of sync, I feel i have a fairly large repo and doing a full resync for TV shows when I add one new one takes forever. Is there anyway it can be tiered so that refreshing the TV show list only grabs the list of shows, entering the show refreshes the episodes? I'm not sure a full resync even completes in Kore any long on my phone.
