### ISSUE TITLE
Please populate the "Releases" section.

### ISSUE THREAD

**Issue by timofonic** [xbmc/Kore#172]
Hello.

Can you please put the Kore releases here for better vibility? And in the Kodi site, please!

http://mirrors.kodi.tv/tools/kore/releases/

Kind regards.

**Comment by SyncedSynapse** [comment]
It IS in the releases section...

As for the website, it has the link to Google Play, which is the preferred distribution platform.

**Comment by timofonic** [comment]
I don't use Google Play services, but F-Droid.

**Comment by SyncedSynapse** [comment]
So, get it from F-Droid. It is there.

**Comment by timofonic** [comment]
Yes, you are right.

Thanks again!
