### ISSUE TITLE
Remember position of episode listview

### ISSUE THREAD

**Issue by rigid** [xbmc/Kore#186]
When browsing episodes of a tv-series, the collapsed-state and list position isn't remembered so that browsing them to build a playlist requires to scroll/collapse repeatedly for every episode.

**Comment by poisdeux** [comment]
This has been fixed for the new release. Unfortunately, I was not quick
enough to get it into 2.0 :(.

https://github.com/xbmc/Kore/pull/177

**Comment by rigid** [comment]
awesome, thank you!
