### ISSUE TITLE
[feature request] longpress to add episode to playlist

### ISSUE THREAD

**Issue by rigid** [xbmc/Kore#187]
it would be nice to have a context menu for episodes on longpress. "Add to playlist" and similar entries (like in the kodi gui context menu) would be useful items.

**Comment by poisdeux** [comment]
Currently the context menu is activated through a context menu button in each list item. See the music lists for an example. Would that also work for you for episodes?

**Comment by rigid** [comment]
Yes, i think that would be fine. Actually I event think that's better.
That way, longpress would stay free to enter some "multi-selection" mode in the future. (So multiple items could be Added to the playlist/Deleted/...)

**Comment by poisdeux** [comment]
Implemented and merged into the mainline.
