### ISSUE TITLE
Get more info about connection failing with Kodi/XBMC

### ISSUE THREAD

**Issue by cmoulliard** [xbmc/Kore#188]
I can access my Kodi station running on Raspberry using Sybu Kodi remote controller but not with Kore or Yatse. Is there a way to get more log info about why the connection fails within the Android Smartphone Application ?

**Comment by SyncedSynapse** [comment]
Only if you're willing to build a debug version, and then look at the logcat output...

I wouldn't go that far. That is usually a connectivity issue, so i would make sure that you have the necessary ports correctly specified and open (80 or 8080 and 9090) on your network.

**Comment by poisdeux** [comment]
@cmoulliard are you still unable to connect with Kore? If you need help compiling a debug version just let me know.
