### ISSUE TITLE
[PVR] problem with channel color option

### ISSUE THREAD

**Issue by criniera** [xbmc/Kore#191]
I make use of the PVR IPTV simple client addon (playlist url: http://kodilive.eu/tv) in my XBMC. this addon make use of the color option in the channel name, so that a channel name is like this "[COLOR orange]Rai 1[/COLOR]". In XBMC i see "Rai 1" written in orange, while in the PVR section of kore i see "[COLOR orange]Rai 1[/COLOR]", this makes impossible to read the channel name because is too long.

![screenshot_2016-01-31-00-55-32](https://cloud.githubusercontent.com/assets/16980409/12701964/b8fa9aac-c819-11e5-9069-e8f8d13923e0.png)
![20160131_005438](https://cloud.githubusercontent.com/assets/16980409/12701965/b90a517c-c819-11e5-8459-08d7e5f3e5c0.jpg)

**Comment by SPDurkee** [comment]
I second this. IPTV is much more popular now. Please add support for tags in titles. Thanks!
