### ISSUE TITLE
Add Travis-CI file to auto test compile PRs

### ISSUE THREAD

**Issue by MartijnKaijser** [xbmc/Kore#195]
For Kodi and binary addons we are also adding Travis-CI build file so each PR gets auto compile tested

**Comment by poisdeux** [comment]
That looks interesting. We need to start adding unit tests as well I guess.

**Comment by MartijnKaijser** [comment]
Some info can be found here
https://docs.travis-ci.com/user/languages/android

I've already enabled it so once the .travis.yml file is there is should start "working" and can be tweaked to our liking.

**Comment by MartijnKaijser** [comment]
https://github.com/xbmc/Kore/pull/198
