### ISSUE TITLE
[Feature request] Automatically pause playback when an incoming phone call arrives

### ISSUE THREAD

**Issue by sputtene** [xbmc/Kore#197]
Can you please add a setting to automatically pause playback when a phone call arrives (and resume playback when the phone call ends)?

It would make your already great app even better :)

Thanks!

**Comment by MartijnKaijser** [comment]
https://github.com/xbmc/Kore/pull/190

**Comment by sputtene** [comment]
Oh, great, thanks! I browsed the issues to make sure I wouldn't make a duplicate request, but I didn't check the pull requests.

**Comment by SyncedSynapse** [comment]
In latest version.
