### ISSUE TITLE
Mute button hard to find and not highlighted

### ISSUE THREAD

**Issue by lebeno** [xbmc/Kore#199]
When Kodi has been muted and there is no media playing, I can find no (un)mute button or indication in Kore. When there is media playing, the (un)mute button is only visible on the "now playing" screen, not on the "remote" screen and it is not highlighted to indicate the muted state when Kodi was muted before the current playback started.

I did spend some time going through different screens to find the (un)mute button, only on one of the three "remote" screens. Although Kodi displays a very visible red "muted" icon in the top right corner of the screen, I regularly use Kore as a headless remote when playing music. A more prominent mute state button would be handy, certainly in the case where Kore is used to control Kodi without a screen.

Steps to reproduce: Play some music, mute Kodi in the "now playing"screen of Kore, stop all playback. Go to music, start playback of any artist or album. Go to Menu > Remote and there is no (un)mute button or indication. When you swipe left the (un)mute button is visible but not highlighted to indicate the currently muted state.

**Comment by RogerTheShrubber1** [comment]
F8 key will toggle mute on/off
