### ISSUE TITLE
[Feature suggestion] Make remote screen shortcuts configureable (same way as side menu)

### ISSUE THREAD

**Issue by Orclas** [xbmc/Kore#201]
Just wrote a "+1 comment" regarding adding a favorites shortcut to the side menu and noted that I would love a remote screen shortcut too, except there's no space for it.

That's fine and I really like the clean style of Kore, but on the other hand, why not make the remote screen shortcut buttons configurable just as the side menu items are? That way users could configure them based on personal preference, replacing default buttons with for example PVR or Weather.

**Comment by poisdeux** [comment]
Closing this as I believe #355 fixes this.
