### ISSUE TITLE
Show file sizes in movie summaries

### ISSUE THREAD

**Issue by willghatch** [xbmc/Kore#205]
I have multiple copies of some movies in my library because I have transcoded some to a smaller format (to put on a phone, for instance).  When I look through the movies listed the preview has a convenient button for downloading to my phone, and shows info such as the film length, year, ratings, etc.  But the most important piece of information to me is often the file size.  It would be great to add it to the summary of data available.

**Comment by tomerf** [comment]
#253 The size is available in the media file list view

**Comment by SyncedSynapse** [comment]
@tomerf has implemented showing the file size on the "Files" section, which i think is the appropriate place to show it. I'm not a fan of showing the file size in the movies/tv shows summary - the metadata that's available there is more useful and i don't like cluttering up the interface.

I'll be closing this one. I'm not extremely opposed to it, but i don't think that it's something the majority of users would benefit.
