### ISSUE TITLE
When OpenVPN connects, Kore can't connect to the server. 

### ISSUE THREAD

**Issue by qdii** [xbmc/Kore#217]
Disconnecting from the VPN server solves the problem.

**Comment by yarons** [comment]
This might be a VPN issue or a networking/routing issue, are you able to access the port without Kore?

**Comment by poisdeux** [comment]
I'm guessing you used auto configuration to configure Kore for your Kodi instance. When using VPN, your IP-network will change (not physically, of course). This means the server will be reachable by a different IP-adress. If this is the case, you can fix this by adding a new media center in Kore when connected through VPN.

Another solution, which is a bit more complex, would be setting up a DNS server which will resolve hostname->ip-adress translations for your VPN network. Then configure OpenVPN to serve the new DNS server to your devices. You will also need a second DNS server to resolve the hostname to the ip-adress on the network without using VPN. And make sure the second DNS server is served to your clients when not using VPN.

Hope this helps...

**Comment by SyncedSynapse** [comment]
This doesn't seem to be an issue on Kore. Any news on this?

**Comment by poisdeux** [comment]
Guess not. I'm closing this. @qdii reopen if you have additional info.
