### ISSUE TITLE
Add button "Get it on F-Droid"

### ISSUE THREAD

**Issue by PanderMusubi** [xbmc/Kore#220]
Please, add a button "Get it on F-Droid" with a PNG file from https://commons.wikimedia.org/wiki/File:Get_it_on_F-Droid.svg in your README file on GitHub and on your website under "Official remotes" with the appropriate link to the page of your app on F-Droid.

**Comment by jondo** [comment]
First of all, a current version should be brought to F-Droid. [They could not build v2.1.0.](https://f-droid.org/wiki/page/org.xbmc.kore#v2.1.0)

**Comment by PanderMusubi** [comment]
Bit short explanation on why it doesn't build. Hope more can be done.

**Comment by jondo** [comment]
I have asked for more information [in F-Droids forum](https://f-droid.org/forums/topic/kore/#post-21731).

**Comment by jondo** [comment]
Now the current v2.1.0 is in F-Droid.

**Comment by mueller-ma** [comment]
I made a PR with a link to fdroid since there is no button for play store

**Comment by mueller-ma** [comment]
@PanderMusubi @jondo The link is merged now

**Comment by PanderMusubi** [comment]
Nice! Note that height of 80 (as recommended) instead of 60 will render the badge a bit more nice.

**Comment by mueller-ma** [comment]
How do you know that 80 is recommended?

**Comment by PanderMusubi** [comment]
Because I was involved in the writing of the badge guide. You will also see that the text GET IT ON will be better readable. Nevertheless, you can choose whatever you want of course.
