### ISSUE TITLE
Android notifications by core ain't removable, even when kodi isn't running

### ISSUE THREAD

**Issue by JVApen** [xbmc/Kore#221]
Hi,

I'm using the Kore app on my Android Phone (Nexus 5X, fully up-to-date) and am running Kodi 16.0 on my Ubuntu 14.04
When using the Kore app to connect to my PC and stop a video which is playing, the notification center of android still shows the file that I was playing. This notification only gets removed if I kill the process of Kore.

If you need some more info, just let me know

**Comment by SyncedSynapse** [comment]
The notification isn't removable, but it only stays on while something is playing on Kodi. It is also removed when the connection is lost.

Are you sure you stopped the video and not paused it?

**Comment by JVApen** [comment]
Yes, I'm sure, I've even closed down Kodi on the PC.

**Comment by SyncedSynapse** [comment]
Odd. I can't reproduce this on any of my systems.

**Comment by SyncedSynapse** [comment]
Do you still get this?
