### ISSUE TITLE
[Feature Request] Add support for mDNS (Avahi/Zeroconf)

### ISSUE THREAD

**Issue by lukasubo** [xbmc/Kore#224]
It would be very useful for the remote to be able to connect using a "devicename.local" address, rather than the device's actual IP. That way, if the IP changes, the remote will continue to work. Thank you for your hard work on this application, it really enhances my day to day experience with Kodi.

**Comment by SyncedSynapse** [comment]
This is supported currently. You might have some network firewall that is preventing it from working.

**Comment by dogtopus** [comment]
@SyncedSynapse This doesn't work for me. In fact, I can only see the mdns query packet when Kore discovers avaliable media centers (and the discovery worked), and I got absolutely nothing when try to connect use the MC's .local hostname instead of the IP address that corresponds to it.
