### ISSUE TITLE
Add new remote, 100% volume never disappears from screen!

### ISSUE THREAD

**Issue by AnsuRio** [xbmc/Kore#225]
Hi all!

Asked the people over att OSMC about this also, but they thought it could also be a problem with the remote app, and therefore I´m putting this up here.

When I add a new remote the 100% volume appears at top of the screen and to get rid of it I need to reboot the system.

What do you guys need from me around this?

Best

**Comment by SyncedSynapse** [comment]
When you add a new remote it tries to check if the EventServer protocol is supported. To do so it checks if Kodi is muted, sends a mute/unmute command (via EventServer) and checks again to verify if the command had any effect (if it didn't EventServer isn't available). Then it reverts back the volume to the initial state.
When you mute/unmute OSMC with a traditional remote does it also always show the 100%?

**Comment by breakthecode** [comment]
I only have Kore at the moment to test with, so hard to check right now.

**Comment by poisdeux** [comment]
Does this problem still occur?

**Comment by SyncedSynapse** [comment]
Closing this, as it doesn't seem to be an issue on the remote and there hasn't been any info for a while.
