### ISSUE TITLE
[feature request] TV & EPG Support

### ISSUE THREAD

**Issue by rigid** [xbmc/Kore#23]
Kore is an awesome controller for Kodi, thanks to all contributors for their efforts!
It would be nice, if TV (with EPG) would also be supported among Music, TV Series, Music and Applications.

**Comment by SyncedSynapse** [comment]
I don't have PVR/TV hardware to use with Kodi, so someone else will need to do this...

**Comment by rigid** [comment]
:( is there someone among the devs who could do it? Or maybe there is a way to setup some dummy PVR thingy?
Would donating a USB DVB-T receiver to you be an option?

**Comment by SyncedSynapse** [comment]
Thanks for the offer, but i don't think that would be a good option.

I guess that sooner or later, someone will come along and add support for it.

**Comment by rigid** [comment]
ok, I hope you're right ;)

**Comment by SyncedSynapse** [comment]
Being taken care of.

**Comment by kenji123** [comment]
Is this still being taken cared of? It's been a while.

**Comment by rigid** [comment]
included in 2.0.0 ... awesome! thank you!
