### ISSUE TITLE
Server IP Change

### ISSUE THREAD

**Issue by Lawgrin** [xbmc/Kore#243]
I know the simple solution to this is just to hard code it on the raspberry/router. But i do believe a switch server/clear server would be an awesome addition. (Play store version app)

**Comment by SyncedSynapse** [comment]
Why don't you use the computer name instead of the IP, assuming it can be resolved on your network.

Don't know what you mean by "switch/clear server" but you can edit the ip/name of your kodi instance.

**Comment by Lawgrin** [comment]
In settings i want to be able to remove the server if that server has changed or lost. Basicly a "resetup" option

**Comment by SyncedSynapse** [comment]
So, click on the server name on the left side menu.
