### ISSUE TITLE
Control pad not working

### ISSUE THREAD

**Issue by moleculezz** [xbmc/Kore#246]
Hi,

Have a Nexus 5X and the Remote (control pad) stopped working. The back button and the center button works. But navigating with the arrow keys doesn't work.
I've recently upgraded to Android N dev preview 3, and it has the same problem.

**Comment by poisdeux** [comment]
I can't reproduce this issue running android 6 and using Kodi 16.0. Which version of Kodi are you using?

**Comment by moleculezz** [comment]
I'm running Kodi 16.1

**Comment by poisdeux** [comment]
Just updated kodi and it is still working for me. You said it stopped working, so I'm assuming it worked before. Did it stop working after an upgrade of Kore or Kodi? 
It could also be a hardware issue. Any other apps that don't respond on the same screen positions?

**Comment by moleculezz** [comment]
I'm afraid I don't know exactly when it stopped working. I don't use Kore often. I want to say that it happened when I upgraded to 16.0, but don't know for sure. I've had a lot of issues with 16.0. Crashing a lot. After upgrading to 16.1, everything worked much better.

You mean touchscreen issues at that screen position? No, all other apps work fine when touching the screen at that location.

**Comment by SyncedSynapse** [comment]
Check [this](http://forum.kodi.tv/showthread.php?tid=268156) thread

**Comment by moleculezz** [comment]
@SyncedSynapse That solved it. Thanks!
