### ISSUE TITLE
Activity stack all messed up

### ISSUE THREAD

**Issue by lbdroid** [xbmc/Kore#255]
Launch KORE and it goes to the "remote" activity.
Then open the drawer and select another activity, such as "Movies".
Then hit the remote BUTTON from the action menu.
Then hit BACK. It goes to movies.
Then hit BACK again. It goes to remote.

In this manner, it is possible to create an activity stack with any number of any activity in it, duplicated many times. This is very very ugly behavior.

The "remote" activity should *always* be at the bottom of the stack. Switching to remote (by any means) should clear the stack all the way down to it. Switching between non-root activities should clear the stack to the bottom and then add a new one above it.

BACK button should drop to remote activity if you aren't already there, or exit if you are in the remote activity.

**Comment by poisdeux** [comment]
Nope. When I'm using Kore I often switch from the remote, back to the list I was currently using. I find it very intuitive to use the back button for that. In your solution I would close Kore, when hitting back at the "remote" activity. This would be very very frustrating...

**Comment by SyncedSynapse** [comment]
What @poisdeux said. Going back from the remote to where you come from, to maybe select another item, is a common pattern and the activity stack is designed to support it.

**Comment by lbdroid** [comment]
It is completely counterintuitive crap.

**Comment by MartijnKaijser** [comment]
@lbdroid same as you response which is utter crap

**Comment by lbdroid** [comment]
Tell me how useful you think it is if you have an activity stack that is 1000 activities deep? Time to pull your heads out of your asses.

**Comment by kokarn** [comment]
Just wanted to say that i'd expect the exact behaviour that Kore is doing today. It's also the way Yatse does among many many other apps. That's a bit of a harsh attitude for no apparent reason dude.
