### ISSUE TITLE
ActionBar/Toolbar irregularity on Android 4.4.4

### ISSUE THREAD

**Issue by hex007** [xbmc/Kore#264]
As you can see in the first screen-shot the toolbar icons are dropped (Android 4.4.4). The second screen-shot is from Android 6.0.1 

![media-20160705](https://cloud.githubusercontent.com/assets/1689246/16572035/03ed1b9c-4219-11e6-8654-b2f537a3a6df.png)

![media-20160705](https://cloud.githubusercontent.com/assets/1689246/16572093/89caf6e4-4219-11e6-9f07-8b51a35fc3af.png)

**Comment by SyncedSynapse** [comment]
Can't see the issue.

**Comment by hex007** [comment]
If you see overflow and power icon on the first image, they are not centered vertically. It is a small ui issue but issue none the less.

**Comment by hex007** [comment]
If you see nav drawer, overflow, and power menu item icons in the first image, they are not centered vertically. It is a small ui issue but issue none the less.

**Comment by SyncedSynapse** [comment]
You'll have to complaint to Google, as it is using the standard Android Toolbar, and there's no control over alignment.

**Comment by hex007** [comment]
I have fixed this issue. Can you open it so i can submit a PR

**Comment by SyncedSynapse** [comment]
You can submit a PR either way, but i'll reopen this.
