### ISSUE TITLE
[Feature Request] Add Kodi Favorites

### ISSUE THREAD

**Issue by wstephen** [xbmc/Kore#269]
The movies, tvshows, musics shortcuts on the Navigation Drawer are so great.  But, the Kodi's Favorite Button (the Star Button) is so difficult to be reached by Kore Remote.  

Understand that reasons for features such as TV Channel Switching, recording are strong and valid, developers may be hammering how to make a good room in the tiny screens of our mobile.  However, I strongly suggest the team should consider making Kodi Favourite Shortcut available on the  Navigation Drawer just like what they've done to movies and tvshows.

Kodi Favorites can store TV Channels with logos, and it can store a myriads of Kodi addons and programs.  It allows renaming too.  How can Kore not availing this feature in its remote function?

Please, please consider!  Imagine the degree of convenience and how pleasant it will look.

**Comment by SyncedSynapse** [comment]
#81

**Comment by fabiodev** [comment]
Not wanting to be annoying i support this idea, why was it closed? doubled?

**Comment by SyncedSynapse** [comment]
Yes, same as #81
