### ISSUE TITLE
support https urls

### ISSUE THREAD

**Issue by spanktastic2120** [xbmc/Kore#274]
When clicking an http link to youtube kore is listed as one of the apps to open the link with, but not when its an https link. I'm guessing it has to do with the intent filter in AndroidManifest.xml specifying "http" but not "https".

Would the fix be as simple as a copy/paste in the intent filter section changing

`android:scheme="http"`

to

`android:scheme="https"`

?

**Comment by SyncedSynapse** [comment]
Maybe. Can you try it?

**Comment by spanktastic2120** [comment]
If someone makes the change and compiles the apk, sure. I've never developed for android, i just did some googling to come up with what i did.

**Comment by SyncedSynapse** [comment]
done in #292
