### ISSUE TITLE
Kodi v17 changed name of the player overlay showing codecs and such info 

### ISSUE THREAD

**Issue by MartijnKaijser** [xbmc/Kore#285]
For v17 a different window should be triggered for showing the codec/video info which is under longpress  button

**Comment by SyncedSynapse** [comment]
b7ece61951590b6adbd0bcad04a8f61df6574566 and 18811371a7df8f9942d15d6a9c4bf94cada45bde should fix this.

**Comment by MartijnKaijser** [comment]
Works. Thx
