### ISSUE TITLE
Support HTTPS Kodi jsonrpc endpoint

### ISSUE THREAD

**Issue by aneeshusa** [xbmc/Kore#296]
I run my Kodi webserver behind a reverse proxy which provides HTTPS along with some other features. However, currently it seems the [http protocol is hardcoded](https://github.com/xbmc/Kore/blob/dadabd09c52a9700a108091d5d80c7dc6247011e/app/src/main/java/org/xbmc/kore/host/HostInfo.java#L233) in Kore, so I am unable to connect. Would it be possible to support HTTPS endpoints  if the user enters an HTTPS Address (e.g. `https://example.com`) on the manual configuration wizard?

**Comment by poisdeux** [comment]
If I understand correctly, your reverse proxy encapsulates the HTTP from Kodi into HTTPS?

To support this, we could add a dropdown menu at the leftside of the address field. Although, I'm not a fan of adding too many bells and whistles to the UI and prefer to keep it simple.

Can't you simply add a passthrough rule to your reverse proxy to allow traffic to your Kodi webserver over HTTP?

**Comment by aneeshusa** [comment]
Thanks for the quick response. My proxy accepts HTTP requests on port 80, which are permanently redirected to HTTPS requests on port 443, which is then internally proxied to Kodi on port 8080. The point of the HTTPS proxy is to secure my Kodi installation by encrypting the Basic Authentication header, which would otherwise be in plain text, so I would rather not simply passthrough the traffic.

The Kore client sees the redirect but it doesn't work:
- If my proxy serves a 301 redirect (standard), the retried request is done as a GET instead of POST, and the request body is empty. This is accepted client behavior for 301, but has incorrect semantics for the JSONRPC interface (no request body -> no response body).
- If my proxy serves a 308 redirect (which explicitly avoids the POST -> GET problem), then the okhttp library sees the redirect but does not follow it automatically (acceptable per RFC), and then `HostConnection` does not know about `308` and defaults to handling it as an error.

Instead of a new dropdown, I think it would be easier to add this feature like so:
- If the Address field starts with "https://" or "http://", then strip it off and use the respective protocol.
- Otherwise, keep the existing behavior.

The first time I tried Kore I tried to put the full "https://example.com" into the Address field, so this is also a general usability win IMO. If this sounds like a reasonable addition I am willing to work on a PR for this.

**Comment by SyncedSynapse** [comment]
My 2 cents. This is an extreme case, and it doesn't justify changing the UI for it.

If changing the 2 `get` functions to check if the address field has http/s and return it as is (without appending `http`) solves the issue, i would do it.

**Comment by poisdeux** [comment]
Ah, so it will be a hidden feature. Nothing wrong with that I guess.
@aneeshusa it would be great if you could implement this. 
I think your suggestion looks good. However, I don't think you need to strip off the "https://" or "http://".

**Comment by SyncedSynapse** [comment]
It's not really a hidden feature, it's changing/correcting the current behaviour: if the user specifies a protocol, use it, otherwise complete the address by using http (which is the only one supported by Kodi's webserver afaik).
I'm not sure if it will work, or if something else has to be changed in okhttp's usage, but it's worth a try.
