### ISSUE TITLE
Completed/updated Dutch translation

### ISSUE THREAD

**Issue by henkhend** [xbmc/Kore#297]
Finished Dutch translation on Crowdin and updated existing translated strings to make them consistent in terms of grammatical tense, syntax and terminology.

**Comment by poisdeux** [comment]
That's nice, but where can we find these updates?

**Comment by poisdeux** [comment]
Nevermind, found it...

**Comment by SyncedSynapse** [comment]
@poisdeux It's still active yes, though i don't actively look into it...

I'll fetch this translation and incorporate it.

**Comment by SyncedSynapse** [comment]
@poisdeux by the way, i've made you manager of the crowdin project.

We really need to change to transifex to keep it coherent with Kodi...
