### ISSUE TITLE
Media control while screen locked

### ISSUE THREAD

**Issue by Peque** [xbmc/Kore#298]
This is related to #235 and #157.

Apart from being able to control the volume with the volume keys while the screen is locked, it would be great to have an interface for play/pause/next, as many music players have, accessible when the screen is locked. The [open-source Timber music player for Android](https://github.com/naman14/Timber) implements this (in case it is useful as a reference for the implementation).

![screenshot_20161015-164453](https://cloud.githubusercontent.com/assets/526577/19410900/46b23dca-92f7-11e6-8654-c958681a0d85.jpeg)

- Volume control is already justified in #235 and #157.
- Play/pause is useful also when an interruption occurs (i.e.: while watching a movie). So that you can pause quickly without needing to unlock your phone in the first place.
- Next/prior may be useful as well when using Kodi as a music player. This way, again, the user can play the next song quickly without having to unlock first.

Thanks for your work and for this great application! :blush:

**Comment by SyncedSynapse** [comment]
Go into settings and enable the Show notification option

**Comment by Peque** [comment]
@SyncedSynapse Thank you! (facepalm) :sweat_smile:
