### ISSUE TITLE
[Feature Request] Visual volume indicator

### ISSUE THREAD

**Issue by 2Zero** [xbmc/Kore#30]
As a user, it would be useful for me to have a visual indicator in Kore of the volume level in Kodi on volume change.

Use case, I often play / queue music using Kore as a control whilst I have the Kodi screen off (sometimes from the next room). An indicator of Kodi volume in Kore would act as visual feedback that changing the volume (via icon or hardware keys) was having an effect.

Personal preference, a slider overlay of some kind which is only displayed for a few seconds on volume change but which could also be directly manipulated by touch.

**Comment by poisdeux** [comment]
Implemented in version 2.2.0.
https://github.com/xbmc/Kore/releases/tag/v2.2.0
