### ISSUE TITLE
Syncing all TV shows takes a long time

### ISSUE THREAD

**Issue by moleculezz** [xbmc/Kore#303]
Hi,

When I compared refreshing/syncing the TV shows list in Kore with the Official Kodi Remote on iOS, it was a huge difference.
On iOS syncing takes a second compared to Kore which can take up to a minute to sync.

What could be the cause of this?

**Comment by SyncedSynapse** [comment]
Kore stores the TV Shows on a local database, so it gets all the information. AFAIK the iOS remote doesn't store them locally, so it's just a call to Kodi to list the TV Shows.

**Comment by moleculezz** [comment]
I still think this is a performance issue though. User experience is definitely affected by this.
Perhaps a different local DB might be faster?
http://greenrobot.org/news/mobile-databases-sqlite-alternatives-and-nosql-for-android-and-ios/
