### ISSUE TITLE
Control on login screen

### ISSUE THREAD

**Issue by gazhay** [xbmc/Kore#311]
Further to issue #63.

Kore app works to move selection up,down,left,right but the select button does nothing.

As json is not uo by this point event server must be responding. The kore app shows "connecting" but as above, using in app d-pad does work.

Is there an issue with the "select" centre button sending "return" or "enter" instead of select?
I think this would enable kore remote to be fully functional on the profile screen.

**Comment by SyncedSynapse** [comment]
Yes, 9ad1fe88796f478be29460f91f48a971cd6803e1 allowed that.

Regarding the select button, it can be "made to work", though i'm not sure if there will be side effects. I'll change it and keep an eye on any complaints.

**Comment by SyncedSynapse** [comment]
361a854e1f297a088085099d7c78accd2aac9855 should fix this.

I'm going to close this for now. If this doesn't work for you, please comment here.

**Comment by gazhay** [comment]
Sorry, just got time to update my gradle and build the apk.

Works well. App still says "connecting" but you can navigate and crucially select a profile to complete login.

Thanks

**Comment by gazhay** [comment]
This has regressed in recent releases and now  no-longer works at all on the login screen.

**Comment by SyncedSynapse** [comment]
Nothing changed over this part. Maybe something changed on your network/configuration. In Kore, check your media center's settings and make sure that "Use Event Server" is enabled and stays that way.
