### ISSUE TITLE
Connecting using hostname sometimes doesn't work

### ISSUE THREAD

**Issue by dogtopus** [xbmc/Kore#316]
mDNS is properly configured on the media center and it works on other devices in the same network (lookup hostname.local returns the proper ip address of the media center), also Kore is able to discover the box in Add Media Center wizard despite that it cannot connect to the box using hostname.
Restarting (including force stop the app and restart) Kore doesn't help.

**Comment by alfredopironti** [comment]
I also noticed link local addresses (e.g. hostname.local) are not recognized in the configuration option. How complex would it be to add support for hostnames in addition to IP addresses?

**Comment by anthonyryan1** [comment]
Android does not include an mDNS resolver at the DNS level like iOS and various desktop systems. It's necessary to implement it within each application using Androids "Network Service Discovery" system.

There are a few examples of it here: https://developer.android.com/training/connect-devices-wirelessly/nsd.html
