### ISSUE TITLE
Feature Request: Send (nearly) every URL to Kodi and play with youtube-dl

### ISSUE THREAD

**Issue by Tratoschek** [xbmc/Kore#318]
First, thank you for the great app.

I've seen, that Kore registers as a player for Youtube-videos and allow sending the URL to Kodi. As far as i know, this feature uses the [Youtube addon](https://github.com/Kolifanes/plugin.video.youtube) I think, it would be really cool, if it also registers for every Internet-URL namely for other video-sites or internet-radio-apps.

I'm not in the technical details, but I think playing in Kodi might be possible then with the already existing [Youtube-DL addon](https://github.com/ruuk/script.module.youtube.dl) from ruuk.

**Comment by SyncedSynapse** [comment]
Kore will only register specific URIs that it knows Kodi will handle. It will never register itself to handle generic URLs (most of which it won't be able to handle), as that isn't being a good Android citizen.

**Comment by Tratoschek** [comment]
I think, the benefit of playing a lot of multimedia URLs is higher than the confusion, if some URLs aren't played.

Is it possible, to automate the recognition of URLs?
youtube-dl can print a [list](https://rg3.github.io/youtube-dl/supportedsites.html) of supported sites and the url-regexes can be extracted fairly simple out of the youtube-dl source (`grep -R '^\W*_VALID_URL' youtube_dl/extractor`)

Another point: What is with urls for playlists/mediastreaming? Kodi can play them directly (as far as I know). There are bugs in other apps for this (e.g. [this](https://github.com/segler-alex/RadioDroid/issues/106)). I've seen, that VLC for Android [registers itself](https://code.videolan.org/videolan/vlc-android/blob/master/vlc-android/AndroidManifest.xml) for this kind of URLs.

**Comment by SyncedSynapse** [comment]
That's different. Registering those specific URLs would be ok, but the initial post seemed to be referring to generic URLs (i might have understood it wrongly).

**Comment by Tratoschek** [comment]
I'm not an Android developer, so maybe I'm mixing things. Let's say we have three types of URLs:
1. Multimedia URLs: Server delivers multimedia data like a stream, a playlist etc. Kodi can play them directly.
2. Website URL with multimedia content: URLs, that Youtube-DL (and because of that also Kodi) can decode to a multimedia URL and then play.
3. Website URL without multimedia content.

Does Android call the URL before sharing it? Because the URL itself gives no hint, what type it is.
If so, I get your statement as: URL type 1 is possible, but type 2 not, because it is not possible to differentiate between type 2 and type 3. If not, I'm not understanding your statement.

Sharing type 1 would be great, but type 2 as well. Is it possible to filter all URLs? Kore seems to recognize Youtube, too. Or do you think, it could be a solution to provide an information message to the user the first time he uses sharing: "You use sharing for the first time. Kore sends all URLs to Kodi. A lot of known multimedia sites can be played this way, but this won't work for any URL."

**Comment by trig-triendlg** [comment]
i would love to send an link to kodi addon orf tvthek via kore..!

**Comment by SyncedSynapse** [comment]
Guess #777 does this, so closing it for now.
