### ISSUE TITLE
[Feature Request] playlist : add currently playing item indicator + jump to currently playing item

### ISSUE THREAD

**Issue by axelsimon** [xbmc/Kore#34]
Hi,
First of all, thanks for this great new Kodi remote :)

Could you consider adding a currently playing indicator on the currently playing item in the playlist (right of the remote). Right now, I can see anything (on 1.1.0) to tell me what is the item being played, so I have to swipe backwards and forwards between the remote and the playlist.
I guess a simple change in background colour or a halo effect would be nice. I simple “play” symbol might not be enough though.

Also, I was half-expecting the playlist to be already jumped to the currently playing song, rather than just show the first items of the list, when one is halfway through the list, for instance.
Maybe that could be an option, as it's possible not everyone wants to jump to currently playing song/item.

Thanks!

**Comment by SyncedSynapse** [comment]
Yeah, this should have been done (and in fact it was highlighting the current item at some point in time). I'll take another look at it.

**Comment by axelsimon** [comment]
I just saw that the indicator in Chorus, Kodi's new web interface, is pretty neat. It's a faux-soundwave analyser, with three little bars moving up and down. Could be an option.

**Comment by SyncedSynapse** [comment]
Indicator is done on the playlist.
