### ISSUE TITLE
[Feature Request] Local Playback

### ISSUE THREAD

**Issue by primaeval** [xbmc/Kore#351]
Hi. I have added local playback for Movies and TV Episodes in my local branch.
https://github.com/primaeval/Kore/tree/local

Is this something you would like to add in or has it been discussed already?

It simply hands off a video/* intent  to Android Media Players with the resolved download url.

**Comment by poisdeux** [comment]
Please see #301

**Comment by primaeval** [comment]
Snap. :) Thanks.

**Comment by poisdeux** [comment]
But.... as you can see it hasn't been updated in a while. Soooo, if you have time and ideas you are more then welcome to help :). (We could setup a separate branch to allow multiple devs to work concurrently.)

**Comment by primaeval** [comment]
Thanks. That would be good. I tried to keep this version simple. I think merging it with dowloads might overly complicate it.

**Comment by poisdeux** [comment]
Regarding my remark about setting up a separate branch, I was wrong. AFAICT GitHub doesn't allow specific access to branches.
Btw, I'm closing this as this should be in a PR not an issue.

**Comment by primaeval** [comment]
OK. How do we get this moving? Do you want to merge in the other implementation or look at a PR from me. I would just like to see this functionality in the Play Store as soon as possible.
