### ISSUE TITLE
Image loading is in the UI thread

### ISSUE THREAD

**Issue by struggggle** [xbmc/Kore#356]
Dear developers,

For image loading, Google says this:
https://developer.android.com/topic/performance/graphics/index.html
" Loading bitmaps on the UI thread can degrade your app's performance, causing slow responsiveness or even ANR messages."

I noticed that in the following code, image loading is in the UI thread: 
https://github.com/xbmc/Kore/blob/master/app/src/main/java/org/xbmc/kore/ui/sections/remote/RemoteFragment.java#L271 
org.xbmc.kore.ui.RemoteFragment.java  --->adjustRemoteButtons()   (line number: 271)
(bitmap is loaded with the invocation of decodeResource ())
the image resource is : https://github.com/xbmc/Kore/blob/master/app/src/main/res/drawable-xxhdpi/remote_background_square_black_alpha.png

adjustRemoteButtons() is called by: org.xbmc.kore.ui.RemoteFragment.java    onCreateView()
which means image loading is in the UI thread.

Do you think perform image loading in the UI thread will affect Kore's performance? If so, perhaps moving the images loading to a work thread can help make app more smooth in user interaction.
Looking forward to your response.

Thanks.

**Comment by poisdeux** [comment]
I haven't tested Kore on every possible device, but even on the virtual devices (which are terribly slow compared to real devices) I don't notice an unacceptable delay when inflating the remote. So, I'm not sure if this really is an issue, although the background image is fairly large.

Do you experience a noticeable delay when Android inflates the remote UI?

**Comment by SyncedSynapse** [comment]
And that code is applicable to Jelly bean only. That's about 30% of the market nowadays, but it tends to get down.

**Comment by CanNuhlar** [comment]
This use to be a big issue back in time but not that deadly nowadays. Still not a very good practice though.

**Comment by vastril4o** [comment]
this api can speed up process - http://square.github.io/picasso/

**Comment by SyncedSynapse** [comment]
Closing this, as it isn't really worth it.
