### ISSUE TITLE
Share links to Kore

### ISSUE THREAD

**Issue by ways** [xbmc/Kore#37]
I'd like to be able to share a link, I.e. from YouTube, and have Kore pass it on to kodi.

**Comment by axelsimon** [comment]
This is/was a wonderful function in the old original XBMC Remote. Maybe some of the code can be pulled from there or studied to reduce the work needed to get this done :)

A cool thing would also be to able to send any local media using DLNA UPnP, the way some phones come with a built-in function to "throw" media to compatible receivers.

**Comment by SyncedSynapse** [comment]
Done for Youtube. Will be in the next release.
