### ISSUE TITLE
[Feature Request] Dedicated subtitle button

### ISSUE THREAD

**Issue by madmax2** [xbmc/Kore#375]
Many remotes controls (real and software) have a dedicated subtitle button that we can use to quickly turn on/off the subtitle as well as select the language.

This is useful because some sections of a movie, we want to just check what they said then turn subtitles off again.

Right now the implementation is not very user friendly
requiring going through a hidden drop down menu then choose subtitle then we can choose  the subtitle language or turn on/off subtitle.

This is extremely cumbersome.

1. We need a dedicated subtitle button always showing.
2. It would also be good if we can hide the other unused buttons as well e.g. Play single, play all button,
3. Ideally we should be able to choose what buttons we want to show/hide e.g. subtitle, audio etc..

**Comment by bendem** [comment]
I would like to bump this and also ask that a menu is added to get to the parent subtitle menu which lets you select **local** subtitles (as well as download, sync and disable them). Currently you have to bring up the player's OSD to get to that menu and bringing up that OSD is sometimes very hard (sometimes the middle button does nothing and I have to switch to the TV remote to bring it up).

**Comment by madmax2** [comment]
@bendem Check here
https://github.com/xbmc/Kore/pull/427

Someone implemented it, but one of the main coder of this app decided now to merge the pull request.

Pretty disappointing outcome.
I suggest you post in that thread and reply to that coder to let them know your opinion.

**Comment by madmax2** [comment]
@n123al 
Unfortunately the main coder has decided to not merge your code.

Can you add code that allows us to put any button on the main UI, so we can assign it to any function we want?

Can you fork this to your own kore project with the code you made.

Disappointing to see your code not get the merge request approved.
