### ISSUE TITLE
Layout

### ISSUE THREAD

**Issue by SamBozman** [xbmc/Kore#378]
Sir: Thank you for the great work on Kore. It works well and I just have one simple request concerning the layout. In each corner of the main direction control there are 4 auxiliary icons. The problem is when controlling Kodi with the directional arrows it is easy to accidentally press one of these 4 auxiliary icons because they are so close to the main directional arrows. There seems to be a lot of screen real-estate and I thought it would be nice if these auxiliary icons could be moved outwards towards the edges of the screen to prevent accidental control problems. 
Please see the picture below to see my proposal changes.

Thanks for your consideration.

Sam
![kore2](https://cloud.githubusercontent.com/assets/15849536/24843767/b501e36e-1d5a-11e7-9db6-5acd07fb2354.png)

**Comment by poisdeux** [comment]
How about putting those 4 buttons above the remote?
![screenshot_1493801042](https://cloud.githubusercontent.com/assets/4527626/25653532/7e004ce8-2fed-11e7-964f-8bf012423faf.png)

**Comment by SyncedSynapse** [comment]
No please no. Furthermore, vertical space is at a premium there. When something is playing those buttons would overlap the info.

**Comment by poisdeux** [comment]
Well, the overlap is still a problem on some devices. It just isn't feasible to fix this permanently, the way the remote is setup right now. Below a screenshot on a ldpi device (but who uses that right...).

![screenshot_1493815751](https://cloud.githubusercontent.com/assets/4527626/25661219/01607d48-3010-11e7-8309-6ddfc43fb486.png)

I would actually favour removing the "now playing info" part on the remote screen as the user can get the info with a simple swipe right. Another reason I don't think the "now playing info" is really useful at the remote screen is that I use the remote only when I need to manage Kodi and don't want to attach a keyboard. At that point I can watch Kodi to see what is playing.

So, if we just remove the "now playing info" we can solve both the size and overlap issues.

**Comment by SyncedSynapse** [comment]
I don't particularly care about the overlap on ldpi, but it could make the issue worse on higher densities.

Regarding removing the now playing info, i'm strongly against it. It's a matter of usage, but i personally use it a lot - i usually just use that remote screen, and seldom go into the "now playing" screen, so having that info and the play/pause buttons is a major bonus IMO.

Regarding the original issue, i understand the pain of the OP, but neither moving the buttons to the corners, nor to the top would be an improvement to the overall experience IMO (it would solve this particularly issue, but i don't think it would be and overall improvement). Sorry it's just my opinion, and while i understand the issue, i don't think it merits changing the button layout for it.
