### ISSUE TITLE
Subtitle not re-enebled after setting to "none" and choosing one again

### ISSUE THREAD

**Issue by MartijnKaijser** [xbmc/Kore#38]
If you set the subtitles to "none" or the setting was already off and choosing a subtitle again it doesn't (re-)enable the subtitle.
This is using the three dots in now playing screen.

**Comment by SyncedSynapse** [comment]
Fixed in 776f6b60e6a5877e79b4aae718c478c277084337 (introduced in 337ac9450a2fa177d66ec47882fb9dbd36b69cef)

This is serious enough to deserve a release. Without this, subtitle selection is broken.

**Comment by MartijnKaijser** [comment]
fixed indeed
