### ISSUE TITLE
[build error] /AddHostFragmentZeroconf.java:134: Error: The WIFI_SERVICE must be looked up on the Application context or memory will leak on devices < Android N.

### ISSUE THREAD

**Issue by Wikinaut** [xbmc/Kore#380]
When building a signed apk:

https://github.com/xbmc/Kore/blob/master/app/src/main/java/org/xbmc/kore/ui/sections/hosts/AddHostFragmentZeroconf.java#L134

gives build error

/work/usr/local/src/Kore/app/src/main/java/org/xbmc/kore/ui/sections/hosts/AddHostFragmentZeroconf.java:134: Error: The WIFI_SERVICE must be looked up on the Application context or memory will leak on devices < Android N. Try changing getActivity() to getActivity().getApplicationContext()  [WifiManagerLeak]
                WifiManager wifiManager = (WifiManager)getActivity().getSystemService(Context.WIFI_SERVICE);
                                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

   Explanation for issues of type "WifiManagerLeak":
   On versions prior to Android N (24), initializing the WifiManager via
   Context#getSystemService can cause a memory leak if the context is not the
   application context. Change context.getSystemService(...) to
   context.getApplicationContext().getSystemService(...).

1 errors, 0 warnings

**Comment by poisdeux** [comment]
Closing as it has been fixed on master.
