### ISSUE TITLE
Remote buttons too small

### ISSUE THREAD

**Issue by shiba89** [xbmc/Kore#383]
Hi, since version 2.2.0 the remote buttons turned from this:
![screenshot_2017-05-01-18-06-28](https://cloud.githubusercontent.com/assets/3816409/25585078/33f1246a-2e99-11e7-97a2-28a43f73fff9.png)
to this:
![screenshot_2017-05-01-18-02-41](https://cloud.githubusercontent.com/assets/3816409/25585086/379d3e6e-2e99-11e7-8c05-78bf6c230bd1.png)

I think it started with https://github.com/xbmc/Kore/issues/299. That guy and I share a similar screen resolution, but with my 54 more vertical pixel I never had overlapping problems. Can this be somehow fine-tuned? Right now I'm on 2.1.0 because I never get the correct button with the small version.

**Comment by poisdeux** [comment]
I believe the way it is now is as it was originally designed. I wouldn't mind increasing the remote size. However, I'm afraid everyone else who was always using the correct size will start complaining...

**Comment by SyncedSynapse** [comment]
It's also my opinion that the PR that changed this changed it for the better, and it should be kept. It is also worth pointing out that, even at the smaller resolutions, the remote buttons are bigger (52dp) than what Google recomends as the minimum (48dp).

Nevertheless, maybe they can be tweaked somewhat in smaller resolutions. Currently they are 52dp, we could try adding 4-8 dp.

**Comment by shiba89** [comment]
I made a side by side comparison:
![comparison](https://cloud.githubusercontent.com/assets/3816409/25662264/31b28492-3014-11e7-8060-23a052e59d74.png)
To me it seems that 2.1.0 is way more similar to the Google Play screenshot.

I also made a comparison of the remote with my thumb on the screen (I only have my old netbook webcam...):
![comparison2](https://cloud.githubusercontent.com/assets/3816409/25662822/343d942a-3016-11e7-8def-d15347459eac.png)
As you can see, with 2.2.0 my thumb almost covers all the remote buttons.

I'm not saying this should be reverted, because button overlapping is in fact a problem. Maybe vertically center the buttons could be enough? Oh well, I made another comparison :)
![comparison3](https://cloud.githubusercontent.com/assets/3816409/25663453/06f27376-3018-11e7-8730-325b6358a70a.png)

**Comment by SyncedSynapse** [comment]
I think that vertically centering the buttons would be worse, as it would make the buttons further away from the natural position of the thumb.

What device are you using and what dp does it have?

**Comment by shiba89** [comment]
I have no idea what dp is, but resolution is 480x854, size 4.5". The phone is an ASUS Zenfone 4, A450CG. More info here: http://www.gsmarena.com/asus_zenfone_4_a450cg-6428.php

**Comment by SyncedSynapse** [comment]
@poisdeux This looks like it's falling on the sw320dp bucket. Do you think we can increase the 58 dp (and maybe increase the 360dp to the same as 400dp)?

I'm only testing on 400dp and it looks good. Did you test it on other devices?

**Comment by shiba89** [comment]
I'm sorry, I understand I explained myself poorly. I know nothing about Android development and I have no idea what "dp" stands for.

Unfortunately I have no other smartphone, could Genymotion be of any help?

**Comment by poisdeux** [comment]
I tested on other devices using virtual machines. 
Below a screenshot on a device resembling the Samsung Galaxy S2 plus ![screenshot_1493885712](https://cloud.githubusercontent.com/assets/4527626/25695851/0392e614-30b5-11e7-8fc0-0e99e1085be7.png)

And here a screenshot on a device resembling the ASUS Zenfone 4
![screenshot_1493885713](https://cloud.githubusercontent.com/assets/4527626/25695853/052b80f8-30b5-11e7-8420-d774ab1a5c3a.png)

Now for the buckets they fall into:

ASUS Zenfone 4: `sqrt(480^2 + 854^2)/4.5 = 217 dpi`  ==>  `scale factor = 217/160 = 1.35` ==> `sw = 480/1.35 = 355`  matching on our sw360 dimensions.

Samsung G2 plus: `sqrt(480^2 + 800^2)/4.3 = 217 dpi`  ==>  `scale factor = 217/160 = 1.35` ==> `sw = 480/1.35 = 355`

So they both fall into the sw360 definition and both are sized the same as you can see from the screenshots. 

Unfortunately, as can be seen from the Galaxy S2 screenshot there isn't much room to increase the remote size. I think the only way we can solve this is by refactoring the remote code and make it responsive. I haven't thought this through, but making the background use a nine-patch image we should be able to scale it depending on the available width and height.

**Comment by shiba89** [comment]
@poisdeux beware that ASUS phones don't use on-screen navigation bar as you can see in my screenshots, so there is much more room.

**Comment by poisdeux** [comment]
@shiba89 Yup, I see. On your phone there is MUCH more room. We need to redesign the remote to be able to dynamically use as much space as available. It is now sized statically based on a few definitions that depend on the smallest width of the device. In your case the smallest width is 480 and that matches on Kore's smallest width definition for 360 (matched on actual pixel size).

**Comment by SyncedSynapse** [comment]
Looking at the screenshot i suspect there's something else going on...

@shiba89 Which Asus zenfone 4 do you have? You linked one with a 4.5" screen and 480x854 resolution, but there's this one:
https://www.asus.com/Phone/ZenFone-A400CG/specifications/
which has a 4" screen and 480x800 resolution.

@poisdeux This last one as a dpi of 233 and dp 330 which probably falls in the sw320 definition. Looking at the initial screenshots that shiba posted it's more consistent with this hypotheses.

**Comment by shiba89** [comment]
@SyncedSynapse A450CG, 4.5". I chose it over A400CG because IPS vs TFT screen, so I'm perfectly sure of the model.

**Comment by poisdeux** [comment]
I implemented a scalable control pad (remote buttons) in PR #428. Hopefully this will work for everyone.

Below a screenshot from a Android Virtual Device resembling a Samsung Galaxy S2.
![samsung_s2](https://user-images.githubusercontent.com/4527626/28891371-8083bc96-77ca-11e7-86eb-d3b2fb8d5a2c.png)

And a screenshot from a AVD resembling an Asus Zenfone 4.
![asus_zen](https://user-images.githubusercontent.com/4527626/28891407-a271106a-77ca-11e7-8f97-f8f45d956f42.png)

**Comment by poisdeux** [comment]
Update: we tried to release a fix for this in 2.3.0 but unfortunately that didn't work out very well.
See #444 Hopefully we get it right the next time.

**Comment by kabamaru** [comment]
Hi, I have a Samsung Galaxy Core Prime (480x800 res) and the update caused me the same issue. Is there a safe place I can get an apk for 2.1.0? I use this app everyday and I really hate the tiny buttons. Thanks!

**Comment by poisdeux** [comment]
#477 should fix the issue and will be included in the next release.
The fix is already available in the nightly build http://mirrors.kodi.tv/tools/kore/nightlies/

**Comment by kabamaru** [comment]
Thanks for the link! The new build does fix the size issue, but ultimately I opted for 2.1.0 because it has a more centered control pad. The new one is too close to the shortcuts below, at least on my phone.

**Comment by poisdeux** [comment]
Could you upload a screenshot? We could add some extra margin to make it more useable.

**Comment by kabamaru** [comment]
![screenshot_2017-11-25-23-12-43](https://user-images.githubusercontent.com/1534720/33234894-806dbbb4-d236-11e7-86d3-3e14a4d29e0f.png)

**Comment by poisdeux** [comment]
Closing this as the 2.3.3 release should have fixed this. Please reopen if the issue persists.
