### ISSUE TITLE
Kore app plays wrong songs

### ISSUE THREAD

**Issue by ghferrari** [xbmc/Kore#399]
Hi,
I'm using Kore on android but it's largely unusuable for me because it consistently plays the wrong song. i.e. if I select one song to play (Song A), then Kore never plays that song. Instead it plays some other song (Song B), which is completely unrelated to the song I want.

Any suggestions for what's going on and how to resolve?

Thanks,

Geoff

**Comment by ghferrari** [comment]
On further investigation, the behaviour is even worse. I don't just get the a different song to the one I selected - a get a new different song each time! i.e. If I try to play Song A, then I get Song B; then when I repeat my attempt to play song A, I get song C...

**Comment by poisdeux** [comment]
See #362
