### ISSUE TITLE
[Feature Request] Watched status on movie and TV list

### ISSUE THREAD

**Issue by dale2507** [xbmc/Kore#400]
The movie list doesn't indicate if a movie is watched or not until you open the plot screen. It would be good if it were possible to see at a glance which movies are watched or not. Perhaps an overlay on the poster? It would be good to have the same thing on the tv show and episode list to make it more obvious.

**Comment by tomerf** [comment]
You can hide watched movies and TV shows in the menu.
But I like the idea of having an indicator in the list view.

**Comment by SyncedSynapse** [comment]
In the next version
