### ISSUE TITLE
[Feature request] Stream local files to Kodi

### ISSUE THREAD

**Issue by mase76** [xbmc/Kore#413]
Hi!
It would be cool to stream local files to Kodi, maybe via UPnP. Either a fileopen dialog in Kore, a player intent, or both.

**Comment by hex007** [comment]
I agree this would be an excellent feature.

**Comment by retro-78** [comment]
Hi 
This is not implemented in the main app but you have this fork #301.

**Comment by poisdeux** [comment]
Hopefully the next release will contain this feature for movies and TV shows. See #504

**Comment by raydac** [comment]
for local file streaming you can use https://github.com/raydac/kodi-videoserver-app
