### ISSUE TITLE
Display remote when screen is locked on Android 7

### ISSUE THREAD

**Issue by mueller-ma** [xbmc/Kore#415]
I have seen #298. However on Android 7 there is only the push notification on the lock screen

**Comment by SyncedSynapse** [comment]
That's the one.

**Comment by mueller-ma** [comment]
Is this really correct?
![kore-lockscreen 2](https://user-images.githubusercontent.com/22525368/27874453-d164beca-61af-11e7-819b-6eea197713ef.png)
![kore-lockscreen 1](https://user-images.githubusercontent.com/22525368/27874427-bc7a49da-61af-11e7-8740-f227374aa442.png)

**Comment by SyncedSynapse** [comment]
Can't understand German, so not sure about the settings screen, but the lockscreen looks ok. What's the problem?

**Comment by mueller-ma** [comment]
Now I have disabled the option "Show remote on lockscreen". It's exactly the same. Is this really intended? An option which does nothing?
![screenshot_20170705-205542](https://user-images.githubusercontent.com/22525368/27880216-84cd6642-61c4-11e7-838a-f1386c4f61ad.png)

**Comment by SyncedSynapse** [comment]
Back out of the settings screen to apply it.

**Comment by mueller-ma** [comment]
I have gone back and even restarted the app, same issue

**Comment by SyncedSynapse** [comment]
Lock the phone while the remote screen is shown and it will still be shown in the lockscreen.

**Comment by mueller-ma** [comment]
That works. Thanks
