### ISSUE TITLE
Use Android 7 notifications

### ISSUE THREAD

**Issue by mueller-ma** [xbmc/Kore#416]
The mpd client MALP uses a bundled notification for player controll.
This way you have in the small notification pause and skip and in the extended some more controll buttons.
And you have a small arrow where you can switch between the two types: https://developer.android.com/images/android-7.0/inline-type-reply.png

**Comment by SyncedSynapse** [comment]
Care to explain what you mean?
Bundled notifications don't make sense, as there is only one.
The current notification already has a collapsed and extended state with actions in them.
The screenshot you link is applicable when you want to reply to a notification, clearly not applicable here.

**Comment by mueller-ma** [comment]
Right, they are not bundled notifications, but they look different on Android 7.
Small:
![screenshot_20170705-182048](https://user-images.githubusercontent.com/22525368/27874482-f34852d6-61af-11e7-85dd-2c3b90da8bb2.png)
Large:
![screenshot_20170705-182054](https://user-images.githubusercontent.com/22525368/27874483-f34b87e4-61af-11e7-8990-a1637f46b186.png)

**Comment by SyncedSynapse** [comment]
Just expand Kore's notification to see it all.

**Comment by mueller-ma** [comment]
Possible, but it doesn't look optimized for Android 7
