### ISSUE TITLE
Ability to play a disc

### ISSUE THREAD

**Issue by madduck** [xbmc/Kore#419]
I can control playback of an audio CD through Kore just fine, but I can't actually select the CD for playing from the Kore UI, other than using the remote to navigate through the screen menus.

It'd be great if instead I could use the Kore app to start playback of a CD.

**Comment by john3voltas** [comment]
Interesting. Are you actually asking for a way to select a CD disk on a CD ROM reader? Or are you referring to select a cue/bin or an iso from a list? I can easily browse through the audio library and choose whichever title I want from Kore so I would suspect you're referring to the first.

**Comment by madduck** [comment]
When I insert a DVD, Kodi's main menu gets a new option "Play Disc".
The only way I can choose that is using Kore's remote, which can be
quite inconvenient. It'd be nice if the menu that slides in from the
left would just expose this option too.
