### ISSUE TITLE
missed features from version 2.1.0 in 2.2.0

### ISSUE THREAD

**Issue by treakiandroid** [xbmc/Kore#422]
Hi,

i have now switched back to version 2.1.0 because following i miss in 2.2.0 (fdroid versions):

The ability to skip throug videos with the arrow keys, this works in 2.1.0 but im 2.2.0 there is no reaction on the arrow keys while playing a video without any osd opened. Please bring that back.

Also the buttons to adjust the volume made it much simpler to make precise relative volume changes, i liked it more, please add a setting to have the buttons instead of the slider.

Also the filesize increased a lot.

Thanks a lot in advance

**Comment by SyncedSynapse** [comment]
The arrow keys work the same. You need to set the option "Use event server" on the media center configuration in Kore for it to work.

As for the volume buttons, you can use the hardware volume buttons to set the volume (enable that in the settings).
