### ISSUE TITLE
Define notation remotely

### ISSUE THREAD

**Issue by AlexisBRENON** [xbmc/Kore#423]
Hi,

While playing music, the left screen of Kore displays the notation (if any) of the currently playing item. However, there is no way to define it in Kore. You have to go to the playlist, show information and then define your notation.

Is there any plan to include the ability to define your notation directly from Kore.
If not, can I freely contribute to this project?

Kind regards,
Alex.

**Comment by SyncedSynapse** [comment]
You can contribute to the project.

I don';t understand what you mean by notation
