### ISSUE TITLE
Share to alternate Kodi instances

### ISSUE THREAD

**Issue by Cj-Malone** [xbmc/Kore#430]
Currently "Play on Kodi" sends it to the currently selected host, but sometimes I don't want to send it to the main one.

With Android 6.0 (23) you can provide ChooserTargets, so when you share a link each Kodi instance could be in the share menu, by selecting one that's not the current Kore could switch to it and then play the link.

[Docs](https://developer.android.com/reference/android/service/chooser/ChooserTargetService.html) + [Sample Code](https://developer.android.com/samples/DirectShare/index.html)

**Comment by SyncedSynapse** [comment]
Implemented in #572
