### ISSUE TITLE
Request: Button for switching video fullscreen/windowed

### ISSUE THREAD

**Issue by MartijnKaijser** [xbmc/Kore#44]

**Comment by SyncedSynapse** [comment]
In the menu (3 dots on top left) there's an option to toggle fullscreen, does this suit you?

There are 2 fullscreen options in jsonrpc: switch only the video window (which isn't in the remote) or the full GUI (which is). Preferably i would only have one of those in the remote, to not confuse users and to keep it simple. If the other one is more appropriate i'll change it.

As for making it a button, i'm not sure where it should go. Aesthetically i can't find a place where it should fit.

**Comment by MartijnKaijser** [comment]
Toggle video window is the one most users need. Toggle the full gui window is near pointless for the remote.

**Comment by MartijnKaijser** [comment]
Maybe a longpress on "back" or something. Not sure

**Comment by SyncedSynapse** [comment]
So, changing the current option "Toggle fullscreen" to toggle the video window instead would work for you and be the most appropriate for the majority of users? 
Ideally i'd like to have only one fullscreen option (which can be toggle video), and keep it in the menu (i don't think this is such a common operation that merits a dedicated button but that's just my usage pattern).

**Comment by rigid** [comment]
if some "Fullscreen toggle" option would be added to the preferences, the user could decide herself. The default could be "video". If one available option would be "disabled", #25 could be closed even :)

**Comment by MartijnKaijser** [comment]
You get kicked out of fullscreen video quite easy by hitting "back" and this could happen quite lot by accident. Getting back to fullscreen should be made quite easy

**Comment by SyncedSynapse** [comment]
I'm not able to test this. On my box toggling the video window to full screen does nothing...

Try 71fc96dddecba9023132a5556f0fd9a7065c9b35 to check if this what makes sense.

@rigid I don't think this merits an option in the preferences. If we make an option out of every decision, pretty soon the settings will be full and the users overwhelmed.

**Comment by rigid** [comment]
Overwhelming the user could be circumvented by putting those kind of settings behind some "advanced" or "expert settings" menu. After all, every kore user is a kodi user which has tons of preferences and uses the same practise.
Actually I would like this settings exactly for novice users who get kodi setup and don't understand that their tv is a computer and get confused by toggling fullscreen. I see that this isn't vital, but I think customizable software is a good thing when options are self-explaining.

**Comment by SyncedSynapse** [comment]
Closing this. 71fc96dddecba9023132a5556f0fd9a7065c9b35 should take care of it. If it's not what it's meant, reopen it please.
