### ISSUE TITLE
Adding a new host mutes the host

### ISSUE THREAD

**Issue by Smeulf** [xbmc/Kore#442]
Hello,

When adding a New host, Kore mutes the host, and unmutes it.

I wonder why, and if it's possible not to mute the host at all ?

It can be annoying if you add a remote while watching/listening something, and sometimes (in the past, not sure it's not fixed now) Kore does not unmutes the host.

Thanks !

**Comment by SyncedSynapse** [comment]
It's necessary to check if Event Server is working.
