### ISSUE TITLE
Gradle error

### ISSUE THREAD

**Issue by yarons** [xbmc/Kore#449]
I tried compiling with Android Studio 3.0b6, I didn't change anything, I just switched to the correct tag and accepted all the dependencies.

I got the following error message at the end:
```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> All flavors must now belong to a named flavor dimension. Learn more at https://d.android.com/r/tools/flavorDimensions-missing-error-message.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org
```

I'm not sure what thos flavorDimensions are but it's probably needed for the newest Android Studio and SDK 26.

Thanks!

**Comment by poisdeux** [comment]
Well, I think Android Studio updated the gradle plugin to version 3.0 without notifying you, or you missed the notification ;).
The link in the error message is pretty clear in my opinion. If you really want to use 3.0 than I suggest to add:

`flavorDimensions "makinggradlehappy"`

and add

`dimension "makinggradlehappy"`

to each product flavour.

**Comment by yarons** [comment]
So I must use the old version or this trick if I want to get rid of the error?
Is there a change I can do it in a branch just for the sake of compliance?

**Comment by poisdeux** [comment]
No, I'm not in favour of adding branches to the main repo. 
But if you want support for 3.0 of the Android Gradle plugin than by all means go for it. And please sent a PR when you fixed all issues.
