### ISSUE TITLE
Kore remote buttons

### ISSUE THREAD

**Issue by DavidPieters** [xbmc/Kore#454]
I don't want to sound ungrateful. Because you all do great work for which I have the upmost respect. 
The navigation buttons are too small for me and a lot of other users. (according to the comments on playstore) 
Also the sound slider isn't easily to handle it accurately.
Is it possible to create different layouts for the remote? Where you can select buttons to be bigger or smaller?

**Comment by SyncedSynapse** [comment]
#383
