### ISSUE TITLE
Media refresh fails

### ISSUE THREAD

**Issue by jmue** [xbmc/Kore#457]
With Kore v2.3.2 it ist not possible to refresh media list like movies or music via swipe down. It shows a mesage 'cant connect to mediacenter'. Remote controls are fine, also it ist possible to start playing a movie with the FAB. I'm running Kore 17.4 on Ubuntu 16.04 formerly Xbmcuntu.

**Comment by SyncedSynapse** [comment]
What about other functions (play, pause, increse volume, etc), do they work?

**Comment by jmue** [comment]
Play, pause, forward, rewind, mute work as expected. The volume slider has no effect, my audio is routed via HDMI. Is there somthing else that would help you? The previous version that was available through the Play Store did'nt have that bug.

**Comment by SyncedSynapse** [comment]
I can't replicate this, and it probably isn't a widespread issue, as this is the first report of it. Have you tried removing your media center from Kore and adding it back?

**Comment by jmue** [comment]
You are right, readding solved the problem for me.
