### ISSUE TITLE
Mute, random and repeat buttons are barely visible when using the day theme

### ISSUE THREAD

**Issue by pitsi** [xbmc/Kore#464]
![screenshot_2017-10-03-10-15-00](https://user-images.githubusercontent.com/5880037/31118965-039e684a-a838-11e7-876f-09f41ca5b1ba.png)

![screenshot_2017-10-03-10-15-23](https://user-images.githubusercontent.com/5880037/31118966-039ff386-a838-11e7-8e99-c86b680bba83.png)

As seen on the screenshots above, the mute, random and repeat buttons are barely visible on the day theme, probably because they are white on light background, instead of grey on white that the playback (stop, play etc) buttons are. Night theme has them all white on dark background, so no problem there.

Tested on android 4.3 with kore 2.3.2. I did not check how it looks on the other 2 themes.

**Comment by pitsi** [comment]
The same problem applies to the solarized theme as well, but not on the mist one (screenshots added)

![screenshot_2017-10-04-13-08-14](https://user-images.githubusercontent.com/5880037/31170635-7c84e8ba-a905-11e7-8159-1d5df94cd205.png)

![screenshot_2017-10-04-13-08-28](https://user-images.githubusercontent.com/5880037/31170647-88667a86-a905-11e7-8757-de47dcdeabdc.png)

**Comment by poisdeux** [comment]
Thanks for reporting this. This seems to be an issue for devices running pre-Lollipop version of Android.

**Comment by SyncedSynapse** [comment]
Yeah, android:tint isn't being applied. 

There's something even stranger on the screenshots posted: where is the overflow button (the three dots)? I've tested this on 4.3 and at least it shows (with the correct color).

**Comment by pitsi** [comment]
Which 3 dots do you mean? I may have disabled them in options, but there are 3 dots in the top right corner on every screenshot.

**Comment by SyncedSynapse** [comment]
Ignore my comment. The screenshot is showing a music playing so the button isn't available, only on videos. My bad.

**Comment by pitsi** [comment]
Actually is a web radio playlist on all screenshots :)

**Comment by pitsi** [comment]
The issue was resolved in yesterday's 2.3.3 release, so I am closing this.
Thank you for the support :)
