### ISSUE TITLE
Changning "Shutdown" button action on "playercontrol(stop)".

### ISSUE THREAD

**Issue by kociszz** [xbmc/Kore#465]
Hi,
As we know, Vero 4K and any Rasberry device can't be turn on WOL.
Problem is when somebody want shutdown on app, device must be reset.
So i want to disable "Shutdown" "Reboot" and "Turn Off" function or change action for "OnStop".

The problem is to find place, where is declaration of this functions in jsonrpc.
I want to catch this methods (in jsonrpc function) and change it for "OnStop" method.
Like "if method="Shutdown" change for "playercontrol(stop)".

**Comment by SyncedSynapse** [comment]
Not sure i understand, but equating shutdown with stop isn't possible on Kore.
