### ISSUE TITLE
Drop dependency on web server at setup

### ISSUE THREAD

**Issue by chrysn** [xbmc/Kore#467]
While Kore works very well with Kodi when the "Web server" / "Allow remote control via HTTP" setting is turned off (and just "Allow remot control from applications on other systems" is on), the "TEST" step in configuring a Kodi instance fails. As a result, I always need to temporarily enable the web server when I'm setting up an Android device in the local network.

Please consider disabling the check (or making it optional -- for example, if there is actual HTTP functionality used, it could show a warning like "Without the HTTP server enabled, features X and Y will not be available. Continue anyway?").

If HTTP isn't needed any more at all, the port, user name and password fields are not needed any more at all, and the documentation at http://syncedsynapse.com/kore/kore-faq needs updating.

**Comment by SyncedSynapse** [comment]
While Kore *might* work without the web server being turned on, we make no guarantee that it works. Kore assumes that the web server is turned on, and it never tries to gracefully fail if that isn't so.

It's also my opinion that HTTP shouldn't be optional as that is an integral part of providing a minimum of functionality. Without it only the remote buttons might work but, imo, that is hardly enough for the large majority of the users.

I understand your point, but you're obviously an advanced user, and you found a way to solve your issue anyway. IMO making HTTP optional would lead to confusion to most users.

**Comment by chrysn** [comment]
On Tue, Oct 10, 2017 at 10:04:43AM +0000, Synced Synapse wrote:
> While Kore *might* work without the web server being turned on, we
> make no guarantee that it works. Kore assumes that the web server is
> turned on, and it never tries to gracefully fail if that isn't so.
>
> It's also my opinion that HTTP shouldn't be optional as that is an
> integral part of providing a minimum of functionality. Without it only
> the remote buttons might work but, imo, that is hardly enough for the
> large majority of the users.

I just ran through the features I know, and kore has shown to fail
gracefully, and the only failure was that movies and series did not show
thumbnail images for items and actors.

Admittedly that's worse user experience, but far from minimum.

I don't care enough to push this if you think it's a non-issue, so feel
free to close it.

Thanks for your response
chrysn
