### ISSUE TITLE
Adaptive icons support for Android 8.0+

### ISSUE THREAD

**Issue by ChristopheVersieux** [xbmc/Kore#483]
Hello all

I am really annoyed that the only application in my launcher that doesn't support adaptive icon shape is Kore

Link: https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive.html

I hope you will implement this feature

Thanks

**Comment by SyncedSynapse** [comment]
Already done

**Comment by ChristopheVersieux** [comment]
![screenshot_20171128-103512](https://user-images.githubusercontent.com/356214/33312361-ed48e9f0-d427-11e7-93c0-782184ba8fa9.png)

Strange... But ok, if you say so... Might be a launcher issue, but that's the first time it happens

**Comment by SyncedSynapse** [comment]
It's done, but it's not on the Play Store yet. Next update will have it.

**Comment by ChristopheVersieux** [comment]
Thank a lot for the quality of the support and your answers.

Keep up the good work!
