### ISSUE TITLE
Addons crashes when opened

### ISSUE THREAD

**Issue by poisdeux** [xbmc/Kore#486]
User reported on the [forum ](https://forum.kodi.tv/showthread.php?tid=325041&pid=2675412#pid2675412) that Kore crashes when opening an addon from the Addons list.

I can find numerous reports in googleplay dashboard regarding a nosuchmethod error:

```
java.lang.NoSuchMethodError: 
  at org.xbmc.kore.ui.sections.addon.AddonsActivity.onAddonSelected (AddonsActivity.java:130)
  at org.xbmc.kore.ui.sections.addon.AddonListFragment$1.onItemClick (AddonListFragment.java:75)
```

Weird thing is that the call is about calling [setSquarePoster](https://github.com/xbmc/Kore/blob/master/app/src/main/java/org/xbmc/kore/ui/sections/addon/AddonsActivity.java#L130) which is available in [AbstractFragment](https://github.com/xbmc/Kore/blob/master/app/src/main/java/org/xbmc/kore/ui/AbstractFragment.java#L87). So everything should just work BUT the [dataHolder](https://github.com/xbmc/Kore/blob/master/app/src/main/java/org/xbmc/kore/ui/AbstractFragment.java#L25) that is passed from the `AddonListFragment` to `AddonsActivity` to start the `AddonInfroFragment` is of type `AddonInfoFragment.DataHolder` which should be just `DataHolder` as it is defined in `AbstractFragment`. However, `AbstractInfoFragment` extends `AbstractFragment` and thus the code should just work... I'm suspecting some inheritance issues here. Any ideas?

**Comment by SyncedSynapse** [comment]
No ideas for now, but the crashes are all happening on Android 4.4

**Comment by poisdeux** [comment]
Ah didn't notice that. I am unable to reproduce the issue on a virtual device running 4.4, so I'm guessing that this might be a vendor problem that don't support the device anymore.
PR #487 fixes the code for the weird inheritance, hopefully this also fixes the reported issue.
