### ISSUE TITLE
Enhancement: LAN autoscan

### ISSUE THREAD

**Issue by stemy2** [xbmc/Kore#489]
Hello,

Every time i start my kodi box, its local ip change, and i have to select/configure it manually. It's totally non-intuitive for beginners so it would be nice to do it automatically.

**Comment by MartijnKaijser** [comment]
Sorry to say but why does your network do such stupid things? Normally your device retains the same IP as it's tied to the MAC address for a while. This seems like just silly and Kodi shouldn't be your only issue on the network

**Comment by stemy2** [comment]
So according your message, this is an abnormal behaviour. Very interesting. Do you know how to fix it ?

**Comment by MartijnKaijser** [comment]
Should be an option in your router.

**Comment by stemy2** [comment]
Ok, thanks.

**Comment by stemy2** [comment]
Effectively, my router was misconfigured.
