### ISSUE TITLE
[Feature Request] Add ability to customise website used for actor bios

### ISSUE THREAD

**Issue by r0bbie** [xbmc/Kore#493]
When tapping an actor on the "Now Playing" page it's a nice feature that this opens up their IMDB profile to discover more. It would be great if there was a way to customise the website used for artist bios, for instance to switch to alternatives such as Wikipedia, TMDb, or Letterboxd.

**Comment by SyncedSynapse** [comment]
Not the same, but IMdb link has been replaced by a generic Google Search. It's not what is referred here, but i believe it's more versatile and probably satisfies the user.
Anyway, i'm not a fan of including a specific customization for this, as it doesn't seem to be a generalized request.
