### ISSUE TITLE
Jenkins fails to build Kore

### ISSUE THREAD

**Issue by MartijnKaijser** [xbmc/Kore#495]
I guess some changes are needed to get it building again

http://jenkins.kodi.tv/view/Android/job/Kore/1285/console

**Comment by SyncedSynapse** [comment]
The actual error is:
```
> You have not accepted the license agreements of the following SDK components:
  [Android SDK Platform 26, Android SDK Build-Tools 26.0.2].
  Before building your project, you need to accept the license agreements and complete the installation of the missing components using the Android Studio SDK Manager.
  Alternatively, to learn how to transfer the license agreements from one workstation to another, go to http://d.android.com/r/studio-ui/export-licenses.html
```

... no comments...

Not sure how to fix this in Jenkins, maybe @Memphiz can help

**Comment by Memphiz** [comment]
We had that shit before. Normally it only should happen if something changed related to the SDK? Well long story short - I am out of town over Christmas and don't have my keys with me for the build slave.

**Comment by SyncedSynapse** [comment]
Hi @Memphiz,

I think you've fixed this already, right? Thanks

**Comment by MartijnKaijser** [comment]
Yep.
Already gave him a cookie
