### ISSUE TITLE
[Feature Request] Support Oreo Colored Media Notifications

### ISSUE THREAD

**Issue by carlylemiii** [xbmc/Kore#499]
https://arstechnica.com/gadgets/2017/09/android-8-0-oreo-thoroughly-reviewed/3/#h3

Would look super slick if Kore would do this and ALSO display media art on the lockscreen like other media apps (Netflix, Yatse, Google Play Music, etc.).

**Comment by poisdeux** [comment]
Thanks for reporting this. I tested on an emulator and it seems that notifications don't work at all on Oreo. Can you confirm?

The following warning is what logcat shows regarding the issue. 

```
12-30 20:45:47.238 4377-4377/org.xbmc.kore.instrumentationtest W/Notification: Use of stream types is deprecated for operations other than volume control
12-30 20:45:47.238 4377-4377/org.xbmc.kore.instrumentationtest W/Notification: See the documentation of setSound() for what to use instead with android.media.AudioAttributes to qualify your playback use case
12-30 20:45:47.240 2062-2105/system_process E/NotificationService: No Channel found for pkg=org.xbmc.kore.instrumentationtest, channelId=null, id=1, tag=null, opPkg=org.xbmc.kore.instrumentationtest, callingUid=10085, userId=0, incomingUserId=0, notificationUid=10085, notification=Notification(channel=null pri=0 contentView=org.xbmc.kore.instrumentationtest/0x7f04005f vibrate=null sound=null defaults=0x0 flags=0x42 color=0x00000000 category=transport vis=PUBLIC)

```

**Comment by carlylemiii** [comment]
They show for me on 8.1.0 on my Pixel 2 XL.

https://imgur.com/vjx7SrY

**Comment by SyncedSynapse** [comment]
Notifications work on Oreo with the latest build.
Does the instrumentatioTest build issue notifications? In Oreo they need to
be posted to a channel (I've done that but not on the tests)

**Comment by poisdeux** [comment]
Ah I see you already fixed the issue in 3077653dd9f815052161565766f4a6a5a418d01a.
I didn't notice there were changes on master. Commits directly pushed on master don't sent notifications unfortunately...

@carlylemiii thanks for posting the screenshots. I must say that I actually find the Yatse notification worse. Hopefully it's a Yatse issue and with a proper poster image the new notification will look good as well.

**Comment by carlylemiii** [comment]
@poisdeux yeah, it doesn't look great with the poster being cropped. My point was showing how it auto-colors like other media apps and how it's a fuller-sized notification.

**Comment by OlegKrikun** [comment]
Looks like Kore need implement [MediaSession](https://developer.android.com/guide/topics/media-apps/working-with-a-media-session.html) for Colored Media Notifications

**Comment by carlylemiii** [comment]
Adding to my previous comment, there will likely need to be some "hacks" happening to get the notification lookin' good. The Yatse developer improved this notification - it takes away the smooth blending somewhat, but it adds the color and makes it so the poster isn't cropped terribly.
