### ISSUE TITLE
[Feature Request] Enable list item selection from Kore

### ISSUE THREAD

**Issue by cribskip** [xbmc/Kore#501]
It's no good user experience to keep switching view between a TV and a smartphone constantly when selecting items from a list. I think #179 aims the same target - preventing the constantly changing focus between smartphone and TV.

I'm thinking of getting the list items from Kodi to Kore and selecting the item to scroll to directly from Kore from a list, rather then pressing down, down, down thirty times.

**Comment by SyncedSynapse** [comment]
That's what the tv/movies/music sections are for.
The remote section is explicitly for navigation using the remote.
Or how do you propose it should be done?

**Comment by cribskip** [comment]
Oh, perfect solution, didn't see them.

Would be nice to be able to add apps to the sidebar then 😋
