### ISSUE TITLE
Re-establish connections after waking from sleep

### ISSUE THREAD

**Issue by anthonyryan1** [xbmc/Kore#531]
It would be nice to add an ACTION_USER_PRESENT BroadcastReceiver so that connections to the media center server can be re-established automatically after waking an Android remote from sleep.

Currently, on some devices it is faster to close Kore and re-open it than to wait for it to re-establish control over the LAN.

**Comment by SyncedSynapse** [comment]
With all the restrictions Google has placed on BroadcastReceivers i very much doubt that that still works.
