### ISSUE TITLE
KORE-PVR-Section 

### ISSUE THREAD

**Issue by ClausMM** [xbmc/Kore#535]
Hello,
I have been using for over a year
KODI (WINDOWS 10) + KORE (Samsung Galaxy S7). 
As a TV server running with me Mediaportal Version. 1.19.
 
There are 3 lists in the PVR_section of KORE:
1. TV channels
2. Radio stations
3. Recordings
Display and control of TV channels and radio stations everything super.
 
Only operation of the recording list is impractical if the list becomes longer.
The latest recording is always at the bottom of the list  :-(
 
Why can not the PVR pick list be sorted? 
Sorting (descending) by start date / time would be very helpful!

Greetings from Berlin, ClausMM

**Comment by ClausMM** [comment]
Hi
Am I the only one who has the problem?
The displayed recordings would only have to be sorted in descending order !!

_SELECT * FROM mptvdb.recording order by idRecording desc;_ (see image)

Best regards, ClausMM
![hc_379](https://user-images.githubusercontent.com/38686001/46493849-ab601480-c811-11e8-8e5f-40f7a67e706b.jpg)
![hc_378](https://user-images.githubusercontent.com/38686001/46493857-af8c3200-c811-11e8-9603-4968cf7e40d9.jpg)

**Comment by poisdeux** [comment]
https://startbigthinksmall.wordpress.com/2011/08/10/for-beginners-how-does-open-source-work/

**Comment by Selaron** [comment]
> Hi
> Am I the only one who has the problem?
Apparently not: #385
