### ISSUE TITLE
An error occured while syncing: Invalid params

### ISSUE THREAD

**Issue by axelsimon** [xbmc/Kore#545]
OS: LibreELEC (a [community testbuild](https://forum.kodi.tv/showthread.php?tid=298462&page=219)
Kore: v2.3.3 from f-droid
Kodi: Leia 18.0-ALPHA2 Git:19eb19e

Hi,
I'm using LibreELEC and I'm getting this error on syncing the music library:
> An error occured while syncing: Invalid params

The TV Shows and Movies library sync to Kore successfully.

I'm not too sure what to make of it, there aren't really any parameters one can tweak on the Kore side.

I got Kore to sync the music collection on a previous occasion (using a slightly older version of LibreELEC and the same version of Kore), but there was an issue: I thought Kore hadn't synced the whole music library, but it turned out Kodi hadn't scraped it properly. I after that, trying to refresh the Kore music library gave the same error (`invalid params`).
I then removed the Kodi instance from Kore and re-added it, and I'm still seeing `invalid params`.

On the LibreELEC side, I've tried removing the source and rebuilding the music library, this hasn't changed the error on the Kore side.
One last thing that could make a difference, I have a path substitution for the music in my advancedsettings.xml which I was planning to use when I switch back to a centralised MySQL database sharing:
>
    <from>/mnt/stuff/audio/</from>
    <to>/storage/music/</to>

Thanks!

**Comment by poisdeux** [comment]
Thanks for reporting this. I can confirm this issue with Kore v2.3.3 and Kodi Leia. However, the development version works for me, so could you please test if the latest nightly build still has this issue? http://mirrors.kodi.tv/tools/kore/nightlies/

**Comment by SyncedSynapse** [comment]
I'm almost sure that this is fixed. We need to make a new release to take care of it.
