### ISSUE TITLE
Interface: switching from remote back to media browser should take you back to last artist/album/etc.

### ISSUE THREAD

**Issue by axelsimon** [xbmc/Kore#55]
Situation:
- Pull media browser from the left of the screen, browse the music library to an artist, an album, start playing the album.
- Press the remote icon in the top left, to see current playing playlist and control it.
- Pull media browser and go to the music library again to add more items to playlist, you are back at the first item of your music library list.

Expected result:
- Pulling the media browser and going to the music library takes you back to last viewed artist/album.

If you have a large music library, you have to go back to the artist you were browsing if you want to add another album by the same artist.
Sure, you could several albums before switching to the remote, but one would expect to be taken back to the last browsed media item (album, artist) as that what Kodi does.

Small issue, but it would be nicer to use :)

Thanks!

**Comment by SyncedSynapse** [comment]
Use Android's back button to navigate back. It works in that scenario.
Accessing any section from the navigation drawer should take you to the base level, to be consistent with Android's guidelines for navigation.
