### ISSUE TITLE
Kore crashes when changing volume

### ISSUE THREAD

**Issue by mvhulten** [xbmc/Kore#551]
When upgrading from Kore **2.3.3** to **2.4.0** (from F-Droid), the application crashes when changing the volume.

I double-checked this by reverting back to 2.3.3, solving the problem (on up-to-date LineageOS); tripple-checked it with another device (up-to-date Fairphone Open).

The version of Kodi is `18.0-ALPHA1 Git:20180402-nogitfound Media Center Kodi`.

**Comment by poisdeux** [comment]
Thanks for reporting this. I can confirm the issue and provided a fix in PR #553.
Should be included in the next beta release. Please reopen this issue if it persists.
