### ISSUE TITLE
PartyMode does not work

### ISSUE THREAD

**Issue by gsantner** [xbmc/Kore#555]
Hi, I have a shortcut to start music partymode on my kodi machine - in favourites.
On Kodi I just press this favourite and partymode for music starts - means random music starts playing immediatly.
When I click on it on Kore, it says "unable to play favourite item - unsupported type". But this is not supposed todo something on my phone. It should just invoke the thing on Kodi.

I often very often don't have any TV screen on and just want to listen to music with kodi. This is not really easily possible currently. And "queue all" is no option either, as it takes like 10 minutes to start first song ;).

from favourites.xml:
```
<favourites>
    <favourite name="TV Sender">ActivateWindow(tvchannels,return)</favourite>
    <favourite name="TV EPG">ActivateWindow(tvguide,return)</favourite>
    <favourite name="Musik Partymodus">PlayerControl(Partymode(music))</favourite>
</favourites>
```

![screenshot_20180609-133449](https://user-images.githubusercontent.com/6735650/41191071-10e210f8-6bea-11e8-85a9-504d60741339.png)

**Comment by SyncedSynapse** [comment]
There's now a party mode button on the remote screen, though it only shows *after* playing music starts.

**Comment by gsantner** [comment]
So are also favorites properly supported now? So can be one icon clicked and it does the job, just like when I click the favorite with mouse?

I.e. PlayerControl and ActivateWindow showed error at Kore. But it works perfectly fine at Kodi.

**Comment by gsantner** [comment]
...I have kodi v2.5.3 installed it still shows "Unable to play favorite. Unsupported type".

The issue not fully is that Kore not can start PartyMode. The issue is at Favorites are broken.
