### ISSUE TITLE
Interface: playlist view requires tiny fingers to click item's context menu

### ISSUE THREAD

**Issue by axelsimon** [xbmc/Kore#56]
Hi there,
The playlist items have a three-dot context menu one can tap to remove them.

The zone with the three dots is so small, I often tap on the item itself which starts playing it.

My guests are usually only amused the first or two first times, after which they ask me to stop changing the music all the goddamn time.

A bigger zone to tap the three-dot context menu would help :)

Thanks!

**Comment by SyncedSynapse** [comment]
Makes sense. Fixed in 0a0328d176fb2a42db9e1dbf4bc6bcae50157f35
