### ISSUE TITLE
Kore 2.4.4 : New function "Play on local device" not working if kodi http password is set

### ISSUE THREAD

**Issue by Smeulf** [xbmc/Kore#564]
Hi!

I just tested the new function "Play on local device" with the 2.4.4 version under Android 7.0, and Kodi 17.6.

Sadly, this function doesn't work for me when the webserver is password protected, but works fine if I remove the password, whatever the player is (VLC or the movie player shipped with the phone).

Should you need more info or test, please just let me know.

All the best.

Smeulf.

**Comment by tomerf** [comment]
Fixed in #576.
