### ISSUE TITLE
[wishlist] streamline Kodi startup

### ISSUE THREAD

**Issue by chrysn** [xbmc/Kore#567]
When starting to use Kodi using my Kore remote, I need to take several steps in sequence:

* Enable Wifi
* Start Kore
* wait for Wifi to be connected
* Press the Wake-up button
* wait for the Kodi box to be started adn Kore to be connected

Ideally, all of that could happen when I open the Kore app, as it is in most configurations pretty useless outside a local network and without a Kodi server.

I'd like to suggest to add advanced configurations options (possibly on-by-default on new setups) that say:
* Enable WiFi when Kore is started. (This might need additional privileges in Android, but i think that those can easily be argued to be convenient. Connection attempts should be held off until readiness of the network is signaled by Android, to avoid waiting for any timeouts and tempt the user to press reconnect for things to be faster.)
* Send wake-up-on-LAN on every connection attempt. (Those can be sent right after the initial SYN package. If the device is off, no time is lost, and if it's on, the additional one multicast package (or burst) when starting the app won't do any harm).

**Comment by NeroRome** [comment]
I understand your wishes but I don't agree at all.

Ad Enable WiFi:
For me enabling/disabling Wi-Fi is something, I never want to be done by an App automatically. I want control for my device if it should use mobile Data, Wi-Fi and also which Wi-Fi network.
I hate Apps, which use too much permission. AFAIK for enabling Wi-Fi the permission _CHANGE_WIFI_STATE_ is needed and this permission cannot be revoked by the user.
In my case I also have more than one WLAN networks and I have to select the correct network (and this is not the strongest network and will not be selected automatically).

Ad Send WOL:
For me also this is not absolutely necessary. I'm fine with the button for WOL.
I also use Kore sometimes without running my Kodi-Server, e.g. see my move library and maybe I find a move to watch, but maybe also not.
Anyway there should be no automatic WOL always but it should be optional.


BTW: Maybe you can/will use an app like _Tasker_ to control Wi-Fi and send WOL. I don't know Tasker and so I don't know the features of this app.

**Comment by chrysn** [comment]
I'm fine with any of this being optional, and even opt-in.

As for WiFi permissions, it's a sad property of the Android ecosystem
that such permissions can't be fine-grained. Wiring this in with another
app is something that I'd need to try out to see whether it's a feasible
option.

**Comment by SyncedSynapse** [comment]
Somehow i missed this issue when you created it, so i didn't comment.

Anyway, i agree with @NeroRome, and i would strongly oppose changing Kore to ask for more permissions to control wi-fi. Even as an option.

As for sending a WOL automatically, personally i also don't see the need for it, but as an option, it might be acceptable. It's not that easy because we wouldn't want to be constantly issuing wol so some care should be taken in the code.

I'm inclined to close this issue as is. If you want to continue with the wol part, maybe creating another issue would be better. I also think that @NeroRome's suggestion of looking at tasker might be useful.

**Comment by turlututututu** [comment]
Hi all, sorry for the late arrival! Back to the wifi thing, I believe it would be better to at least show a message asking the user to check if he is connected to the appropriate wifi. Indeed, without it, it can be quite confusing for the none tech oriented user to sort things out!
