### ISSUE TITLE
Download only creates empty folder

### ISSUE THREAD

**Issue by jondo** [xbmc/Kore#57]
I am using Version 1.2.1 from F-Droid. Remote controlling my RaspBMC works fine.

However, when I try to download music (either by pressing the download button on the album screen or by selecting the corresponding context menu item of a track), Kore only generates the artist and album folder, but does not actually download the track files.

**Comment by SyncedSynapse** [comment]
For support, please use the forum http://forum.kodi.tv/forumdisplay.php?fid=129
