### ISSUE TITLE
Notification sometimes incorrectly shows "Nothing Playing"

### ISSUE THREAD

**Issue by coreyfarrell** [xbmc/Kore#570]
I'm experiencing intermittent failure of the Kore notification.  It sometimes gets stuck saying nothing is playing.  The main window shows the correct information, only the notification is wrong.  It seems like it happens after I watch episodes on the "Simpsons World" addon but I can't be sure yet.  One thing I can say for sure, to fix it I go into "App Info" for Kore and press "Force Stop".  When I reopen Kore the notification shows the correct info with ff/pause/rewind buttons.  Just closing / reopening the Kore window doesn't fix it.  I'm using Kore 2.4.4 installed from Google Play Store.

**Comment by SyncedSynapse** [comment]
Closing this as notifications have been extensively reworked
