### ISSUE TITLE
Watched check mark synchronisation

### ISSUE THREAD

**Issue by ThrowsThrowable** [xbmc/Kore#578]
When the "watched" check mark of a movie or episode is toggled in kore, the checkmark in the listview is mostly not synchronized. In this case, manually synchronising the list view by swiping down is required. Once in a while it seems to get updated automatically though.

Best way to reproduce this is to navigatie back immediately after toggling the check mark.

**Comment by SyncedSynapse** [comment]
Yes this happens. It's the result of trying to minimize the calls to Kodi to sync the database, which has this side effect. It's a compromise.
Note that the info will be updated. If you navigate to other section and back, it will show the correct status, it's just the navigate back that doesn't immediately show the updated status.
It can be a nuisance when you are marking movies/shows as watched, but this is an operation that imo isn't very common, so i'm not sure it's worth the added overhead of making sure it's always synced, given that the vast majority of time that will be unnecessary.

**Comment by ThrowsThrowable** [comment]
Ok I see, so it's an expected behaviour. No problem than, and marking just one episode / movie isn't common indeed.

I found out when I was actually trying to mark full seasons as unwatched. This is very useful for shows for toddlers with episodes of only five minutes. Therefore I was thinking about three dots menu in each season item of a show (Mark as watched / unwatched).

I would like to contribute to this project and help to develop new features but I'm not sure where to start. Do you prefer tickets here on github or on the kodi.tv forum? Is there something as a "where to start for developers" or overview of the code or should we just dig into the code? Finally, thanks a lot for this app!

**Comment by SyncedSynapse** [comment]
It's a known behaviour, not necessarily optimal i agree. Marking the whole season as watched/unwatched seems useful to me, either via an entry on the three dots menu, or when entering the episodes list, via the top right overflow menu (not as obvious, but not all that bad).

Issues/tickets should be posted here. To contribute, we don't have any guide or overview of the code... Feel free do dive right in, and post here or on the forum any questions/doubts.
