### ISSUE TITLE
Computer's VPN disable connection with the phone

### ISSUE THREAD

**Issue by stemy2** [xbmc/Kore#579]
Hello,

I'm using a VPN but the PC-side VPN makes it unusable cause i must desactivate it to be able to connect my phone to the PC. Strangely, my phone also has a VPN, but it doesn't prevents any connection to the PC.

**Comment by poisdeux** [comment]
I don't think this is a Kore specific problem. For general user support please use the Kodi forum. https://forum.kodi.tv/forumdisplay.php?fid=129

**Comment by stemy2** [comment]
I can't ask in the forum because they censor every descussion about VPNs, because according them it's a tool for cybercriminals.
I remarked something else that's strange: 
-if i activate the VPN after pairing, nothing but the back button is working.
-if i connect to the VPN with Network Manager, everything works well, but it's less handy than with the official VPN app.
