### ISSUE TITLE
Updated Dutch translations

### ISSUE THREAD

**Issue by ThrowsThrowable** [xbmc/Kore#580]
I translated empty dutch strings and modified others to be consistent with the Kodi translations.
**As I'm new to github** and contributing to open source projects, how should I push this file?
Should I first create an issue here (like I did here), than create a new branch (I'm using sourcetree btw) and finally create a pull request here?

**Comment by ThrowsThrowable** [comment]
Thanks, as I was unable to push to the repo, I created a fork. This is probably the way to do it, or not?
Than I could push and create a pull request from my fork: #581 
Please tell me if I'm doing stupid things... :)

**Comment by poisdeux** [comment]
No stupidities found! Indeed GitHub uses the [integration-manager workflow](https://git-scm.com/book/en/v2/Distributed-Git-Distributed-Workflows). See https://guides.github.com/ for more details.

**Comment by ThrowsThrowable** [comment]
Thx for these links, the second one will take some time to read :)
