### ISSUE TITLE
[bug/feat] Trunicated title information?

### ISSUE THREAD

**Issue by momoe** [xbmc/Kore#599]
To amend Fix https://github.com/xbmc/Kore/commit/da90f92ddcb6743249ca0387b88989c7b298524d instead of trunicating long titles, please have the main remote title scroll the title back/forth horizontally while a video is playing. As some local media does have very long title information, especially episode numbers in a series is impossible to read. 

Please provide some way to either view the entire title, or scroll the title information that will make key information be presentable such as the episode numbers. 

-Thank you.

**Comment by Isayso** [comment]
I would also like to have a smaller font option or wordwrap for the playlist view for the same reason. I'm guessing the title most of the time now. YouTube titles are often very long and rotating to landscape is sometimes inkonvenient. ;) 
Thanks a lot, its great work.

**Comment by Isayso** [comment]
I modified one grid_item  with maxlines and smaller font and deleted ellipsize. 
I think this is a better solution because the important information is often at the end.
Thanks!

![kore_mods](https://user-images.githubusercontent.com/35309607/67385959-60d44600-f594-11e9-98d0-18539f886697.jpg)
