### ISSUE TITLE
Cannot distinguish long track titles

### ISSUE THREAD

**Issue by jondo** [xbmc/Kore#60]
Track titles like
`Suite No. 1 in F major, HWV 348 "Water Music": IV. Andante - Allegro` and
`Suite No. 1 in F major, HWV 348 "Water Music": V. Passepied`
are both displayed as `Suite No. 1 in F major, H...` and therefore indistinguishable.

I suggest removing the middle instead, to get
`Suite No. 1...te - Allegro` and `Suite No. 1...V. Passepied`.

**Comment by SyncedSynapse** [comment]
Can't remove the middle. Might be able to scroll the title, but i'm not certain that this should be done everywhere. Where do you think this is most problematic?

**Comment by jondo** [comment]
I think it is most problematic in the playlist, because this uses narrow columns in landscape mode.
There, much wider columns (or just one column) would help.

On my 1280×720 phone, this also happens in landscape mode in the "remote control". Using two lines might help here. (And of course it happens everywhere in portrait mode.)

**Comment by SyncedSynapse** [comment]
Fixed in da90f92ddcb6743249ca0387b88989c7b298524d
