### ISSUE TITLE
Kore does not show "Playing" UI after I start a video

### ISSUE THREAD

**Issue by jamesbroadhead** [xbmc/Kore#602]
### Describe the bug
From the "Remote Control" UI, after clicking the center button to play a video, Kore does not display the "Playing" UI. 

Sometimes, after 10-30 seconds, the Playing UI appears 
Other times, the Playing UI never appears. The app remains on the "connected to <server>" UI

If I force-quit the application and restart it, the Playing UI appears immediately 

## Expected Behavior
The 'Playing' UI should be shown as soon as the video begins to play. 

## Actual Behavior
Sometimes it never shows - as a result, I cannot pause or stop the video. 

## Possible Fix
Poll the kodi api more frequently? 

### To Reproduce
1. Navigate to a video using the 'remote control' UI
2. Use the middle button to play the video 
3. Wait. 

### Debuglog
Log: https://paste.kodi.tv/huniqijoyi.kodi
Started video at 23:52.
Kore did not show the 'playing' 
At 23:52:59, I restarted Kore, it showed the 'playing' UI & I stopped the video

Debug Log: http://dpaste.com/2QH0DR9

### Screenshots 
Here are some links or screenshots to help explain the problem:
https://photos.app.goo.gl/Sj3crzm7E5zdYUpa7 - the remote control ui
https://photos.app.goo.gl/6pvkCb9tjgBTieeA6 - the "playing" ui

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:
 - Mobile device: Huawei P20 Pro
 - Android version: 8.1.0
 - Kodi version and platform: 18.0_rc2  (this is a long running problem however)
 - Kore version: 2.4.4

**Comment by SyncedSynapse** [comment]
Thanks for the detailed report.
I honestly have never seen this happening. On slower Kodi devices it might take a couple of secs to show up (for Kore to be notifies), but i shows.
Please check if the TCP option is enable in Kore for that Kodi instance, though it should work either way.
I'm more inclined to believe it has something to do with you device. Huawei has been pulling some naughty stuff with Android lately, namely killing (perfectly valid) background processes, in an effort to appear well in battery tests. Can you check if your battery saving settings isn't preventing Kore from functioning correctly (maybe whitelist Kore, or try another phone).

**Comment by poisdeux** [comment]
Finally had some time to look into this. It seems there is a race condition causing problems.
Below is some logging when starting a video using the reported method.
We receive an `Player.OnPlay` method which we follow up by calling the `GetActivePlayers` chain sequence.  This asks Kodi which players are active and it seems Kodi still thinks there are no active players. 
I'm not sure but it looks like an issue on Kodi's side. However, I think we can also redesign the way we check if there is something playing. As the `Player.OnPlay` method also returns the `playerid` which we use to get the properties of the currently playing item.

```
2019-01-31 20:30:57.369 org.xbmc.kore D/HostConnection: Read from socket: {"jsonrpc":"2.0","method":"Player.OnPlay","params":{"data":{"item":{"id":2,"type":"movie"},"player":{"playerid":1,"speed":1}},"sender":"xbmc"}}
2019-01-31 20:30:57.369 org.xbmc.kore D/HostConnection: ignore tcp response - false
2019-01-31 20:30:57.369 org.xbmc.kore D/HostConnection: Got a notification: Player.OnPlay
2019-01-31 20:30:57.369 org.xbmc.kore D/HostConnection: Starting method execute. Method: Player.GetActivePlayers on host: http://10.0.2.2:8080/jsonrpc
2019-01-31 20:30:57.370 org.xbmc.kore D/HostConnection: Sending request via TCP: {"jsonrpc":"2.0","method":"Player.GetActivePlayers","id":252}
2019-01-31 20:30:57.374 org.xbmc.kore D/HostConnection: Read from socket: {"id":252,"jsonrpc":"2.0","result":[]}
```

**Comment by MartijnKaijser** [comment]
iirc there was some change done to this part of the code. Might ask in our slack channel #python cause it had something similar

**Comment by SyncedSynapse** [comment]
Had some talk with the team, and this forum thread explains the issue:
https://forum.kodi.tv/showthread.php?tid=298461&pid=2660601#pid2660601

Ticket here: https://trac.kodi.tv/ticket/17632

And the solution: https://github.com/xbmc/xbmc/pull/13726

So we basically can't rely on OnPlay for v18+ and implement onAVStart/Change/Resume.

**Comment by actricom** [comment]
This is definitley an annoying bug introduced by v18 (I installed it today over v17.6). I have never seen this happen previously, but it now happens when playing a video that requires a screen resolution change (and therefore a slight delay). So if I play a 24p video I see the issue, otherwise I don't. If this can't be fixed due to an asynchronous issue, then a slight delay in code before checking will fix it probably every time and is preferable to it never working.

**Comment by actricom** [comment]
**WORKAROUND**: I have found that if you start a problem video that gives you the "Nothing playing" screen, you can fix it by pressing the right arrow button on the control panel underneath. You can be as fast as you like (even before the video actually starts) and it works! Hope this helps. So, as per my previous post, I would think a one second delay in code would fix it.

**Comment by MartijnKaijser** [comment]
That is **not** a fix. Read was was mentioned above

**Comment by SyncedSynapse** [comment]
@actricom A fix is coming, probably tomorrow. In the meantime if you don't want to be affected by this, disable the "TCP" option in Kore (in the Kodi config screen).

**Comment by actricom** [comment]
Thanks @SyncedSynapse
