### ISSUE TITLE
Provide context menu for directories

### ISSUE THREAD

**Issue by RalfJung** [xbmc/Kore#608]
## Feature suggestion
**Detailed Description**

Provide access to directory context menu when navigating files (e.g. on auto-mounted device).

### Context

It is currently not possible, from the app, to enqueue an entire directory for music playback. When using the main Kodi UI, I can do that with the context menu on a directory, but the app does not have a context menu on directories.

**Comment by SyncedSynapse** [comment]
Isn't that what the top left icon on the remote d-pad does (the one to the left of the up arrow)?

At least going into Music->files->tapping there brings up the context menu.

**Comment by RalfJung** [comment]
That's when using the app as a remote and looking at the TV screen.

I am talking about the part of the app that locally displays menus and lets you navigate without even looking at the TV screen.

**Comment by RalfJung** [comment]
Yeah I found that, it's not very discoverable though. Moreover, it doesn't help when I already have some songs queued and now want to queue another whole directory.
