### ISSUE TITLE
Add option to disable lockscreen while remote is active

### ISSUE THREAD

**Issue by ThiefMaster** [xbmc/Kore#61]
Another useful feature from the old xbmc remote. While watching a movie it's quite annoying to unlock the phone using the lockscreen pattern (or whatever is used) just to access the remote.

For extra security I'd suggest to automatically re-enable the lockscreen once playback stops, so if you e.g. fall asleep while watching a movie your phone is only unlocked until it finished.

**Comment by shtrom** [comment]
:+1: see also #109, for a widget on the lock screen.

**Comment by sputtene** [comment]
I use Llama for that. It's an app that automatically performs actions when certain conditions are met. You can find it on Google Play for free.

My events in Llama:
- When the current app is Kore: disable screen timeout
- When charging: set screen timeout to 300 seconds
- When using battery: set screen timeout to 60 seconds

The first event keeps the screen on when Kore is the active app, so the lock screen isn't displayed either.
One of the two other events take care of reinstating the screen timeout when Kore is no longer the active app.

**Comment by shtrom** [comment]
Not available on F-Droid ):

**Comment by sputtene** [comment]
Unfortunately not. I've searched F-Droid first, but didn't find any apps that allow you to automate stuff. If you find any, please let me/us know :)

I've settled for Llama from the Play Store which is free, unlike Tasker for example.

**Comment by SyncedSynapse** [comment]
@jtdor has added a commit that helps with this issue. It doesn't keep the phone awake, but i'm not a fan of that either (and i believe it requires additional permissions, which i dislike even more), but is a good solution imo.
