### ISSUE TITLE
A new translation from Transifex

### ISSUE THREAD

**Issue by Valdnet** [xbmc/Kore#624]
The translation in Polish on Transifex has been completed. You can download them and release a new version of the application. I would like to see and check the translation :wink:

**Comment by SyncedSynapse** [comment]
I'm not sure where you did the translatation, but Kore isn't yet officially on Transifex, on an account that the foundation manages.

**Comment by Valdnet** [comment]
This is not your team? :grimacing:
https://www.transifex.com/yaron/kore/dashboard/

All menu descriptions match. Where do you translate your descriptions?

**Comment by SyncedSynapse** [comment]
No. For now we accept direct PRs for translations here.
But i believe that that transifex project belongs to @yarons , so he might issue a PR with the Polish translations so that your work is included.

**Comment by yarons** [comment]
@SyncedSynspse
Are you willing to set up integration and I'll add you as administrator on this Transifex project?
I'm already managing translations for several other projects, either on that platform or Crowdin, I can also ask for Weblate (open source) hosting if it suits you better.

**Comment by yarons** [comment]
@Valdnet, I'm on it 😀

**Comment by SyncedSynapse** [comment]
@yarons Thanks, but we (xbmc) actually have a transifex account, and we should be using that.

@MartijnKaijser Who is managing Transifex nowadays?

**Comment by yarons** [comment]
Oh well, that sucks because I wanted to join this team and I didn't get in, so if it will be managed through their account I'll probably lose access.

**Comment by Valdnet** [comment]
> so he might issue a PR with the Polish translations so that your work is included.

Ok. Please add Polish translation. It is a pity that you will not be able to add translations to Transifex. I actively work on it.

I use the application every day and it is very good. The only thing missing is #620.

**Comment by yarons** [comment]
I see that there's already a Polish translation… contributed about a year ago…

**Comment by alanwww1** [comment]
Guys, since Kore is one of the most often used addons, I'd put it into the official Kodi Transifex project like the core language files and PVR addons. This way it would get autonatic updates in its repo. All I need is contributor access to the repo for.
Cheers, Attila

**Comment by Valdnet** [comment]
@alanwww1 very good idea.

I hope you will get along somehow.

> I see that there's already a Polish translation… contributed about a year ago…

It has been a little improved. New descriptions translated also.

**Comment by Valdnet** [comment]
@yarons what decision?
@SyncedSynapse what about the translation?

**Comment by SyncedSynapse** [comment]
@alanwww1 You should have "write" access to this repo, as a member of team-kodi. Do you need "maintain" access?

**Comment by homocomputeris** [comment]
@SyncedSynapse Is Crowdin https://crowdin.com/project/kore used for translation?

**Comment by SyncedSynapse** [comment]
@homocomputeris No, that's an even older project that i started, but it's not used anymore.

I'll try to get Kore set up on Kodi's Transifex.

**Comment by homocomputeris** [comment]
> @homocomputeris No, that's an even older project that i started, but it's not used anymore.
> 
> I'll try to get Kore set up on Kodi's Transifex.

It seems that Kodi will [migrate from Transifex](https://forum.kodi.tv/showthread.php?tid=353289), so probably it makes sense to use Crowdin.

**Comment by yarons** [comment]
Just tell me when and I'll disable or remove it to avoid confusing the translators, some of them are still applying on Tx.

**Comment by SyncedSynapse** [comment]
Took a while, but we've setup Kore at Transifex, with the already translated languages uploaded.

It's available here: https://www.transifex.com/teamxbmc/kore-android-remote/dashboard/

I'm new to Transifex, so it might take a while till i understand how it works and incorporate the translations on Kore.

Sorry for the delay, closing this for now.
