### ISSUE TITLE
[Feature request] Ability to take screenshot

### ISSUE THREAD

**Issue by tjsuominen** [xbmc/Kore#628]
## Feature suggestion
Very often Kodi "boxes" are hidden or even don't have a physical keyboard attached. At the moment it's a bit tricky to make screenshots @ Kodi UI. Having such functionality in Kore would very useful and make Kore app / Kodi UX e.g. in debugging cases much better.

### Context
To ease Kodi UX e.g. in debugging cases when a screenshot is required and one doesn't have a physical keyboard at hand. It would benefit all Kodi / Kore users.

### Possible Implementation
Have a separate button in the Kore UI to take a screenshot when pressed.

**Comment by SyncedSynapse** [comment]
This is not currently possible to do, as Kodi doesn't expose a screenshot function to external apps.

Even if it was possible, i wouldn't allow a separate button on Kore to do this, as it is such a specific use-case that it doesn't justify it.

**Comment by tjsuominen** [comment]
OK, well justified.
