### ISSUE TITLE
[Feature request] Process formating-tags on "Now playing"-information

### ISSUE THREAD

**Issue by Niklas04** [xbmc/Kore#629]
## Feature suggestion
May it could be possible to process or hide formating-tags for texts.

**Detailed Description**

I'm using the "DMAX Mediathek" from LORE with Kodi (some online video libary).
This addon uses some tags to format parts of the title and subtitle in different colors.
The tags are shown in the screenshots below ("[COLOR chartreuse]", "[/COLOR]").

May it could be possible to process these tags in Kore or to hide these tags.

Due to these format-tags it is sometimes a bit difficult to read the title of the played video.

### Additional context, screenshots or links
Here are some relevant links or screenshots:

<img src="https://user-images.githubusercontent.com/33813894/54562001-5894a680-49c6-11e9-90ad-ccc9da7236cc.png" width="300">
<img src="https://user-images.githubusercontent.com/33813894/54562031-6518ff00-49c6-11e9-83e1-5ebb940d24e8.jpg" width="600">

*Note: Team Kodi will consider this item however we will not make any promises if it will be included.*

**Comment by MartijnKaijser** [comment]
The add-on dev should stop using these stupid tags cause he cannot know if the correct colour is used in whatever skin

**Comment by dagwieers** [comment]
@MartijnKaijser Then at least remove the color-formatting. But currently also [B], [I], [LIGHT], [UPPERCASE], [LOWERCASE] are also not supported.
