### ISSUE TITLE
(Feature Request) IMDB/Themoviedb link to movie

### ISSUE THREAD

**Issue by SmasherDK** [xbmc/Kore#634]
You can press on an actor, and go straight to imdb (search imdb for that actor name)

But it would be really nice, that you could just press on the movie name, and go straight to that movie on imdb or themoviedb.
It allready has all the data, from when it scraped the movie? :)

Best regards...  and have a nice eastern.

**Comment by SyncedSynapse** [comment]
Closing, as links have changed from pointing to imdb to generic google searches
