### ISSUE TITLE
File browsing takes forever when changing directories

### ISSUE THREAD

**Issue by rigid** [xbmc/Kore#64]
When using the "File browser", it takes forever to change directories. It seems the deeper the directory structure is, the longer it takes. Also, there is no kind of progress indicator, which can be confusing on long delays. (I just tested "Music". "Videos" and "Pictures" might be affected also.)

**Comment by DanhKE6D** [comment]
If there are a lot of files and directory are deeply structured, json rpc response string could be quite long and may take a while to parse. I will put up a progress indicator when requesting a content of a directory from Kodi.

**Comment by rigid** [comment]
I'm not sure if this is caused by the pure amount of data. (about 100 list entries per directory max. in my case and about 6-7 parent directories). With XBMC Remote I can browse everything instantly.
