### ISSUE TITLE
Contribute to Korean translation

### ISSUE THREAD

**Issue by parkmino** [xbmc/Kore#644]
Korean translation seems still missing, and I'd like to contribute to this.
Should I translate Kore/app/src/main/res/values/strings.xml and attach the file here?

**Comment by SyncedSynapse** [comment]
Yes, that's the file, but don't attach it here, just send a PR.

**Comment by parkmino** [comment]
OK, I will try PR first.
If it fails, I will reopen this issue and attache the files.
