### ISSUE TITLE
Inconsistent string name and translation in strings.xml

### ISSUE THREAD

**Issue by parkmino** [xbmc/Kore#645]
The string name and translation comment seems not to match.
Please confirm whether it is correct or not, so that I can go on with Korean translation.

Kore/app/src/main/res/values/strings.xml at 285 line

    <string name="confirm_artist_download">Are you sure you want to download all albums?\nThe albums will be downloaded in the background, but it can take a while to finish.</string>

**Comment by SyncedSynapse** [comment]
It's correct - it refers to all albums of the artist.
