### ISSUE TITLE
[Feature] Connect via NBNS (netbios hostname) instead of IP

### ISSUE THREAD

**Issue by stevenstrike** [xbmc/Kore#67]
Tried on Windows 8.1(Kodi) using Android 5.0(Kore) on same network, connection via IP is working, not working using Kodi-PC's hostname (netbios). (Using a simple router with no DNS functionalities, only via netbios broadcasting)

Thanks for reading.

**Comment by SyncedSynapse** [comment]
This works for me, so it must be something on your network that isn't resolving the hostname. Tried it with Linux and Windows 8.?

**Comment by stevenstrike** [comment]
[**@SyncedSynapse**](https://github.com/SyncedSynapse) commented on [15 avr. 2015 19:54 UTC+2](https://github.com/xbmc/Kore/issues/67#issuecomment-93501570 "2015-04-15T17:54:56Z - Replied by Github Comment Enhancer"):
> This works for me, so it must be something on your network that isn't resolving the hostname. Tried it with Linux and Windows 8.?

Sorry i posted this ticket a little too quick. I was actually asking for a NBNS (winbind i guess) implementation, for those stuck with a simple router in which you can't manage hostnames.
