### ISSUE TITLE
Provide larger icon in app overview

### ISSUE THREAD

**Issue by PanderMusubi** [xbmc/Kore#670]
### Describe the bug
Icon of this app in the app overview in settings is too small, see screenshot.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:
Icon should be the same size as other icons in the app overview.

## Actual Behavior
Icon is too small, see screenshot

### To Reproduce
Go in Settings to App and notifications and show all apps.

### Screenshots 
Here are some links or screenshots to help explain the problem:
![kore](https://user-images.githubusercontent.com/198964/63535439-b8612180-c511-11e9-989b-621ccf6d7918.png)

### Your Environment
Used Operating system:
 - Mobile device: OnePlus 5T
 - Android version: 9 (LineageOS 16)
 - Kodi version and platform: n/a
 - Kore version: 2.4.7

**Comment by PanderMusubi** [comment]
Installed the app via F-Droid. See also https://github.com/dmfs/opentasks/issues/827 for similar issue and possible fix.

**Comment by SyncedSynapse** [comment]
Fixed in #619
