### ISSUE TITLE
".." item behave diffrently from Kodi

### ISSUE THREAD

**Issue by bigretromike** [xbmc/Kore#673]
### Describe the bug
Here is a clear and concise description of what the problem is:

When navigating directory structures made inside addon the ".." (go level up/go to parent) item behave very different from Kodi behave. In Kodi when you use ".." it act as "go back", but from Kore it act as "go level up". When using routing plugin and I would enter `plugin://plugin.video.myplugin/menu/` and the item I enter have path `plugin://plugin.video.myplugin/tvshow/1/` and load, if I enter ".." item in Kore, Kore cut lat part of the url and want to enter `plugin://plugin.video.myplugin/tvshows/` when In real it should enter `plugin://plugin.video.myplugin/menu/`

## Expected Behavior
Here is a clear and concise description of what was expected to happen:
When I enter ".." item I would like to go back to directory from whom I enter before.

## Actual Behavior

When I enter ".." item the `url` is modified and the path that does not exist is trying to be access, it cut last 'folder' from url ex. `plugin://plugin.video.myplugin/tvshows/1/` will be translated to `plugin://plugin.video.myplugin/tvshows/` even when I enter from different menu.

## Possible Fix

Make `..` work as back button - same as in Kodi.

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

not needed

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - Mobile device:
 - Android version: 8.0
 - Kodi version and platform: 17.6, 18.4, 19.0
 - Kore version: 2.4.7
 

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by SyncedSynapse** [comment]
This is fixed in the latest version, available soon

**Comment by bigretromike** [comment]
That's a great news - it's been hell difficult to track every small "bugs" that are there and aren't critical. Thanks for fixing/reporting back.
