### ISSUE TITLE
Keyboard handling with multiple remotes connected

### ISSUE THREAD

**Issue by Yamakaky** [xbmc/Kore#675]
## Feature suggestion
**Detailed Description**

When I select a text field using kore, the android keyboard correctly pops up. However, if 2+ kore are connected on the same kodi, the keyboard only appears to one kore. 

### Context

This is annoying if the kore where the keyboard pops on is in an other room. I also couldn't find how to kick a remote, so the only option is to close kore on the other phone. 

### Possible Implementation

- put the keyboard in the kore currently in use (best one I think) 
- put the keyboard on all the kore connected
- ask the user

### Additional context, screenshots or links
Here are some relevant links or screenshots:

*Note: Team Kodi will consider this item however we will not make any promises if it will be included.*

**Comment by SyncedSynapse** [comment]
This doesn't seem to be an issue with Kore, but an issue with Kodi. Sounds like when there's more than one client connected through TCP, only one get notified.

Anyway, FYI, you can always tap the three dots menu and select "Send text to media center" to go around this issue.

**Comment by Yamakaky** [comment]
Oh OK, thanks, will report!
