### ISSUE TITLE
Widgets for Stop and Pause/Play

### ISSUE THREAD

**Issue by PanderMusubi** [xbmc/Kore#679]
## Feature suggestion
Offer 1x1 widgets for:
* Stop
* Pause/Play
* Next (optionally)

**Detailed Description**
Tapping the stop widget will pause the Kodi instance Kore is currently connected with. This widget will have only a square symbol on it. Similarly the pause/play widget will pause or play that Kodi instance, only this widget will also change how it looks from two bars to a triangle. Both reflect same look and behavior of these buttons inside Kore.

Optionally, a next widget could be implemented with a triangle pointing right.

### Context
When in a rush to stop or pause Kodi, these widgets are quicker to operate than when having to open Kore or having to switch back to Kore, etc. This is especially useful when the user is playing media for a longer period of time not involved in operating Kore at that time.

**Comment by SyncedSynapse** [comment]
There's notifications for that. I don't think widgets are appropriate in this context
