### ISSUE TITLE
`musicbrainz_albumartistid` tag is used instead of `artist`

### ISSUE THREAD

**Issue by jondo** [xbmc/Kore#68]
I have got a FLAC file with the tags `artist` and `musicbrainz_albumartistid` (among others). Kore now wrongly uses the `musicbrainz_albumartistid` instead of the `artist` as artist.
Kodi correctly uses the `artist` tag.

**Comment by SyncedSynapse** [comment]
It uses the `display_artist` returned from Kodi, whatever that may be in relation to FLAC. Where are you seeing that?
