### ISSUE TITLE
[bug] Language resets to default on changing screen orientation (in settings only)

### ISSUE THREAD

**Issue by akc-kyiv** [xbmc/Kore#686]
### Describe the bug
Here is a clear and concise description of what the problem is:

When you use an in-app language other than system one, the language of UI reset to system default on changing screen orientation (in settings only). User needs to leave settings page to fix the issue.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Custom language stays in any scenarios

## Actual Behavior

Custom language reset to the default one on changing screen orientation (on the settings page)

### To Reproduce

1. Set language to any other than the system one
2. Go to the Settings page
3. Rotate your device

### Your Environment
Used Operating system:

 - Android version: 9.0
 - Kodi version and platform: 18.5
 - Kore version: Built from the latest master branch

**Comment by poisdeux** [comment]
Thx for reporting this. PR #689 should fix this.

**Comment by poisdeux** [comment]
@akc-kyiv did #689 fix the issue for you?

**Comment by akc-kyiv** [comment]
> 
> 
> @akc-kyiv did #689 fix the issue for you?

Yes, sorry, forgot to let you know. It's fixed, thanks
