### ISSUE TITLE
Publish beta releases on testing channel

### ISSUE THREAD

**Issue by jaylinski** [xbmc/Kore#696]
## Feature suggestion

Periodically publish new changes to the Play Store testing channel:

https://play.google.com/apps/testing/org.xbmc.kore

### Context

Your last release dates back to February 2019 (9 months ago). Since then a lot of improvements and fixes have been added to the app, which we can't use, since they weren't released yet.

One example is the addition I contributed a while back: #671 

Releasing a new (stable) version requires manual testing in order to ensure the app works as expected. A testing channel lowers that barrier by not having to invest that much time into testing, thus making it easier for you developers to publish a (testing) release more often.

### Possible Implementation

https://support.google.com/googleplay/android-developer/answer/3131213?hl=en

### Additional context, screenshots or links
Here are some relevant links or screenshots:

Signal uses a similar approach: https://support.signal.org/hc/en-us/articles/360007318471-How-do-I-join-Signal-s-beta-

*Note: Team Kodi will consider this item however we will not make any promises if it will be included.*

**Comment by poisdeux** [comment]
We already use beta releases. See https://forum.kodi.tv/showthread.php?tid=233827
I guess the real issue you're addressing here is that we take a long time to finally release a new version on GooglePlay. If you want to be more up-to-date you can get the latest build from the `master` branch here: http://mirrors.kodi.tv/tools/kore/nightlies/

@SyncedSynapse we can automate the release to GooglePlay as well. If we introduce two new permanent branches (`beta` and `production`) we can automatically push each nightly to the `alpha` track. Each latest commit on `beta` is released to the `beta` track on GooglePlay and each latest commit on `production` is released to the `production` track.
All development continues to be performed on `master` and when we want to create a new release we merge it into `beta`. This allows development to continue while we can apply hot fixes for the beta release . If beta is found to be  good enough we merge the `beta` branch into `production` to create a new production release. And as we use a branch for `production` as well we can even apply hot fixes on production.
By automatically setting the version code as the sum of all commits on `master`, `beta`, and `production` creating a new release will always have a higher version code than any previous release as required by GooglePlay.

**Comment by jaylinski** [comment]
@poisdeux Thanks for the detailed response! :heart: I didn't know about the nightlies. 

I'll leave this issue open so you can discuss this further with @SyncedSynapse if you want to. Feel free to close it anytime.

**Comment by SyncedSynapse** [comment]
I'll admit a mea culpa here, and i promise to try really hard to push a new beta release this week :)

@poisdeus Looks like a good plan, now we just need a plan to execute that plan :) Keeping this open for now

**Comment by 466** [comment]
Is there a f-droid beta testing channel?

**Comment by SyncedSynapse** [comment]
No, but f-droid pulls all releases that are marked with a tag in github, and as we usually mark beta releases with tags, f-droid gets those as "final"...
