### ISSUE TITLE
Support for songs without an album in Music

### ISSUE THREAD

**Issue by mvglasow** [xbmc/Kore#7]
First of all, thanks for a great app!

What I'm currently missing is support for songs in Music. Right now, I can browse artists, albums and genres. Artists and genres are essentially filters on albums – touching one will show me all albums by that artist or of that genre. Touching an album will just show me the album (again) and give me the option to play the whole album. There's no way to see the names of the individual songs, or add just one song from an album to the playlist (other than by adding the whole album and then examining the playlist). Songs that don't have album info are apparently inaccessible from Kore.

I'd like to be able to:
- See and select individual songs by an artist (including those which are not on any album)
- See and select individual songs of a particular genre, or all artists of a particular genre
- Search for songs by name

Maybe this could be solved with a two-level filter concept:
- Swiping to Artists, Albums or Genres and touching an item will add that item to a filter. The selection is displayed in the navigation bar and the hamburger icon changes to a backward arrow (touching it will remove the filter).
- Users can then swipe between the same pages, but only items matching the filter will be displayed (rather than the entire library).
- Touching another item with the filter active will bring up the list of songs that match both criteria (filter and item touched after that). Users can then either touch the "Play" buttom at the bottom to add all songs to the playlist, or touch individual songs to add them to the playlist. (Maybe include a play button in the card for each song to make the action clearer.)

**Comment by SyncedSynapse** [comment]
In the album, if you scroll down, you should have the list of songs of that album. If it's not appearing for you, that means that something bad happened during the sync process.

Try resyncing your music library (swype down), and wait till the end to check if it ends successfully.

**Comment by mvglasow** [comment]
Oh... hadn't seen that before, thanks! That solves it for songs that are 
part of an album. How can I see songs without album info?

**Comment by SyncedSynapse** [comment]
You can't...
I'll change the title of this issue to reflect this.

**Comment by privong** [comment]
Howdy. I want to echo @mvglasow's thanks for the great app. I just recently returned to using kodi after a long hiatuis from xbmc; the app is working great.
I had also noticed the issue selecting songs without album info; I came across this issue and was wondering if there was a plan or timeline for implementing it?

**Comment by mvglasow** [comment]
Hello!

 

New message, please read <http://phanmemoto.com/condition.php?qnfi>

 

Kate Denis-Smith

**Comment by wuliwuente** [comment]
+1

Besides Kore being great for videos and movies, this pretty much makes the music feature useless. Currently I'm using the file browsing, which works fine, but with a little bit of comfort lost.

**Comment by mvglasow** [comment]
Hi, You're not gonna believe what I've read yesterday, you've got to read it yourself at <http://slustythoky.tuskla.com/aeovpm>

Warm regards, Michael von Glasow

**Comment by poisdeux** [comment]
I believe release 2.1.0 fixes issues:

  * See and select individual songs by an artist (including those which are not on any album)
  and  
  * Search for songs by name

If so, I want to close this issue and create a new issue for:

  * See and select individual songs of a particular genre, or all artists of a particular genre

as it requires some more thought/discussion on how to implement this in a way it doesn't disrupt the UX.

Can @mvglasow and others confirm?

**Comment by mvglasow** [comment]
Upgraded to 2.1.0 a few days ago.

Selecting songs for playback now works for songs which are not part of an album – many thanks for that!

There are still issues with downloading songs that are not part of an album:
* The Songs tab doesn't offer download at all, unlike the Albums tab (which has support for downloading individual songs).
* When tapping Download on the Info tab of an artist that has no album (none of the artist's songs have album info), nothing happens – in some instances this will even cause Kore to crash..
* I haven't tried how the download button on the info tab behaves if some of the artist's songs have album info and others do not: ill it download all songs or just those with album info? That would need to be tested as well.

**Comment by SyncedSynapse** [comment]
You've uncovered some bugs on Kore...
Downloading on Artists isn't working but it's an easy fix. Downloading songs without artist or album info will probably crash Kore somewhere...

**Comment by poisdeux** [comment]
@mvglasow does 2.2.0 still have the above mentioned issues?

**Comment by poisdeux** [comment]
Closing this as this should have now been fixed. Please reopen if the issue persists.
Regarding the other feature requests by OP please open an issue per feature request.
