### ISSUE TITLE
Kore on F-droid version outdated

### ISSUE THREAD

**Issue by EnerGeh** [xbmc/Kore#704]
The current proposed version on f-droid is still 2.4.7. I don't know how to fix it, but am very glad to help if you tell me how 😉

**Comment by SyncedSynapse** [comment]
Supposedly F-Droid should have picked it up automatically - AFAIK as long as we tag the releases F-Droid picks them up.
I don't know how they implemented that, but there's already an issue opened on f-droid related to this: https://gitlab.com/fdroid/fdroiddata/issues/1913

The last person that did something on Kore's side regarding f-droid was @mueller-ma so maybe he has some kind of insight into this.

**Comment by mueller-ma** [comment]
F-Droid didn't try to build the 2.5.0 (versionCode 26): https://f-droid.org/wiki/page/org.xbmc.kore/lastbuild_26
The version code was bumped before tagging the release, so it should be fine. No idea, why F-Droid doesn't build and publish Kore.

**Comment by licaon-kter** [comment]
```
DEBUG: Directory: build/org.xbmc.kore
DEBUG: > git -c core.askpass=/bin/true -c core.sshCommand=/bin/false -c url.https://.insteadOf=ssh:// -c url.https://u:p@bitbucket.org/.insteadOf=git@bitbucket.org: -c url.https://u:p@bitbucket.org.insteadOf=git://bitbucket.org -c url.https://u:p@bitbucket.org.insteadOf=https://bitbucket.org -c url.https://u:p@github.com/.insteadOf=git@github.com: -c url.https://u:p@github.com.insteadOf=git://github.com -c url.https://u:p@github.com.insteadOf=https://github.com -c url.https://u:p@gitlab.com/.insteadOf=git@gitlab.com: -c url.https://u:p@gitlab.com.insteadOf=git://gitlab.com -c url.https://u:p@gitlab.com.insteadOf=https://gitlab.com fetch --prune --tags --force origin
DEBUG: Directory: build/org.xbmc.kore
DEBUG: > git remote set-head origin --auto
DEBUG: Directory: build/org.xbmc.kore
DEBUG: > git checkout -f origin/HEAD
DEBUG: Directory: build/org.xbmc.kore
DEBUG: > git clean -dffx
DEBUG: ...fetch auto name from build/org.xbmc.kore
DEBUG: Parsing manifest at 'build/org.xbmc.kore/build.gradle'
DEBUG: ..got package=None, version=None, vercode=None
DEBUG: Parsing manifest at 'build/org.xbmc.kore/app/src/main/AndroidManifest.xml'
DEBUG: ..got package=org.xbmc.kore, version=None, vercode=None
DEBUG: Parsing manifest at 'build/org.xbmc.kore/app/build.gradle'
DEBUG: ..got package=org.xbmc.kore, version=None, vercode=26
DEBUG: Adding possible subdir app
DEBUG: fetch_real_name: Checking manifest at build/org.xbmc.kore/app/src/main/AndroidManifest.xml
DEBUG: ...got autoname 'Kore'
INFO: Finished
```
...so no autoupdate because [versionName is not static](https://github.com/xbmc/Kore/blob/master/app/build.gradle#L22) and F-Droid does not parse functions on checkupdate

**Comment by SyncedSynapse** [comment]
The thing is, it's been like that since ca5023bae789074ff9cf18e53c4c37799888beb4, which was merged 4 years ago, and there have been Kore releases on F-Droid since then.
Maybe something changed on F-Droid's mechanism that broke this? I'm not sure, as i don't have any visibility on it.

**Comment by licaon-kter** [comment]
I saw that, yes, not sure how it worked before.

**Comment by SyncedSynapse** [comment]
I see that you've already issue a PR on gitlab. I suppose that once that gets merged this gets fixed, right.

**Comment by licaon-kter** [comment]
Was merged, next cycle should build it.
https://f-droid.org/wiki/index.php?title=Special:RecentChanges&days=7&from=&hidebots=0&hideanons=1&hideliu=1&limit=500
