### ISSUE TITLE
Local download doesn't work anymore

### ISSUE THREAD

**Issue by Octoton** [xbmc/Kore#709]
### Describe the bug
Here is a clear and concise description of what the problem is:

Since version 2.5.0 (just got it up with f-droid) i cannot locally download my movie anymore.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Click on the download icon, get a system download notification and a file is created in the movie folder of my phone

## Actual Behavior

No system notification, but a empty serie/season/ folder is created on my phone movie folder.

### To Reproduce

1. Click on the download icon
2. Wait

 

### Your Environment
Used Operating system:

 - Mobile device: samsung galaxy A5 2017
 - Android version: 9
 - Kodi version and platform:  18.4, raspbian
 - Kore version: 2.5.0

**Comment by deafboy** [comment]
Same for the music downloads.

- Kore 2.5.0.26 on Pixel 3XL (Android 10)
- Kodi 17.6 on Ubuntu 14.04

**Comment by poisdeux** [comment]
This might be caused by plaintext data transfers which are by default denied since Android 8. Do you use HTTPS to connect to Kodi?

**Comment by Octoton** [comment]
I use http, i have tried activating ssl but it doesn't change a thing.
Local streaming is working but not downloading. In the previous version, there where no problem even on android 9.

**Comment by SyncedSynapse** [comment]
Something strange is going on... I can't download files either, but i get no error. I've tried to downgrade Kore to as far as 2.5 and it didn't work either...

@poisdeux  Is the download function working for you?
@Octoton  Can you confirm that with the previous version it was working correctly for you (a test would be nice).

**Comment by Octoton** [comment]
With he previous version posted on f-droid there where no problem, i was downloading stuff all the times.

**Comment by poisdeux** [comment]
The download was working for me and still works for the majority of files. 
But after doing some more testing with my [test media set](https://github.com/poisdeux/dummymediafiles) I finally stumbled upon an artist (Lloyd Green) that failed to download and get the above described behaviour.

From the Kodi 18.5 logs I get the following:

```
2020-02-29 20:50:13.216 T:123145478225920   DEBUG: CWebServer[8080]: request received for /vfs/%2fVolumes%2fSD%20Card%2fdummymediafiles%2fmusic%2fGreen%2c%20Lloyd%2fThe%20Little%20Darlin%27%20Sound%20of%20Lloyd%20Green%2f19-Seven%20Days%20Of%20Crying.mp3
2020-02-29 20:50:13.217 T:123145478225920   DEBUG: CUtil::GetMatchingSource: no matching source found for [/Volumes/SD Card/dummymediafiles/music/Green, Lloyd/The Little Darlin' Sound of Lloyd Green/19-Seven Days Of Crying.mp3]
```
But I get the same message for music files that I am able to download:
```
2020-02-29 21:11:51.202 T:123145478762496   DEBUG: CWebServer[8080]: request received for /vfs/%2fVolumes%2fSD%20Card%2fdummymediafiles%2fmusic%2fJay-Z%2fThe%20Black%20Chronic%2f01-Intro%20-%20Intro.mp3
2020-02-29 21:11:51.204 T:123145478762496   DEBUG: CUtil::GetMatchingSource: no matching source found for [/Volumes/SD Card/dummymediafiles/music/Jay-Z/The Black Chronic/01-Intro - Intro.mp3]
```

The only difference I can see now is the use of "weird" characters like `,` and `'`.

**Comment by SyncedSynapse** [comment]
@poisdeux Just a note: #715  helped somewhat, but didn't solved the issue for me. I still can't download successfully, but before #715 the download manager on my phone (which somehow is different than the standard one) indicated that there were errors downloading (no details), and now it just shows the files "queued" for ever...

Then again, this is the same behavior i got with previous versions, so it might be something specific to my phone... @Octoton  can you try this new version to see if it works for you? It should be available tomorrow at http://mirrors.kodi.tv/tools/kore/ (nightlies or test builds)

**Comment by poisdeux** [comment]
@SyncedSynapse did you enable downloads over all network connections (WIFI and mobile)? If not the download manager will queue the downloads and wait until the required network connection is available.

**Comment by Octoton** [comment]
@SyncedSynapse with the last build, it is working like a charm. Thanks
