### ISSUE TITLE
[Feature Request] Adding volume controls to remote screen

### ISSUE THREAD

**Issue by mribichich** [xbmc/Kore#718]
## Feature suggestion

**Detailed Description**

Adding/having the volume controls in the remote view (the one in the middle), next to the next, forward (the arrows). But not the same way like its being shown right now in the first screen.

![262645-como-usar-movil-como-mando-distancia-kodi2](https://user-images.githubusercontent.com/5748554/77073504-2c8f7500-69ce-11ea-94b5-d06a6ddf635b.jpg)

It would be awesome to have the minus and plus buttons of the volume, and even the bar to move it easily.

![262645-como-usar-movil-como-mando-distancia-kodi with vols](https://user-images.githubusercontent.com/5748554/77073548-3c0ebe00-69ce-11ea-9a28-1bbcb64f13e3.png)

### Context

I spend almost all the time in this screen. So everytime I want to change the volume with the app, to avoid using the phone buttons, I find my self going to the first screen.

Since I change a lot the volume, because of different movies or series, I fear that the phone buttons will break anytime.

So having them in the remote screen would be awesome.

**Comment by SyncedSynapse** [comment]
I'm not a fan of this, unless someone comes up with a design that is pratical and looks good on the first screen.
