### ISSUE TITLE
[feature request] Full control of add-ons

### ISSUE THREAD

**Issue by axelsimon** [xbmc/Kore#72]
Hi,

Ok, first of all, I realise this is likely to require a large amount of work, but I think it would be a very neat enhancement.
Instead of simply showing installed add-ons and taking you to the add-on's screen, it would be great if we could actually control the add-on from Kore.

The main problem I see is that there is no standardisation of how add-ons work and what they do. One solution could be to get add-ons to come with a mapping of their (main?) functions, which could be used by Kore to build the menus and send the events/requests.

As Kore is now the official Kodi remote, this might give us enough weight to suggest that add-ons need to now include this description which could be used to control them. That should probably be discussed with the main Kodi team.

As an example, here is an actual use case. I use the DI.fm app a fair bit, it's pretty simple: open add-on, add-on loads list of DI radios, I click radio, music magically appears.
This same could be done on Kore (go to add-ons, DI, see list of radio, select radio) avoiding having to turn the TV on just to listen to music.

Another use case is adding items to the playlist (say Vimeo or Youtube videos) while a video is already playing and thus using up the main display.

Anyway, I'd be interested in discussing this enhancement and your opinion on how feasible it is.

Cheers

axel

**Comment by SyncedSynapse** [comment]
With all the variety in add-ons i'm not sure it would be feasible to standardize a simple set of functions, but i'm not the best person to evaluate this.
In any case, i think that the primary site for discussing this shouldn't be here. You probably should post on the forum to gauge interest and feasibility from add-on developers.

**Comment by bromix** [comment]
I would just enable the navigation of an adoon like Yatse did. In Yatse you can navigate the current content of an addon. Nothing more - everything else would complicate things.

**Comment by SyncedSynapse** [comment]
@bromix what do you mean by navigation? Using the d-pad on add-ons? That's possible (if there are any issues with this it might have something to do with threads and TCP on Kodi, and the solution is to disable TCP in Kore).

**Comment by Razzeee** [comment]
![screenshot_2015-06-21-20-02-48](https://cloud.githubusercontent.com/assets/5943908/8272770/e97c824a-1850-11e5-91ab-2f0416832d1b.png)
Here is an example from the YouTube app. It seems to fetch the list items

**Comment by wp9015362** [comment]
> @axelsimon wrote:
> 
> Instead of simply showing installed add-ons and taking you to the add-on's screen, it would be great if we could actually control the add-on from Kore.

+1

That would be really nice.

Regards

**Comment by eisnerd** [comment]
I've been using Yatse to invoke add-ons and Kore for everything else. I'm considering implementing this. Has there been any discussion elsewhere?

Beyond the `Addons.GetAddons` call, the protocol seems to be just directory/file traversal with the special `plugin://` URI scheme. It may be fairly easy to adapt the Files/Playlists browser to this and even add them to Favourites.

**Comment by SyncedSynapse** [comment]
Yes, i believe you're right. With the `addonid` returned by `Addons.GetAddonDetails` we should be able to browse it using `Files.GetDirectory` with the directory being `plugin://addonid`.

2 things to consider:
1. I think this should be started from the Addon details screen, not from the Files section (going into that section to browse addons doesn't make much sense). Ideally, the FAB on the details screen would be a + sign that would reveal the Start (existing) and Browse options when touched. As a simpler alternative to implement, a new icon could be included on the icon row that starts the browsing.  The icon should be something from Google's material icons (https://design.google.com/icons/), svg in white 24dp. Can't seem to find something totally appropriate... maybe the "open in browser".

2. For addon navigation the logic in `FileListFragment` probably works, and should be reused, though it needs to be tweaked, as the path is somewhat different, and the back actions can't go all the way to the top (the fragment expects to be able to get back to "Sources", which doesn't make sense in this context). Haven't looked at it in detail though.

**Comment by eisnerd** [comment]
Thanks for your interest and help. UI-wise, I thought perhaps a tab like on TV Overview/Episodes might be suitable. I haven't seen the action button being used for accessing more navigation elsewhere. I would have thought it should be for actions like play/launch/enqueue, rather than opening a browse fragment.

You're right that the root/parent thing needs a little adjustment. The Sources stuff won't be invoked if the ".." entry is not it added, so the changes will be quite small.

**Comment by PanderMusubi** [comment]
Without doing anything special, my plugins work in Yatse where I can choose which item to play. In Kore this is indeed still not possible and without looking at the screen, I cannot start any item. So support for this is greatly welcomed.

**Comment by eisnerd** [comment]
Would you be able to give me an example plugin? I don't ask that to question what you said, just to save time. I don't use many plugins, but I've been able to play items straight from the menu in Kore, so I'm guessing that plugins differ in some way.

Thanks

**Comment by MartijnKaijser** [comment]
Addon browsing was added in upcoming version
