### ISSUE TITLE
Remove XBMC from interface strings

### ISSUE THREAD

**Issue by homocomputeris** [xbmc/Kore#720]
XBMC was renamed to Kodi almost [6 years ago](https://kodi.tv/article/xbmc-getting-new-name-introducing-kodi-14). Probably, no one is still using versions before 14 up to now.

Shouldn't "XBMC" be dropped from interface strings like this one? https://github.com/xbmc/Kore/blob/e24dcca1ce2e3349f014f898deb4eed786abac78/app/src/main/res/values/strings.xml#L81

**Comment by SyncedSynapse** [comment]
Sure, just send a PR.
