### ISSUE TITLE
port to webos, lg smart tv

### ISSUE THREAD

**Issue by jontis** [xbmc/Kore#723]
## Feature suggestion
Could Kore with reasonable effort be ported to run on Webos (lg smart tv)?

**Comment by SyncedSynapse** [comment]
You mean Kodi right, not Kore, which is just the remote app.

**Comment by jontis** [comment]
No, I do mean Kore. I want Kodi to run on my dedicated media box, and control it from the tv.

What I really would have wanted is for the LG magic remote to control Kodi too, but that seems far out of scope for now.

**Comment by SyncedSynapse** [comment]
Sorry, but porting Kore to another OS is so out of reach that it's not something i would consider.
