### ISSUE TITLE
Prevent notification from being swiped away

### ISSUE THREAD

**Issue by homocomputeris** [xbmc/Kore#726]
## Feature suggestion
**Detailed Description**
When something is playing, the notification can be swiped away. It would be great it wasn't possible to swipe it away while playing, similarly to VLC

### Context

When it's swiped from the notification drawer, one has to reopen Kodi from menu.

**Kore version** 2.5.0-13-g0d25fc9

*Note: Team Kodi will consider this item however we will not make any promises if it will be included.*

**Comment by homocomputeris** [comment]
Okay, it seems that the notification can be swept away only sometimes, so that's a bug then, not a FR.

**Comment by SyncedSynapse** [comment]
It's probably a bug of your Android implementation, as the notifications that Kore launches are supposed to not be swiped away, though each device manufacturer is "free" to change that behaviour.
