### ISSUE TITLE
Unable to play videos locally

### ISSUE THREAD

**Issue by dylanbob** [xbmc/Kore#733]
Hello
First of all, thank you for your amazing work.

### Describe the bug
Here is a clear and concise description of what the problem is:
Since this evening, I cannot play movies locally on my tablet using kore.
The movies are stored on an external hard drive plugged into my raspberry pi running kodi (move details below). I have been watching movies on my tablet for a few weeks and it used to work fine, but today I rearranged my directories and updated my libraries a few times and now I cannot watch movies locally anymore.
**I can still play the movies on my TV by browsing my movies library and starting the movie from my tablet.**
I tried on multiple movies and series including some I watched a few days ago.
I tried refreshing my library on my tablet and on kodi as well.
I tried rebooting my pi, my tablet, reinstalling kore.
I tried on another device : Nokia 7.1 (more details below).
I tried on VLC and the native video player of my tablet.
I tried disabling my web user password and reseting the access mode.
Note : I can still play movies using VLC by browsing my kodi from the VLC app directly, although I am not sure it is using the same protocol.

## Expected Behavior
Opening Kore, tapping on the hamburger menu then choosing Movies, tapping on any movie then the + sign below right then "Play Locally" button...
the movie should start on VLC on my android tablet

## Actual Behavior
I get on error message (see https://imgur.com/a/9he7eu7) which translates to : "The location "----------" cannot be read".
The movie doesn't play on my tablet.

### To Reproduce
1. go to the kore app on your android
2. tap the hamburger menu
3. tap on movies
4. tap on a movie
5. tap on the + sign below right
6. tap "Play locally"
7. cry

### Debuglog
I was not able to find kore logs.
I activated logs and all the specific logs and events on kodi but the error does not show up...

### Screenshots 
Error message : https://imgur.com/a/9he7eu7
Note : I am aware my password is shown. My kodi is not reachable from the Internet and this password is unique, so that is not a problem, I will simply change it afterward.

### Your Environment
Used Operating system:
 - Mobile device: Samsung Galaxy Tab S3 (/also tried and got the same problem on Nokia 7.1)
 - Android version: 9 (/10 on Nokia)
 - Server : Raspberry pi 4 running fully updated Debian 10 Buster
 - Kodi version and platform: kodi/testing,now 2:18.6-1~buster and running /usr/bin/kodi-standalone
 - Kore version: v2.5.0 (playstore's)

Hope you can help!
Regards

**Comment by poisdeux** [comment]
Thank you for your detailed report. This seems to be a problem that has already been fixed. You can get the latest development version from http://mirrors.kodi.tv/tools/kore/nightlies/ and see if that still has the issue you described.

**Comment by dylanbob** [comment]
Thank you for your very fast answer
I installed the latest version kore-20200411-0d25fc9-master.apk on my tablet as an update (without manually uninstalling first).
Now it works (yay!) with the native video player... but not with VLC?!
I tried rebooting the tablet.

Also, if I set my password back on Kodi AND kore, refresh my library ("sync succesful" : I guess it works then) and try to play a movie again locally on my tablet : nope, doesn't work! Not on the native video player ("You have been disconnected to the network"), not on VLC.

**Comment by dylanbob** [comment]
For some reason, it works fine on the Plex android app, even with the password on...
So, is that a problem with VLC and the Samsung native video player?

**Comment by dylanbob** [comment]
Also, downgrading to 2.5.0 and trying with the Plex app works fine, even with the password on.
So I wonder if it is an issue with VLC?

**Comment by dylanbob** [comment]
And now it works with the native video player and without a password too...
I don't understand what happened.

Recap, using playstore's version of latest nightly build:
Without a password:
- works with Plex, native samsung video player
With a password:
- works with Plex only

And it nevers work with VLC which I am used to.

**Comment by cpages** [comment]
I was going crazy since (I thought) this started to fail after I reorganized my kodi library. Playing on kore's local device also fails for me now with vlc (roughly translated: cannot play route http://server/vfs//path/to/film). I uninstalled vlc and worked smoothly. Maybe something has changed on vlc side?

**Comment by davidrg** [comment]
I have the same problem and it seems to be with how VLC handles the URL.

The error message I get when I try to play something locally (28 Days Later in this case) is "The location http://10.0.1.158:80/vfs//storage/titan_media/movies/28%20Days%20Later.mkv cannot be played.". If I open up VLC, choose the Stream option from the menu and enter the same URL I get the same error.

The Kodi wiki says everything after "vfs/" should be URL encoded. So the URL going to VLC really should be: http://10.0.1.158:80/vfs/%2fstorage%2ftitan_media%2fmovies%2f28%20Days%20Later.mkv

If I open up VLC, choose the stream option and put the properly URL encoded URL above in the video does indeed play just fine. So I guess the URL encoding is being stripped out when the URL is passed to VLC.

Now that the video has been played successfully in VLC it now appears in the recently played list:
![image](https://user-images.githubusercontent.com/1887527/83943545-31d3c180-a851-11ea-9a2e-0df08215bd88.png)
Attempting to play the video again from here just results in the same error as before. Note how the URL isn't as entered here - the %2F has been replaced with /. So probably its VLC that stripped out the URL encoding when passed the URL from Kore.

I guess this probably ought to be reported to the VLC folks as a bug but I don't know how likely they are to fix it if it were reported to them though.

**Comment by poisdeux** [comment]
Nice debugging. I don't think this is a VLC issue though. We didn't do proper URL encoding and 
PR #743 should fix this. I tested with VLC and some other players and seems to be working flawlessy.

**Comment by SyncedSynapse** [comment]
Yeah, it seems like it was a dumb error on our part. Nice find.

I'll try to push an update to Google Play soon.

**Comment by SyncedSynapse** [comment]
Closing this, as it should be fixed now
