### ISSUE TITLE
Auto detect system langeuage and use system language by default

### ISSUE THREAD

**Issue by princeofdream** [xbmc/Kore#738]
## Feature suggestion
**Detailed Description**

Detect system language and list system font, if system language is Chinese, switch UI language to Chinese by default. And each language support it's own font by default. And if we can use system fonts will be much better.

### Context

Many people download this soft and try to use it, but hard to read and event some media files name are encoded with their own language, so we find out we can not read the list of the media files.
Why can not support a better multi language UI and detect it by default? I think auto detect language and set it's UI will be a very easy way to use for users.

### Additional context, screenshots or links
Here are some relevant links or screenshots:

*Note: Team Kodi will consider this item however we will not make any promises if it will be included.*

**Comment by SyncedSynapse** [comment]
Not sure what you're referring to. Kore uses your device language by default, and offers a setting to change that to another language, so i think it covers this.

**Comment by princeofdream** [comment]
if kore use system language by default, then this is a bug in simple Chinese language windows. In simple Chinese windows, the ui are still in English, and fonts can not be configure to custom fonts. Please check it out.

**Comment by poisdeux** [comment]
Kore has not been translated to Chinese yet. If you would like to help translating it you can do so by joining transifex: https://www.transifex.com/teamxbmc/kore-android-remote/
