### ISSUE TITLE
Playlist always jumps to top (making it impossible to browse it)

### ISSUE THREAD

**Issue by bernd-wechner** [xbmc/Kore#739]
## Bug report
As per subject: Playlist always jumps to top (making it impossible to browse it)
## Expected Behavior
I expect to be able to browse the playlist.
## Actual Behavior (To Reproduce)
- Using Kore 2.5.0
- Enqueue a long music playlist (75 tracks is my typical and I use an addon to enqueue them)
- Playlist is populated and looks good
- Swipe up to scroll down the playlist examining what's on it (as my addon is a mix producer)
- Every second or so the view jumps back to top, making it impossible to browse the playlist
### Screenshots 
Can record a video of the behaviour if it helps. And provide link.

### Your Environment
 - Mobile device: Honor 9
 - Android version: Android 9
 - Kodi version and platform: 18.6
 - Kore version: 2.5.0

**Comment by poisdeux** [comment]
Thank you for the issue report. I've not been able to reproduce this issue. Does this also happen when creating a long playlist without using the addon? For instance, by simply selecting all songs from an artist from your library?

**Comment by bernd-wechner** [comment]
Thanks for getting back to me. I just tried. Admittedly I have a few other problems with Kore. For example I go to Music, then Albums, I see a load of entries, I add one to playlist and it's one song not an album. Hmmm. So I went o  Music and Artists, and scrolled down to find a prolific artist and click add to playlist and got  large playlist. Then wen to look at it and swiped down down down, paused and flip it went straight to top again. 

Very odd. If you don't see it and I do, it suggests an environmental trigger. So to explore that briefly:

1. I have Kodi running (on a HTPC on my LAN)
   a. It's not playing
   b. It's just on the home page
2. I added files to playlist on Kore using Music/Artists and "Add to Playlist" on a prolific artist
3. My phone is not "quiet"  as in other things are running on it (for example Blokada  is always running and Andoid is notorious for lingering background apps). So...
   a. I rebooted the phone
   b. I turned off Blokada (an ad blocker that watches network traffic)
   c. I killed all background apps (I used[ KillAll](https://play.google.com/store/apps/details?id=com.tafayor.killall))
   d. I started Kore and went to the playlist and swiped up to scroll down and ... it jumps to top again/still.
   e. So obvious interplay with other apps. Not a 100% sure test. But I ran KillAll angain after, and the only things it found running were Blokada, Facebook and Messenger. Interesting to see how tenasciously those last to autostart themselves. Blokada I expect as I ran it, to turn it off. It operates at the VPN level and to be sure it's off I turned it off. I can't for love or money imagine that it's URL based blocking could cause this behaviour but to be sure I turned it off.

Summary: Yes, it doesn't matter how I build the playlist. No I can't find any obvious environmental interplay. 

Which begs the question are there debugging options of any use (can Kore run in a debug mode that leave a log file? Even if I had to install a debug build?).

**Comment by poisdeux** [comment]
Are you by any chance using HTTP to connect to Kodi? 
I was able to reproduce your issue by changing the host configuration in Kore and deselect "Use TCP". Kore will then use HTTP to get data from Kodi and uses a 2 second interval. Every 2 seconds the playlist is retrieved and the UI updated. This resets the scroll position and thus the playlist jumps to the top.

**Comment by regagain** [comment]
I have the same problem. "Use TCP" is deselected (I tried selecting it to see if the issue still happens but for the some reason the setting isn't saved). This was not happening on earlier versions of Kore, although I am not sure on which version the issue first occurred.

**Comment by bernd-wechner** [comment]
> Are you by any chance using HTTP to connect to Kodi?
> I was able to reproduce your issue by changing the host configuration in Kore and deselect "Use TCP". Kore will then use HTTP to get data from Kodi and uses a 2 second interval. Every 2 seconds the playlist is retrieved and the UI updated. This resets the scroll position and thus the playlist jumps to the top.

Ingenious! I hadn't even seen that seeing (well long forgotten it as I'm sure I saw it when I first installed Kore ages ago and set it up). So took me a while to find it. But I turned on TCP and checked and alas the problem persisted. So I rebooted the phone, and thee problem is gone! I can browse! Yay! Makes the playlist useable. Brilliant insight.

I find that if I leave Kore (and do other things) then come back to it, it's popped back to top. But no big drama there. State between app use on Android is no guraantree. The main things I can browese the play list.

I'd stop short of close this as resolved, as I think while it's helped me enormously now , that is still technically a work around to a bug that does exist when not using TCP. We're just now, closer to nailing it as it's reproducible!

**Comment by bernd-wechner** [comment]
> I have the same problem. "Use TCP" is deselected (I tried selecting it to see if the issue still happens but for the some reason the setting isn't saved). This was not happening on earlier versions of Kore, although I am not sure on which version the issue first occurred.

As noted above I just tried and it was saved and persisted across a reboot too. I did click the Test button, which had oddly silent behaviour, as in it just closed that screen really didn't report anything positive or negative, so I inferred success (rightly or wrongly) but then as noted above I went to playlist and the problem persisted. Until I restarted my phone and it went away.

**Comment by poisdeux** [comment]
@regagain Kore tests if a direct connection using TCP can be made and if not falls back to polling over HTTP. This issue was introduced in 2.5.0 when we introduced showing available playlists on Kodi. In previous versions only active playlists would be shown and if nothing was playing the playlist screen would be empty.

@bernd-wechner indeed we can keep this issue open to solve the issue for HTTP connections.

**Comment by poisdeux** [comment]
Closing this as #740 has been merged to master. If the issue reappears please reopen this with any additional info.
