### ISSUE TITLE
Share video link from YouTube only works if Kodi is not already playing a video

### ISSUE THREAD

**Issue by DanhKE6D** [xbmc/Kore#74]
If Kodi is idle, share (Play on Kodi) will play the selected video as expected. While Kodi is playing, share another video does not work at all. Sometimes the playlist would queue the YouTube link, but this link would not be played when the previous video was completed.

**Comment by SyncedSynapse** [comment]
21c90438d052cd08cf8bad757e68a2c7dec35d33 probably fixes these issues. Could you please check it.

**Comment by petko10** [comment]
I'm having the same issue with the current android version of Kore (and Kodi 16.1-4, Manjaro). What info would be helpful for debugging ?

**Comment by SyncedSynapse** [comment]
If something is playing it queues the shared video. Check the playlist screen (swipe right from the remote screen).

**Comment by petko10** [comment]
I couldn't reproduce the issue after clearing the playlist from the songs that were currently playing (as in "It works now, thanks!" :D ) , but previously there was nothing playing either, I guess something had clogged the playlist without actually playing.
