### ISSUE TITLE
Music search results reset when moving to Remote and back

### ISSUE THREAD

**Issue by bernd-wechner** [xbmc/Kore#741]
### Describe the bug
The use case this disrupts badly is populating a playlist. To experience this

1. Search for a song using the Music menu
   1. Tap the **Menu** icon at top left
   2. Tap **Music** in the left bar menu
   3. Tap the **Songs**  menu item
   4. Tap the **Magnifying Glass** icon
   5. Enter an Artist's name say
   6. Observe that a list of songs by that artist are returned  
2. Add a song to the playlist
    1. Choose a song and tap the **3 dot** icon on the right
    2. Tap "Add to playlist"
3. Go look at the playlist
   1. Tap the **Remote** icon in the top right
   2. Left swipe to get to the Playlist view
4. Go back to Music
   1. Tap the **Menu** icon at top left
   2. Tap **Music** in the left bar menu
5. Notice that your search results are gone!

## Expected Behavior
I expect the search results to still be there so I can select another song and add it to the playlist, and in this workflow add mahy songs, go check the playlist, come back, add some more etc.

## Actual Behavior
Described above in the use case workflow.

## Possible Fix
Search results cached and remembered, so that when returning to the Music browser its state is as you left it (to examinge the playlist)

The same may apply to other browsers of course. But it's the Music playlist creation use case above that I notice disrupted. By comparison using the Chorus web interface I can browse and search and add songs and the playlist is always visible, there being no conflict in screen space. But I don't use it on the phone of course. The Kore app by comparison has limited screen space and so checking the playlist involves a screen switch as described on the  use case workflow.

### To Reproduce
Well covered above in presenting the use case.

### Your Environment
Used Operating system:
 - Mobile device: Honor 9
 - Android version:  Android 9
 - Kodi version and platform: 18.6
 - Kore version: 2.5.0

**Comment by bernd-wechner** [comment]
@SyncedSynapse, thanking you immensely! If you reference the commit here, that would be wonderful too, as it aids in lurkers (watchers, like me) learning a little as well. Thanks once more!

**Comment by bernd-wechner** [comment]
@SyncedSynapse, if you're active at all and don't mind, fixing this one would rock: https://github.com/xbmc/Kore/issues/805

It's a real frustration currently on long playlists.

**Comment by SyncedSynapse** [comment]
Just reopening this because i didn't meant to close it as solved.

I don't think this is an acceptable behaviour. When you change sections, no cached search should be set by default.

That being said, i believe you can alter your workflow slightly to achieve what you want: tap back when on the playlist to go back to the music section and the search should still be there. Using the menu to change to the music is a new workflow that starts with a clean state.
