### ISSUE TITLE
PVR channel icons not shown

### ISSUE THREAD

**Issue by heeplr** [xbmc/Kore#746]
### Describe the bug
Here is a clear and concise description of what the problem is:

Channel icons are not shown in the PVR channel list.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Previous versions of Kore showed the channel icon that has been configured in kodi.

## Actual Behavior

The first letter of the channel name is shown like when no icon is configured in kodi.

## Possible Fix

Sync channel icons from kodi.

### To Reproduce

1. Configure PVR channel icons in, so that they are shown in the list of the "TV" section in kodi.
2. Go to "PVR" section in Kore

### Debuglog

There is no debug output.

### Your Environment
Used Operating system:

 - Mobile device: SM-G930F (herolte)
 - Android version: 9
 - Kodi version and platform: Kodi 18.7 Git:20200608-nogitfound / gentoo
 - Kore version: 2.5.0

**Comment by anonimno1** [comment]
This is working on my side.
As soon as Kodi shows the icons, these are synced to Kore 2.5.0.

**Comment by heeplr** [comment]
@anonimno1 thank you.

I tried to reinstall kore. I also tried with a fresh kodi installation and I can see all channel icons I configured in kodi just fine, but not in kore.

Also, Album covers of music, fanart of movies and tv-series etc. all show correctly in kore.

Which settings affect this? Maybe I need to enable something specific for that?
Is there anything I could try to further debug this?

**Comment by stemy2** [comment]
@heeplr 
I have the same problem, did you found a fix?
