### ISSUE TITLE
Toggle to disable share to specific instance

### ISSUE THREAD

**Issue by mueller-ma** [xbmc/Kore#761]
## Feature suggestion
**Detailed Description**

On my device when I want to share a link there are four direct share targets and [two of them are taken by Kore](https://github.com/xbmc/Kore/issues/572) (Play on host and Queue on host). I'm using Kore with a single Kodi instance, so I don't really need these two targets, but rather have more space for other share targets, e.g. chats.
Therefore I suggest to add a setting to disable Kore's share targets.

### Possible Implementation

If I get an OK from you for this, I can propose a PR.

**Comment by poisdeux** [comment]
I'd say go ahead! :). I have no idea how to implement this so I'm very curious to your solution.

**Comment by mueller-ma** [comment]
#762
