### ISSUE TITLE
Favourites thumbnails

### ISSUE THREAD

**Issue by narcisgarcia** [xbmc/Kore#763]
### Describe the bug
When adding DailyMotion accesses to Favourites, Kore gets same thumbnail as Kodi shows.
But when choosing an image file to set or replace one favourite thumbnail, it's not got by Kore.
Example: Setting thumbnails to PVR channels that are added to Favourites.

Remote: Using Kore 2.5.1 on Android
Player device: Using Kodi 18.7 on Raspbian

**Comment by SyncedSynapse** [comment]
duplicate #765
