### ISSUE TITLE
Full remote for a full monitor

### ISSUE THREAD

**Issue by narcisgarcia** [xbmc/Kore#764]
I'm using Kore 2.5.1 from F-Droid.
The function to serve as interface works split between Kore client and Kodi screen: Some parts are listed in Kore (such as PVR channels, favourites list or plugins list) and deeper parts aren't, such as subcontents like plugins contents lists.

This means some times user must take care of actions on handheld screen and other times on Kodi screen. For this last user must switch Kore to "arrows mode".

There should be a compete mode to Kore does interface for everything, and Kodi only acts as a monitor of content being played.

This is important for these scenarios:
1. Making easy to have a near device that allows to read everything: Menus, lists, actions... And not needing to get up of the couch to approach TV screen with small letters.
2. Let spectators watch contents while Kore user is exploring or preparing next play.

**Comment by SyncedSynapse** [comment]
Too generic. Specific suggestions please
