### ISSUE TITLE
Support auto-dark mode.

### ISSUE THREAD

**Issue by xmha97** [xbmc/Kore#774]
Hello,
Please please support auto-dark mode. (like Aurora Droid):
![Screenshot_2020-11-26-21-14-32-077_com aurora adroid](https://user-images.githubusercontent.com/23485114/100380618-6bc99780-302c-11eb-8dbe-527467a5383d.jpg)
Thanks.

**Comment by SyncedSynapse** [comment]
Similar to #785 . Keeping that one as it has some more info
