### ISSUE TITLE
Feature Request: Properly support sendtokodi (youtube-dl resolving of random links in Kodi)

### ISSUE THREAD

**Issue by gerion0** [xbmc/Kore#776]
## Feature suggestion
**Detailed Description**
Since quite a time the addon [sendtokodi](https://github.com/firsttris/plugin.video.sendtokodi/) exists, that allows playback of nearly [every](https://github.com/ytdl-org/youtube-dl/tree/master/youtube_dl/extractor) video and audio site with help of youtube-dl. For this addons also an [Android app](https://play.google.com/store/apps/details?id=com.yantcaccia.stk) exists to request the playback from an Android device. However, since Kore already is an Android app for Kodi, I want to suggest to enable this functionality also in Kore if the addon is available in the connected Kodi instance.

### Context
I regulary facing the situation to search some nice presented website (for example Youtube, die öffentlich-rechtlichen TV sender sites in Germany, Reddit, some Podcast sites and Online radio streams) for a medium. If I have found a specific medium, I have scripted my browser (on the desktop PC) so it sends this link via one click to Kodi to present it to other people (better sound and bigger display). This is currently not possible with my smartphone.

I assume that other people want the same, see #737, #671, #318 (kind of similar to this request) and the sheer existence of the other android app.

### Possible Implementation
I'm not an Android developer, only a user. I would expect to have a "Send to Kodi" option via the share menu of Android.

**Comment by Upabjojr** [comment]
That's a great idea actually.

**Comment by axelsimon** [comment]
Just tried the app, it's terrible : you have to enter the IP manually (and there's an issue, so i had to copy-paste my Kodi box's IP address) **and** you have to manually paste the link you want to open in a box.
Kore could / should provide a much better alternative, the "stream to Kodi" function in NewPipe, from Firefox / Fennec is super useful.

**Comment by Upabjojr** [comment]
> you have to enter the IP manually (and there's an issue, so i had to copy-paste my Kodi box's IP address)

Do you mean the DHCP autodetect is not working on your WiFi?

> you have to manually paste the link you want to open in a box.

What do you mean? I just share the page from the browser through Kore, no need for copy-and-paste.
