### ISSUE TITLE
Resuming a video doesn't update the progress time

### ISSUE THREAD

**Issue by SyncedSynapse** [xbmc/Kore#78]
Through TCP, starting a video with a resume point doesn't update the progress time, it always starts at 0. 

Reported here: http://forum.kodi.tv/showthread.php?tid=227400

**Comment by SyncedSynapse** [comment]
The issue here is that calling `GetProperties` on jsonrpc through TCP, immediately after a video is started, always returns the `Time` as (near) 0, ignoring the video resume point.

The sequence of events is (calling jsonrpc through TCP):
1. Start a video that has a resume point, and select to start it from that resume point (note: this shows a dialog box on Kodi, which might be interfering with the TCP listener thread?);
2. Kodi issues a `Player.OnPlay` notification;
3. Kore gets the notification and *immediately* calls `GetActivePlayers` followed by `GetProperties` (with `Time` as one of the params);
4. The `Time` returned from `GetProperties` doesn't reflect the correct time of the video. It's not 0, the milliseconds field usually has some value, so it seems to be counting from the moment when the video was started (?), but it's not the correct time of the video (which should be with the resume time);
5. Subsequent calls to `GetProperties` return the correct `Time`;
6. If a slight delay is included before the first call to `GetProperties` (like 0.5s for instance), it returns the correct time, so this issue only occurs if it is called *immediately* after starting the video.

@Montellese do you have any insight into this? I can try working around this on Kore, though it will be ugly.

**Comment by Montellese** [comment]
I don't know the internals of the player either @FernetMenta might be able to give some insight here.

Are you asking for the current playback time only once and then only update the progress locally until the next notification or user interaction?

**Comment by FernetMenta** [comment]
does this apply to current master?

**Comment by Montellese** [comment]
According to the report this is with Kodi 14.0 Dec 12 2014 so no.

**Comment by SyncedSynapse** [comment]
@Montellese That's correct: if connected through TCP the remote only updates the info on a user action/notification/exit. Through HTTP it keeps polling kodi about what's playing (every 3s iirc), so this issue doesn't persist for long.

@FernetMenta I've tested it with the current master and it also happens.

I don't think this is something serious, but it is a curious one.

**Comment by FernetMenta** [comment]
the problem is that application wrongly interprets the return value of m_pPlayer->GetDisplayTime(). A value of zero means undefined. It takes some time for player to get started, during this time it returns zero.

**Comment by Montellese** [comment]
@FernetMenta: Why does the player execute the `OnPlaybackStarted()` callback if playback hasn't actually started yet. Because that's what JSON-RPC uses as a trigger to send the `Player.OnPlay` notification.

**Comment by FernetMenta** [comment]
Seems the definition of "playback started" is ambiguous. Playback has started but that does not mean that we have a first frame on screen.
