### ISSUE TITLE
Seek does not work with Kodi 19 Matrix

### ISSUE THREAD

**Issue by cpages** [xbmc/Kore#780]
Seek is not working from kore, with new kodi v19

I posted the issue in the kodi repo (https://github.com/xbmc/xbmc/issues/19084) but apparently it's kore's fault, using a deprecated rpc call that was just removed in the latest kodi version. The same problem was already fixed in the ios remote app: https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/95

**Comment by SyncedSynapse** [comment]
Thanks for the warning, it's indeed a bug on Kore's end. Will fix it as soon as i possible.

**Comment by daitj** [comment]
@cpages I have added a fix in #788 if you want to extend the work or just test it out.

**Comment by cpages** [comment]
I don't have the setup ready to build and test this, but thanks for taking care of it

**Comment by SyncedSynapse** [comment]
#789 fixes this, so i'm closing the issue. Soon i'll put an updated version on the Play Store.

**Comment by wkg** [comment]
> #789 fixes this, so i'm closing the issue. Soon i'll put an updated version on the Play Store.

f-droid please too

**Comment by ThiefMaster** [comment]
Looking forward to a fixed version :)

**Comment by ClausMM** [comment]
I'm also really looking forward to a fixed version ! Up to kodi v18 this was a very nice control option !

**Comment by ThiefMaster** [comment]
Looks like Kodi 19 is no longer RC but has been officially released. Time for an android update? :)

**Comment by wkg** [comment]
i can't wait ... compiled it with patch ...  https://fdroid.wmd.su/org.xbmc.kore_27.apk

**Comment by tomnor** [comment]
> > #789 fixes this, so i'm closing the issue. Soon i'll put an updated version on the Play Store.
> 
> f-droid please too

Agree, a version on fdroid would make it possible for me to enjoy this fix too. Or an apk asset here maybe?

**Comment by ThiefMaster** [comment]
The problem with a self-build apk (or an f-droid version instead of the play store version) is that I'd have to re-add all my Kodi instances... one at the TV at home, two at my parent's place, one on my desktop PC... not particularly fun. :)

**Comment by Dr-cell** [comment]
> Looks like Kodi 19 is no longer RC but has been officially released. Time for an android update? :)

**Comment by Dr-cell** [comment]
What you do take it no offer or anything  no working together

**Comment by tomnor** [comment]
Adrian ***@***.***> writes:

> The problem with a self-build apk (or an f-droid version instead of the play store version) is that I'd have to re-add all my Kodi instances... one at the TV at home, two at my parent's place, one on my desktop PC... not particularly fun. :)

But why would a build from f-droid not leave your settings intact though?

**Comment by ThiefMaster** [comment]
You cannot update an app unless the new APK has been signed using the same key as the already-installed version.

**Comment by wkg** [comment]
> You cannot update an app unless the new APK has been signed using the same key as the already-installed version.

Stupid android system

**Comment by ThiefMaster** [comment]
Kind of makes sense, otherwise someone could sideload a malicious app (or put a malicious app with the same id/name as a popular app on an alternative store) and steal the data already stored by the original app after tricking someone into installing it from there.

Anyway, this is probably going pretty off-topic...

**Comment by SyncedSynapse** [comment]
Sorry for the late reply. I'll post an updated version to Google Play asap (F-Droid will also pick it up).

**Comment by nebrunner** [comment]
@SyncedSynapse this is still broken for me, did this ever get updated on Google Play?  My Google Play is showing I have latest Kore installed.

**Comment by SyncedSynapse** [comment]
This was updated on Google Play recently. Check in Kore's settings->about if you're running v2.5.3.
If you are, what exactly is the issue you're having? This issue is related with the seek bar on the Now Playing page, maybe you're having other issues.

**Comment by Adonai** [comment]
F-Droid still has old version, there was no 2.5.3 tag in the repo.

**Comment by wkg** [comment]
yes, update metadata, please https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/org.xbmc.kore.yml

  - versionName: v2.5.3
    versionCode: 29
    commit: v2.5.3
    subdir: app
    gradle:
      - yes
    rm:
      - art/launcher/sam/concepts/Kore_App_Icons.zip

**Comment by nebrunner** [comment]
My Kore shows as latest version on Play store, when I check in Kore I have 2.5.3 but seek does not work.  I am on a Fire 7.

**Comment by maretodoric** [comment]
Hello. Also on 2.5.3, kodi matrix 19.2, seek doesn't work. When i pause the video and after some time the video information kicks in, i try to seek and it goes away from video info like it accepted something, but it's still not seeking.

**Comment by SyncedSynapse** [comment]
@maretodoric This issue was related to the seek bar on the "Now playing" screen, not the arrows on the Remote screen.

Regarding your issue, i think it has to do with the way you're connected to Kodi: In Kore, open the left side bar, tap Kodi's name and check the parameters for the connection. I believe that you expect to have the "Use EventServer" checked and it isn't.
