### ISSUE TITLE
Switch theme based on system preference

### ISSUE THREAD

**Issue by Mynacol** [xbmc/Kore#785]
## Feature suggestion

Kore could check the system-wide preference for dark theme/mode and select a light/dark theme accordingly.

### Context

[Since Android 10](https://developer.android.com/guide/topics/ui/look-and-feel/darktheme), users can use a system-wide dark mode toggle. This helps with eye strain at day and night.

### Possible Implementation

As Kore has multiple themes, a selection menu for both light and dark mode would be nice.
Alternatively, we could "sync" light and dark themes so only the background color and text is switched, but the contrast/2nd colors stay the same. Then a simple toggle to switch on/off auto-switching themes is sufficient. The existing theme picker will allow users to select one theme that is used (with a light and dark variant).

**Comment by SyncedSynapse** [comment]
Done.
