### ISSUE TITLE
Allow to choose download location

### ISSUE THREAD

**Issue by romainsc** [xbmc/Kore#798]
## Feature suggestion
**Detailed Description**
Kore downloads files in the local/internal storage “music” directory. I would be useful to be able to set another directory, for instance one on the external SD storage.

### Context
This possibility is valuable as the internal storage is often limited and already consumed by app.
A possible workaround to this storage shortable is the usage of the SD card as an internal storage extension but this will not allow it to be used for something else and with the latest version of Android, the extension scheme have a strange behavior.

### Possible Implementation
I think being able to set the directory in the settings would be enough.

**Comment by SyncedSynapse** [comment]
Closing this, as considering Android's restrictions on file downloads, this doesn't look feasible.
