### ISSUE TITLE
Add option to enter text using QWERTY keyboard when in remote control mode

### ISSUE THREAD

**Issue by mvglasow** [xbmc/Kore#799]
## Feature suggestion
**Detailed Description**

When I am using the remote control to change settings, I would like to be able to use Android’s keyboard features (either the on-screen keyboard or a hardware keyboard, if the Android device has one) to enter text.

### Context

As I usually do not have any input devices hooked up to my media center, entering text in settings (or elsewhere) is currently a pain. Basically I have two options:

* With Kore: Essentially, I have to navigate an on-screen keyboard with the directional pad of the remote control, which is a pain in the rear.
* With a CEC-capable television and a remote with a numeric pad: text can be entered with the numeric pad the way we would write text messages on our cell phones 20 years ago. Somewhat better than the above, but still with a lot of room for improvement, and not always available (some devices are not CEC capable, e.g. computer monitors, or may not have a numeric keypad on the remote).

As a side effect: Entering long or otherwise complex passwords is a particular pain and error-prone, which gives people an incentive to choose easily guessable passwords. An improved keyboard UX would avoid punishing people for choosing safe passwords.

### Possible Implementation

If a hardware keyboard is available, any keypress should be passed through to Kodi when in remote control mode, making the keyboard behave much as if it were directly connected to the Kodi system (maybe with the exception of keys that have a function in Kore itself). Otherwise, an extra button could be added to the remote UI, which brings up the on-screen keyboard. Again, any key pressed on the on-screen keyboard should be passed directly to Kodi.

### Additional context, screenshots or links
Here are some relevant links or screenshots:

(none at this time)

*Note: Team Kodi will consider this item however we will not make any promises if it will be included.*

**Comment by SyncedSynapse** [comment]
The keyboard appears automatically when needed, as long as you are connected through TCP - check the connection settings in Kore and make sure that you're using TCP.

If that isn't possible, you can always tap the three dots menu on the top right corner on the remote screen and choose "Send text to media center" which will open the keyboard to send the text to Kodi.

**Comment by mvglasow** [comment]
In fact, I had overlooked that one, thanks for the pointer :-)

However, would it be feasible to implement a default pass-through mode (as described above) for a physical keyboard whenever Kore is in remote control mode, without having to go through the menu item?
