### ISSUE TITLE
Add playlist support

### ISSUE THREAD

**Issue by mvglasow** [xbmc/Kore#808]
## Feature suggestion
**Detailed Description**

Kodi supports playlists for music and for music videos. Currently there is no way to browse and play them directly from Kore – one has to select them from the Kodi UI. It would be great if this functionality were available directly from the Kore UI.

### Context

I would be able to play any playlist stored in Kodi from Kore, without having to switch on my media center screen (or even be in the same room).

### Possible Implementation

Kodi’s web UI has playlists in the Browser tab, which otherwise is very similar to the File Browser tab in Kore. Main difference is that the web UI has not only file sources, but also others such as YouTube for videos, or playlists for both music and videos.

The web UI allows the user to enqueue a playlist in Kodi, or to browse it. When browsing a playlist, the user can play the files, enqueue the files, or select individual files to play in Kodi or download.

Placing this functionality in the (file) browser may not be perfect UX (I would have put it in the neighborhood of what the playlist contains, i.e. music and music video), but it would at least be consistent with the web UI. Otherwise, the functionality offered by the web UI is a good reference for implementation in Kore.

### Additional context, screenshots or links
Here are some relevant links or screenshots:

No links – if you have a functioning Kodi instance, insert a link to its web interface here :-)

*Note: Team Kodi will consider this item however we will not make any promises if it will be included.*

**Comment by WolfgangKnobloch** [comment]
Would like to see this feature added as well
and like to offer support on developing, albeit I have no recent coding experience etc.
But I could do other things like specifying, reviewing, testing etc

I agree with the view that playlists should be accessible like in the main Kodi App, i.e. with content types, e.g. Music, Video, etc... 
I think it would be fine to start capability to select and play as a first step. Edit, download, etc could come later.

**Comment by SyncedSynapse** [comment]
Duplicate #668

**Comment by WolfgangKnobloch** [comment]
Agree that it is a duplicate. 

Do I understand correctly, that the requirement itself is however not closed yet, as 668 ist still in Open state?
Has there been any movement around it?
I repeat my offer to support e.g. with testing reviewing etc.

**Comment by SyncedSynapse** [comment]
Yes, it's not closed, but there are no news.
