### ISSUE TITLE
[Feature Request] Need Favorites in menu

### ISSUE THREAD

**Issue by gvkt** [xbmc/Kore#81]
Don't know if this is possible.

It would be useful to have a Favorites menu item in the menu panel to bring up Kodi Favorites in one tap. If possible, displaying the Favorites list on Kore itself would be ideal (especially for no-display use for Audio) but this may be difficult to do.

Perhaps there is a workaround I am not aware of.

**Comment by juup** [comment]
I'm interested in the same feature. Would be nice to control radio (plugin) with it.

**Comment by micressor** [comment]
+1 for this feature!

**Comment by jponzo** [comment]
+1!

**Comment by jp438** [comment]
I would be very interested in this feature for the purposes of radio as well! +1

**Comment by SyncedSynapse** [comment]
Unfortunately there are some issues with this. It is possible to open the favorites window on Kodi, but after being opened it isn't possible to dismiss it using the remote. I'm not sure, but i believe this is related to a known issue with threading on Kodi.

Given this, introducing a favorites button on the remote isn't really helpful, as it will lead to a situation where the user gets stuck.

**Comment by jp438** [comment]
Thanks for the reply! Would it maybe be possible to sync the contents of the favourites menu with Kore so that it can start media directly outside the Kodi interface. (Just like you can browse your library entirely on Kore and select something to play without having to navigate Kodi's menus)

**Comment by SyncedSynapse** [comment]
I guess something along those lines could be done, not sure how well if it would work though. Keeping this open.

**Comment by dzsodzso63** [comment]
So +1 for this 
Sync favorites or if not possible, maybe a separate favorites menu for kore app separately 
Quite a problem if you use a deep menu item a lot (E. G. in a plugin)

**Comment by wstephen** [comment]
Yes +1
The movies, tvshows, musics shortcuts on the Navigation Drawer are so great. But, the Kodi's Favorite Button (the Star Button) is so difficult to be reached by Kore Remote.

Understand that reasons for features such as TV Channel Switching, recording are strong and valid, developers may be hammering how to make a good room in the tiny screens of our mobile. However, I strongly suggest the team should consider making Kodi Favourite Shortcut available on the Navigation Drawer just like what they've done to movies and tvshows.

Kodi Favorites can store TV Channels with logos, and it can store a myriads of Kodi addons and programs. It allows renaming too. How can Kore not availing this feature in its remote function?

Please, please consider! Imagine the degree of convenience and how pleasant it will look.

**Comment by unalterable** [comment]
+1 for this feature. It would be very helpful for providing hotlinks for kore, so do you can jump to parts of plugins that can be hard to navigate to with the remote.

**Comment by R4md4c** [comment]
Hello, I'm interested in implementing this feature as I use Kodi daily and would like to have this feature inside Kore. 
There is a [Favourites API](http://kodi.wiki/view/JSON-RPC_API/v6#Favourite) included in v6 API, can't we just it that to retrieve the Favourites without syncing and handle it as we are handling the PVR section?

**Comment by SyncedSynapse** [comment]
@R4md4c I guess so, though i'm not sure what `Favourites.GetFavourites` returns, or what can be done with it (starting them?) but i think it's worth a try.
Note that, even though the documentation doesn't mention a `Favourites.GetFavourites`, there's one. Take a look at the result from introspect (available at `\doc\json_responses\Instrospect...json`) to check the details.

**Comment by R4md4c** [comment]
@SyncedSynapse I'm currently retrieving info from the `Favourites.GetFavourites` API, but I don't see any ID that could identify a favourite item so that I could execute an action on it, for example if I have a favourite item with type "window", I can't use the `GUI.ActivateWindow` on that item to activate its window  in Kodi. Do you have a workaround for that since you are more verse with Kodi's API? or am I missing something?

Here is a sample of the JSON response I'm getting from that endpoint.
```
{
  "id": 71,
  "jsonrpc": "2.0",
  "result": {
    "favourites": [
      {
        "title": "AR:ART_Aflam1",
        "type": "media"
      },
      {
        "title": "AR:BEIN_SPORTS_1HD",
        "type": "media"
      },
      {
        "title": "AR:BEIN_SPORTS_2HD",
        "type": "media"
      },
      {
        "title": "[B]Playlists[/B]",
        "type": "window"
      },
      {
        "title": "Popular Videos - Tom and Jerry",
        "type": "window"
      },
      {
        "title": "tom and jerry 1950 full episodes",
        "type": "window"
      },
      {
        "title": "Tom and Jerry & Fred Quimby",
        "type": "window"
      }
    ],
    "limits": {
      "end": 7,
      "start": 0,
      "total": 7
    }
  }
}
```

**Comment by SyncedSynapse** [comment]
What's your request like? You probably need to specify the `properties` field (inside the `params`).
Maybe using:
`
"params": {
    "properties": ["window", "windowparameter", "thumbnail", "path"]
}
`

returns more info.

**Comment by R4md4c** [comment]
@SyncedSynapse Thanks it is working now, and I'm able to activate windows with the help of windowparameter.

Here is an example of a media type Favourite Item that is been favourited from the PVR.
```
{
      "path": "pvr://channels/tv/All channels/pvr.iptvsimple_1756997637.pvr",
      "thumbnail": "AR:BEIN_SPORTS_1HD",
      "title": "AR:BEIN_SPORTS_1HD",
      "type": "media"
    },
```

As you can see I only have a path, but it doesn't seem that the `Player.Open` API endpoint can be used with these kind of Uris, Is there another endpoint that could resolve these kind of URIs? Any advice regarding how to resolve them into playlist id or a channel id?

**Comment by SyncedSynapse** [comment]
No idea, though i would try to use `Player.Open` to see if it works. Even if it doesn't work with PVR links it might work with other types.

@Montellese Can you provide some insight on this (how to play items returned by `GetFavorites`)?

**Comment by R4md4c** [comment]
@SyncedSynapse I've followed this [thread](http://forum.kodi.tv/showthread.php?tid=198738&highlight=Youtube), and tried the `Player.Open` with `{item: { file: "<youtube_path>" } }` and it works!
Will have to experiment with other media types though.

**Comment by SyncedSynapse** [comment]
Closing this as it will be available in the next version

**Comment by j13ag0** [comment]
Thanks for adding this feature.
I'm running the KORE remote on a  Nexus 6.  When I go to the Favorites entry on the menu I get a list of things that I have favorited in Kodi.  
The difficulty is that they are inert.  No actions happens when I tap one. They don't play.
My favorite are all Music / albums.

Am I missing something ?

cheers
-jg-

**Comment by narcisgarcia** [comment]
I'm using Kore 2.5.1
What about bottom menu?

**Comment by narcisgarcia** [comment]
I'm using Kore 2.5.1
What about bottom menu?
