### ISSUE TITLE
[Feature Request] Need a Go Home Button on remote

### ISSUE THREAD

**Issue by gvkt** [xbmc/Kore#82]
Don't know if this is possible, but it will be useful to have a go to Kodi Main Screen button on remote (like Esc key on keyboard) which will dismiss all overlays and popups on Kodi and get back to Home Screen on Kodi.

Very useful, especially in display-less use of Kodi for Audio. The remote becomes unresponsive if there are some unintended popups or overlays on Kodi (for example, New Media Detected popup that requires a manual dismissal) and without a display it is difficult to know what the situation is.

The current work around is to do a number of back key taps until the remote starts responding.

**Comment by axelsimon** [comment]
Doesn't the Home icon on the bottom left of the main Kore remote screen do that?
In any case, I agree getting out of layers of popups, lyrics and music visualisation can sometimes be a pain. If the home button doesn't do that, then I'll add my vote to this :)

**Comment by gvkt** [comment]
It goes to the Home Screen but will not dismiss any popups that may be up. It may be a limitation of Kodi API but a klutzy workaround would be to send a couple of back commands first in any case and then send Home when the Home on the Kore tool bar is tapped.
