### ISSUE TITLE
'Play Locally' doesn't work when SSL is enabled

### ISSUE THREAD

**Issue by SeaMonkey82** [xbmc/Kore#823]
### Describe the bug
Here is a clear and concise description of what the problem is:
When SSL is enabled, 'Play Locally' passes the link with http:// instead of https://

## Expected Behavior
Here is a clear and concise description of what was expected to happen:
If SSL is enabled, 'Play Locally' should pass https://

## Actual Behavior
When SSL is enabled, 'Play Locally' passes the link with http:// instead of https://

## Possible Fix
Pass https:// when SSL is enabled

### To Reproduce
1.  Enable SSL in Kodi
2.  Attempt to 'Play Locally' in Kore

### Your Environment
Used Operating system:
 - Mobile device: Samsung Galaxy Note 9
 - Android version: 10
 - Kodi version and platform: 19.3.0 x86_64
 - Kore version: 2.5.3

**Comment by SyncedSynapse** [comment]
I believe this was fixed in #834 so i'm closing it.
If not, please reopen.
