### ISSUE TITLE
MAC address not saved when modifying a multimedia center

### ISSUE THREAD

**Issue by djelouze** [xbmc/Kore#824]
### Describe the bug
Here is a clear and concise description of what the problem is:

In order to use WOL from my smartphone (OnePlus + LineageOS), I modified an existing but offline multimedia center (MC) by adding its MAC address. Once done, the only options was "Cancel" or "Test". Then I tapped on "Test", which obviously returned an error (as offline). 

Then I switched on the MC, went back into "Modify" in Kore for this MC, and saw that the MAC address was not set.

Setup again -> "Test" -> test ok -> but WOL was not functioning.

"Modify" again -> MAC address not set !

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Once the MAC address is set, either offline or online, the MC settings on Kore should be kept.

## Actual Behavior

The MAC address is not saved when manually modifying an existing MC.

## Possible Fix

Here is a workaround : modifying the name of the MC *AND* the MAC address fixed the issue.

### To Reproduce

1. Add an MC with automatic setting
2. Modify the MAC address and validate
3. Go back to "Modify" the MC

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

WOL was not working, while the MC was accepting the wake up from other remote software.

### Your Environment
Used Operating system:

 - Mobile device: OnePlus A5000
 - Android version: v11 (LineageOS)
 - Kodi version and platform:  v19.3
 - Kore version: v2.5.3
 

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by SyncedSynapse** [comment]
When the Media center is offline, any changes made aren't saved, as they couldn't be checked. That includes the Mac Address.

When the MC is online and you specify a valid Mac Address, it is saved correctly (just tested). Wether it can be used to WoL is another thing, as the MC might not respond to the WoL packed.

When no Mac Address is specified, it currently can't be obtained automatically, given Android's security restrictions, so for WoL to work you need to manually specify the Mac Address, in an online MC.
