### ISSUE TITLE
[Question] How to contribute to add a translation? 

### ISSUE THREAD

**Issue by sidealice** [xbmc/Kore#83]
I would like to contribute Chinese locale for the remote. But don't know how to add and where to request.

**Comment by sidealice** [comment]
understand how to contribute this already. thanks

**Comment by older** [comment]
Just in case anyone is looking for the answer. To add a translation - send pull request with 
`/app/src/main/res/values-[locale name]/strings.xml` file translated to your language.

But is it possible to integrate Kore translations into Kodi translation project at transifex?

**Comment by SyncedSynapse** [comment]
It's being worked on.
