### ISSUE TITLE
Video VIEW intents not received for most hosts

### ISSUE THREAD

**Issue by cemrich** [xbmc/Kore#830]
### Describe the bug
Kore does not accept all video urls with explicit "video/*" mimetype on Android 12.

For example, if i send `am start -a android.intent.action.VIEW -d https://example/video.mp4 -t video/*` via adb shell (or share the corresponding intent from another app), Kore shows up just fine in the list of receiving apps.

If I however send `am start -a android.intent.action.VIEW -d https://example.net/video.mp4 -t video/*` (note the added domain), Kore does not show up as receiving app.

## Expected Behavior
Kore should be able to receive any url to view with explicit "video/*" mimetype, regardless of its host.

## Actual Behavior
Kore does not get listed as receiving app for VIEW intents with explicit "video/*" mimetype for some hosts.

## Possible Fix
I suspect the [`<data android:host="*" />`](https://github.com/xbmc/Kore/blob/b9ad95ad9ade5e0904ba0abb66af976471007b99/app/src/main/AndroidManifest.xml#L49) section in the manifest file does not work as expected.

Documentation: https://developer.android.com/guide/topics/manifest/data-element#host

### To Reproduce
Steps to reproduce the behavior (on a machine with ADB and connected device) :
1.  `adb shell`
2. `am start -a android.intent.action.VIEW -d https://example.net/video.mp4 -t video/*`

### Your Environment
Used Operating system:
 - Mobile device: Focophone F1
 - Android version: Lineage 19.1 (Android 12)
 - Kodi version and platform: -
 - Kore version: v2.5.3

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

Thank you!

**Comment by SyncedSynapse** [comment]
Closing this, as you fixed it in #831
