### ISSUE TITLE
Sorting should ignore Articles (i.e The, A, An)

### ISSUE THREAD

**Issue by delphiactual** [xbmc/Kore#87]
as described

**Comment by SyncedSynapse** [comment]
There's an option to ignore the articles (prefixes) in the sort menu.

**Comment by delphiactual** [comment]
Thank you, I was looking under settings for sorting options, I didn't try the menu on each of types.
2 sorting issues i discovered "iZombie" is erroneously at the end due to sorting based off ASCII value. And "The 'Burbs" is sorted into apostrophe instead of B...
Thanks for your consideration
