### ISSUE TITLE
Sorting Irregularities

### ISSUE THREAD

**Issue by delphiactual** [xbmc/Kore#88]
2 sorting issues i discovered "iZombie" is erroneously at the end due to sorting based off ASCII value. And "The 'Burbs" is sorted into apostrophe instead of B...
Thank you for your consideration

**Comment by SyncedSynapse** [comment]
This issue and #105 are similar, so i'll close this one as #105 has more info.

I get that this might not be about the music section, but the issue is transversal to all lists.
