### ISSUE TITLE
feat: Material 3

### ISSUE THREAD

**Issue by FieryMewtwo** [xbmc/Kore#911]
## Feature suggestion
**Material 3 theming and UI**

Material Design UI and Material You elements and theming across Kore.

### Context

I really like the way Kore works, but it really stinks that, compared to most other apps on my phone, it looks kinda dated and out of place. I think Kore should have a Material 3 UI (make it optional, though!) with theming and whatnot.

### Additional context, screenshots or links
Here are some relevant links or screenshots:

*Note: Team Kodi will consider this item however we will not make any promises if it will be included.*

**Comment by SyncedSynapse** [comment]
yeah, closing.
