### ISSUE TITLE
Non-FOSS in F-Droid build

### ISSUE THREAD

**Issue by licaon-kter** [xbmc/Kore#912]
c728508ad65a03c24b65c6b6794a438f223c6a1c

```
$ gradle :app:dependencies --configuration releaseRuntimeClasspath
...
+--- androidx.core:core-google-shortcuts:1.0.1
|    +--- com.google.firebase:firebase-appindexing:20.0.0
|    |    +--- com.google.android.gms:play-services-base:17.5.0
|    |    |    +--- com.google.android.gms:play-services-basement:17.5.0
|    |    |    \--- com.google.android.gms:play-services-tasks:17.2.0
|    |    |         \--- com.google.android.gms:play-services-basement:17.4.0 -> 17.5.0 (*)
|    |    +--- com.google.android.gms:play-services-basement:17.5.0 (*)
|    |    \--- com.google.android.gms:play-services-tasks:17.0.0 -> 17.2.0 (*)
```
ref: https://github.com/xbmc/Kore/blob/v3.0.0-beta.1/app/build.gradle#L106

**Comment by licaon-kter** [comment]
Think we can, for now, exclude gms at build time:
```
    implementation('androidx.core:core-google-shortcuts:1.0.1') {
        exclude group:'com.google.android.gms'
    }
```

Can somebody test this APK? https://gitlab.com/fdroid/fdroiddata/-/commit/4a42435346fda40ab37978bc65e71b8195b88ce8#note_1108571409

Is GMS used elsewhere too? Could I PR such a change here directly?

**Comment by SyncedSynapse** [comment]
Play services aren't used in Kore, didn't think they would be dragged by the shortcuts library...

I'm obviously not sure if excluding that breaks something internally on the shortcuts library, but PR this and i'll make some tests.

**Comment by SyncedSynapse** [comment]
Closing this as it will be managed through the pr

**Comment by woheller69** [comment]
why is `exclude group:'com.google.android.gms` not a fix?

**Comment by licaon-kter** [comment]
Because the lib was build from non-FOSS deps, so it's non-FOSS.

**Comment by woheller69** [comment]
If I remove the whole thing 

```
    implementation('androidx.core:core-google-shortcuts:1.1.0') {
        exclude group:'com.google.android.gms'
    }
```

it still builds and works. What is the dependency used for?

**Comment by licaon-kter** [comment]
You've removed the Firebase deps from https://github.com/androidx/androidx/blob/9aafaf4e78e5e8a58db27b08c251f12797cc1f88/core/core-google-shortcuts/src/main/java/androidx/core/google/shortcuts/ShortcutInfoChangeListenerImpl.java#L35 and https://github.com/androidx/androidx/blob/9aafaf4e78e5e8a58db27b08c251f12797cc1f88/core/core-google-shortcuts/build.gradle#L38 and you can build shortcuts? That would be nice

**Comment by woheller69** [comment]
no, I removed the whole implementation('androidx.core:core-google-shortcuts:1.1.0')... from Kore build gradle and it still builds

**Comment by licaon-kter** [comment]
That's one way to go at it.

It isn't used then? What is going on? :) :)

**Comment by woheller69** [comment]
yes, obviously it is not used. Just remove the whole line in pre-build...

**Comment by woheller69** [comment]
I wanted to see where it is used and simply removed the dependency. Usually Android studio would show red lines where it is needed. Nothing happened. Also a clean build worked and it runs :-)

**Comment by licaon-kter** [comment]
Will amend recipe then, thanks

**Comment by licaon-kter** [comment]
:tada: thanks @woheller69

**Comment by woheller69** [comment]
Also created a PR here to remove it #1005
