### ISSUE TITLE
Share youtube video not playing

### ISSUE THREAD

**Issue by MichaelMackus** [xbmc/Kore#917]
### Describe the bug
Here is a clear and concise description of what the problem is:

Playing youtube videos with kore no longer works. The app is setup correctly and I can conrol kodi with it, but sharing youtube links do not work.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Click share on youtube video, then "play on kodi"

## Actual Behavior

Opens kore app and shows "nothing playing". I'm still able to otherwise control kodi.

**Comment by MichaelMackus** [comment]
Also I can play youtube fine on kodi this issue is only with kore. I am using kodi v19.4 and kore is up to date

**Comment by SyncedSynapse** [comment]
This should be the issue fixed in #915 , which will be available soon, so i'm closing this. If it isn't, please reopen.

**Comment by juup** [comment]
It's still not working in v3..0.0 for me.
