### ISSUE TITLE
"Show Now Playing" sometimes ignored

### ISSUE THREAD

**Issue by heeplr** [xbmc/Kore#927]
### Describe the bug
Although the "Show Now Playing" option is disabled in the settings, the PVR channel list still contains a dragabble section at the bottom. (Same for Music section)

## Expected Behavior
Show nothing on the bottom of channel list, when the option is disabled.

## Actual Behavior
Sometimes a draggable section is still shown

### To Reproduce
1. Disable "Show Now Playing" in settings 
2. go to Music section or PVR Channel list
3. start playback
4. switch views & come back
5. kill app
6. go to Music/PVR section again

### Screenshots 
Everything fine, when the setting is enabled:
![Screenshot_20221019-181224_Kore](https://user-images.githubusercontent.com/32984777/196747863-0a31eb45-4059-4de8-ae37-63fb42a0a364.png)

When setting is disabled, sometimes the "Now Playing" section is correctly disabled, as expected:
![Screenshot_20221019-181143_Kore](https://user-images.githubusercontent.com/32984777/196748127-68915d26-caa2-40a9-8caa-65ed21774819.png)

But sometimes, the section is still shown:
![Screenshot_20221019-181327_Kore](https://user-images.githubusercontent.com/32984777/196748427-4c9e662a-7e9e-4dd5-9557-9182781ed0cd.png)

### Your Environment
Used Operating system:
- Mobile device: SM-G930F
- Android version: 11
- Kodi version and platform: 19.4
- Kore version: v3.0.0

**Comment by SyncedSynapse** [comment]
This is indeed a bug that i didn't catch, but i'm aware of it and plan to fix it soon

**Comment by SyncedSynapse** [comment]
fixed in #931
