### ISSUE TITLE
Please re-open #80 for discussion

### ISSUE THREAD

**Issue by gvkt** [xbmc/Kore#93]
Odd to close it immediately after a comment expressing an opinion. Why not allow for a discussion or wait a day or two at least to see if there are any comments on the latest comment before closing it? Less autocratic way to run things no? :-)

I have added a comment to that issue #80 to provide further feedback. 

In any case I have provided as much input as I have so up to you what you do with it.

**Comment by MartijnKaijser** [comment]
opening a ticket for opening a ticket is just wrong
