### ISSUE TITLE
Can't connect using wildcard certificate

### ISSUE THREAD

**Issue by diegombeltran** [xbmc/Kore#930]
### Describe the bug
I'm unable to connect to my Kodi instance using TLS and user authentication. The certificate is a wildcard *.domain.xyz signed by Let's Encrypt CA. Works flawlessly in Firefox (Desktop and Android). It also works with Yatse client, though it warns the user the certificate is not valid (I think this is because it's a wildcard certificate) 

Plain HTTP works as expected.

## Expected Behavior
I should be able to log in to the Kodi instance with Kore.

## Actual Behavior
Kore says "Unable to connect to XMBC/Kodi"

## Possible Fix
Message asking the user if he trusts the certificate as a workaround.
Be able to connect to instances with wildcard certificates.

### To Reproduce

* Wildcard certificate signed by Let's Encrypt (server.pem and server.key in the Kodi userdata folder as expected)
* User and pass set up
When trying to connect using Kore, it fails with a "Unable to connect to XMBC/Kodi" message.

### Screenshots 
I rather not posting them as they contain my instance name and domain.

### Your Environment
Used Operating system:
* Kodi Matrix 19.5
* Libreelec 10.0.3 on Raspberry Pi 4
* Android 12 (LineageOS 19.1)
* Kore 3.0 from F-Droid

**Comment by basilgello** [comment]
You are getting this issue because the certificate alone is not trustable. What makes the cert trustable is its path to one of trusted root certoficate. You need to include intermediate LE certificates in your `server.pem` on Kodi side by using LE's `fullchain.pem`: `cat fullchain.pem domain.pem > server.pem`.

**Comment by diegombeltran** [comment]
That's right! Including the chain in the server.pem file fixed problems with both clients.

Thank you very much!

**Comment by SyncedSynapse** [comment]
Guess it can be closed

**Comment by basilgello** [comment]
Actually, if the underlying APIs throw meaningful exception, it would be good to inform user what goes wrong so we dont have to guess wgat happens inside the TLS channel.
