### ISSUE TITLE
"invalid params" upon playback/refresh of some tv-series after upgrade to kodi v19.4-r4

### ISSUE THREAD

**Issue by heeplr** [xbmc/Kore#932]
When trying to refresh the video library or starting playback of specific tv-series (not all of them), "invalid params" toast message appears.

There is no logcat output and kodi debug log output is limited to this:

```
2022-11-02 12:32:31.752 T:3360332   DEBUG <general>: JSONRPC: Incoming request: {"jsonrpc":"2.0","method":"Player.Open","id":4510,"params":{"item":{"episodeid":1194}}}
```

and

```
022-11-02 12:33:10.669 T:3464558   DEBUG <general>: JSONRPC: Incoming request: {"jsonrpc":"2.0","method":"VideoLibrary.GetTVShowDetails","id":4520,"params":{"tvshowid":125,"properties":["title","genre","rating","plot","studio","mpaa","cast","playcount","episode","imdbnumber","premiered","votes","art","file","watchedepisodes","dateadded"]}}
```

If I can provide more information somehow, please let me know.

**Comment by SyncedSynapse** [comment]
Thanks. Some clarifications:
1. This only started happening after you upgraded Kodi to 19.4-r4 ? The previous version worked?
2. What platform are you running Kodi on?
3. You mention that the error when starting playback only happes on certain shows, what about the refresh, does it also happen only on specific tv shows (you can trigger an update for a specific tv show when in the detail of it, or for all tv shows when in the list).

**Comment by heeplr** [comment]
1. Yes
2. Gentoo. It's compiled with the following options:

* X airplay alsa bluetooth css dbus lcms nfs optical pulseaudio system-ffmpeg udev udisks upnp upower vaapi vdpau webserver xslt 

And without:
* -bluray -caps -cec -dav1d -eventclients -gbm -gles -libusb -lirc -mariadb -mysql -power-control -raspberry-pi -samba -test -udf -wayland -zeroconf 

3. Yes, refresh works for all those shows, where also playback works. Refresh inside the list of all series works always. Inside detail of one problematic show doesn't work and in the episode list of that show also doesn't work.

Could this maybe be a Kodi bug and not Kore related at all?

**Comment by SyncedSynapse** [comment]
Have you tried cleaning and updating your Kodi's video library, and then refresh it on Kore.

**Comment by heeplr** [comment]
Yes, that was the first thing I tried.

Am I doing the kodi debugging right? I'm surprised that Kore seems to get "invalid params" from Kodi, but Kodi not outputting anything about it in the logs with all debugging settings activated.

**Comment by basilgello** [comment]
You can curl the JSON-RPC endpoint directly:

```
curl -s -X POST -H "Content-Type: application/json" --data-binary '<request-json>' "http://user:pass@ip:port/jsonrpc"
```

**Comment by SyncedSynapse** [comment]
Did you manage to directly call via json-rpc, and did you get the same result? If so, that might indicate that the issue is with Kodi, not Kore.

In the GetDetails call, try deleting some of the params, to see if it makes a difference, ie, instead of

`
{"jsonrpc":"2.0","method":"VideoLibrary.GetTVShowDetails","id":4520,"params":{"tvshowid":125,"properties":["title","genre","rating","plot","studio","mpaa","cast","playcount","episode","imdbnumber","premiered","votes","art","file","watchedepisodes","dateadded"]}}
`

just send:

`
{"jsonrpc":"2.0","method":"VideoLibrary.GetTVShowDetails","id":4520,"params":{"tvshowid":125,"properties":["title"]}}
`

(play with what's inside the `properties` tag to see if you find one that triggers the issue.

**Comment by basilgello** [comment]
Another question @heeplr : did you enable database logging in the advanced logging selector? It might be a database issue, too

**Comment by heeplr** [comment]
thanks for all the hints.

@basilgello yes, database logging was enabled but no errors/warnings

Today I did a fresh setup of Kodi and can't reproduce the issue now anymore. That strongly suggests that the issue is related to some corruption in my decade old installation.

Closing this now. If it occurs again, I'll try more debugging and reopen the issue. Sorry for wasting your time :-(
