### ISSUE TITLE
Kore does not retain https portion of Kodi host address when using SSL

### ISSUE THREAD

**Issue by appletalk** [xbmc/Kore#934]
### Describe the bug
Here is a clear and concise description of what the problem is:

When adding a Kodi host to Kore using an https address it functions normally (ie. https://kodi-host), but when the host entry is edited the https:// portion is dropped from the Address field (ie. kodi-host). I believe this is a minor Kore UI bug.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Kore should save the https portion of the address with the host record or default to using https if port 443 is entered.

## Actual Behavior

Anytime an existing Kodi host entry using https is edited Kore only displays the hostname portion and attempts to connect over http which fails. This then requires https:// to be manually added every time a change is made.

## Possible Fix

If port 443 is entered to connect to Kodi, Kore should attempt to use https by default. Or it should retain the https portion of the url if it is used to connect. (Or both)

### To Reproduce

1. Under Kodi Settings -> Services -> Control -> Enable SSL (This will require a server.pem and server.key in the userdata dir)
2. Add the Kodi host in Kore using https://kodi-host for the address field and other required information to add the host
3. Save and confirm Kore connectivity is working
4. Edit the host entry in Kore and see that the https portion of the url has been removed
5. Click Test and Kore will not connect to Kodi because it tries http rather than https

### Debuglog

The debuglog can be found here:
I can provide a debug log if needed, but it doesn't seem relevent for this minor bug as this is a Kore UI issue.

### Your Environment
Used Operating system:

 - Mobile device: Pixel 5
 - Android version: Android 13
 - Kodi version and platform: Kodi 19.4 on OSMC
 - Kore version: 3.0.0 F-Droid
 

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by SyncedSynapse** [comment]
Fixed #945
