### ISSUE TITLE
Sort albums by year (Artist view)

### ISSUE THREAD

**Issue by Mynacol** [xbmc/Kore#936]
## Feature suggestion

I have an artist with over 200 albums and those are named "1 foo..." "2 bar..." [...] "100 baz...". The current sorting of those is "1 foo..." "10 bar..." "100 baz..." [...] "199 foo.." and only then "2 bar...". I would like them to be lexically sorted.

Previously, I would just sort by release year, which matches the numbering scheme nicely. After the v3 release (thanks btw for this beautiful update) the sorting options are gone. Re-implementing them would be welcomed.

**Comment by SyncedSynapse** [comment]
The same sorting options are there, nothing changed...
When in the Album tab, the sorting options can be accessed in the 3 dots menu, and there's the "Artist year" option. Don't those appear to you?

**Comment by JungleJim42** [comment]
Hi! Thanks for this great app! I only miss one feature from that was lost from the last version: in the artist view, when there is a list of all albums by that artist, I wish they could be sorted by year or date. So that when I look at my "Genesis" artist view, I see all Genesis albums listed by year. Thanks!

**Comment by JungleJim42** [comment]
I think the change to do would be to modify one line in:
app/src/main/java/org/xbmc/kore/ui/sections/audio/ArtistAlbumsListFragment.java
Line 133 - change SORT_BY_ALBUM to SORT_BY_YEAR
I never modified an Android app so I do not know how to test.

**Comment by JungleJim42** [comment]
Ok I used Android Studio to test the change and it worked. I made a pull request. Thanks!
