### ISSUE TITLE
Use term “playlist” in the same manner as Kodi

### ISSUE THREAD

**Issue by mvglasow** [xbmc/Kore#937]
## Feature suggestion
**Detailed Description**

Out “in the wild”, the term *playlist* is used with two different meanings:
1. list of items queued to be played (each item will play after those before it have), also referred to as *play queue*
2. stored list of multiple playable items, usually with a name for the list, which can be added to the play queue as a single action

In Kodi itself, [1] is called play queue, while playlist refers to [2]. Kore currently does not support [2], and uses playlist for [1].

### Context

It would be preferable to be consistent in use of terminology: playlist refers to [2] while [1] is referred to as play queue. If the same term refers to different things in Kodi vs. Kore, users may get confused.

### Possible Implementation

In UI strings for Kore, simply replace all occurrences of “playlist” with “play queue” or just “queue”. Translations will need to be looked at separately, but the same rule applies: follow Kodi terminology.

### Additional context, screenshots or links
Here are some relevant links or screenshots:

(none)

*Note: Team Kodi will consider this item however we will not make any promises if it will be included.*

**Comment by SyncedSynapse** [comment]
Make sense, will keep it in mind.

**Comment by SyncedSynapse** [comment]
Fixed in #944
