### ISSUE TITLE
[FEATURE REQUEST] Please add option to enable vibration on button press

### ISSUE THREAD

**Issue by wp9015362** [xbmc/Kore#95]
@SyncedSynapse :

Could you please add an option to Kore which allows enabling vibration on button press, so that the device vibrates when you press a button on the touchscreen?

It would be much appreciated.

Regards

**Comment by akshay2000** [comment]
I have implemented this feature and created pull request #100. Let's see if this gets accepted.

**Comment by wp9015362** [comment]
@SyncedSynapse :

Thanks for merging. Is there any ETA for when a new version with this feature will be available via the Google Play Store?

Regards

**Comment by SyncedSynapse** [comment]
Beta sometime during this week. Release probably in the middle of August.
