### ISSUE TITLE
[Feature request]  A dialog box for selecting a specific media player when playing over the network

### ISSUE THREAD

**Issue by serj-47** [xbmc/Kore#951]
In my home network, there are two kodi players, one installed in the bedroom and the other in the living room, and both kodi players are also added to the kore app. When I share a YouTube link from my phone with the kore app, I can't choose where exactly the video will be played, kore always sends the video to the kodi player that was used last. It would be convenient if, when sending a youtube link to the kore application, a dialog box appeared with the selection of a specific player in kore.

**Comment by basilgello** [comment]
Please open the feature request there: https://forum.kodi.tv/forumdisplay.php?fid=9 Github is only a bug tracker!
