### ISSUE TITLE
Sidebar library access with Plexbmc

### ISSUE THREAD

**Issue by MetaUserName** [xbmc/Kore#96]
When I first setup kodi the kore sidebar gave me access to my library, when I changed my library to be handled by plexbmc the sidebar takes me to a empty library, I realise the sidebar is working but the library does not connect to the plexbmc library

**Comment by SyncedSynapse** [comment]
This is most likely an issue with Kodi itself. I can't replicate this, but most likely the json-rpc calls don't work with plexbmc (have no clue, as i'm not familiar with it).
