### ISSUE TITLE
TV Shows view capped at 299 entries

### ISSUE THREAD

**Issue by fifthrider** [xbmc/Kore#97]
When presented with a large library, Kore fails to scan all titles to be browseable on Android.  A seemingly random selection of titles do scan properly, totaling approximately 299 titles.  (Unfortunately, since there isn't a counter built into Kore itself, I'm relying on my relatively fallible ability to count by hand.)  If a title on that list is removed from the library and subsequently re-added, it does not subsequently reappear; another title takes its place.  My suspicion, although I am unable to demonstrate this rigorously, is that shows are somehow being added in reverse last-modified order until a certain maximum number is reached, after which Kore stops scanning and caching.

Steps to replicate: have a library with 300 or more TV Show entries in it; attempt to scan that library with Kore.

Expected outcome: all TV shows in library are visible through Kore.

Actual outcome: total number of visible TV show entries is capped at approximately 299.

**Comment by SyncedSynapse** [comment]
There is no limit for the tv shows, though it is possible that the sync service isn't finishing successfully so it doesn't sync all shows.

If you do a refresh and wait for it to end, does it end successfully? Any messages shown?

**Comment by fifthrider** [comment]
Thanks for the reply-

It completes apparently normally, (no error messages), but does not add or remove any entries - still 299 or so shows and 54.17MB of cache.  Is there a way of getting a console readout or log from Kore to see what's going on?

**Comment by SyncedSynapse** [comment]
Are you able to connect your device to your computer, compile a debug version of this (gradlew installDebug) and check the messages that appear on logcat?

**Comment by fifthrider** [comment]
Sure.  Capture started about a second before I started the update, and was stopped about a second after it completed.  No indication of a failed sync; even gave the 'success' popup.

In two pieces because even after redacting as much unrelated noise as I could on the logs it was too big for pastebin.

http://pastebin.com/Y1UJ2i2n
http://pastebin.com/jdYr904S

**Comment by SyncedSynapse** [comment]
Thnks for this, though it wasn't a debug build of Kore, so it doesn't contain the relevant log messages...

Are you able to compile a debug version of Kore? If not, you can get it from here:
https://drive.google.com/file/d/0B8b8P_pnImuPdkF5NEhvVkV2MEE/view?usp=sharing

(you'll have to uninstall your current version, as Android doesn't allow the coexistence of diferent build types).

Then, run this on a shell, to filter the logcat results:
`adb logcat | grep `adb shell ps | grep org.xbmc.kore | cut -c10-15``

**Comment by fifthrider** [comment]
On the contrary, that definitely *was* a debug build; I compiled it myself with the usual 'gradlew assembleDebug && adb -d install ./app/build/outputs/apk/app-debug.apk' process.  Screenshot of the build folder: https://i.imgur.com/Dbi3f7t.png  The relevant debugging bits in the first run are buried in a pile of semi-related system calls.

Here's the output of 

`adb logcat | grep org.xbmc.kore`

on a fresh debug run.  Still getting "Sync successful"; still getting incomplete syncs.

http://pastebin.com/JmYK0LuA

**Comment by fifthrider** [comment]
Oh, and 

`ps | grep org.xbmc.kore` on my phone gives 

`u0_a152   14505 352   1754996 157528 ffffffff 00000000 S org.xbmc.kore`

Not sure if that's how you meant that shell command you posted to be run; as posted it doesn't do anything because it calls adb twice.  Also, I dispensed with running 

`ps | grep org.xbmc.kore | cut -c10-15`

Because LG doesn't ship cut with its version of GNU coreutils, but I imagine the output would be something like

`14505`

**Comment by SyncedSynapse** [comment]
Ok, i just didn't find the messages i was looking for in the first dump. Unfortunately they also aren't on the second dump... But that is because `adb logcat | grep org.xbmc.kore` will strip them.

Like you said, you need to get the pid of the process, so if you could do `adb shell ps | grep org.xbmc`, get the pid (second row, the `14505` you mention) and then `add logcat | grep pid` to get the relevant  output.

Make sure you get the latest version from git, as i've included some new messages yesterday.

**Comment by fifthrider** [comment]
Got it- thanks for clarifying that.

Also, thanks for whatever you did to add those messages to the output; somehow that patch fixed the bug!  All 440 entries scraped properly, with one minor caveat - it's sorting entries whose titles start with lowercase letters to the end of the list.

http://pastebin.com/h7J7ZfVW

**Comment by SyncedSynapse** [comment]
errrr... The latest patch was supposed to only contain additional log messages, but i inadvertently also changed a constant that determines the amount of tv shows to sync, from 300 to 2 (this was to test in my device).

So, it works syncing 2 at a time, but not 300, though it doesn't blow up with an out of memory and the code is the same... strange.
Anyway, i can't keep it at 2 shows at a time, i'll change it to 200, and ask you to try again to check if it helps.

**Comment by fifthrider** [comment]
Sounds good; I'll keep my build environment ready to go.  Thanks for your help!

**Comment by fifthrider** [comment]
So, not sure if this is the result of a change in the meantime, or just me not noticing because I hadn't added anything to the library in a while, but this issue is back in the current Google Play builds. Maybe you could add a "Large Library Compatibility Mode" toggle to the advanced settings that adjusts the constant down for slow scraping?

**Comment by poisdeux** [comment]
Looks like this is the same issue as #219.
It's on my TODO list to add the fix for other media as well.
But if anyone else has some spare time in the coming weeks and willing to fix this. See #236 on how to do this.

**Comment by poisdeux** [comment]
Fix merged, see #283 

Please reopen if issue persists.
