### ISSUE TITLE
Abandoned?

### ISSUE THREAD

**Issue by DeadSecTr** [xbmc/Kore#997]
Project dead?

**Comment by basilgello** [comment]
Nope

**Comment by DeadSecTr** [comment]
Last update is 1 year ago...

**Comment by basilgello** [comment]
The beta version has been tagged but idk why f-droid did not catch the tag

**Comment by basilgello** [comment]
v3.1.0 tagged. I will ensure the fdroid sees the update

**Comment by woheller69** [comment]
F-Droid has disabled 3.x versions for non-foss dependecies :-(

**Comment by DeadSecTr** [comment]
But why they implement non foss?

**Comment by woheller69** [comment]
I fixed it for F-Droid. The non-FOSS dependency was actually unused, so we could remove it. New build on F-Droid coming soon.
